import { ImportData } from './types';

export const A1_VOCABULARY: ImportData[] = [
  // ЛИЧНИ ЗАМЕНКИ (PERSONAL PRONOUNS)
  { word: "ich", translation: "јас", category: "pronoun", sentence_de: "Ich bin hier.", sentence_mk: "Јас сум овде.", image: "👤" },
  { word: "du", translation: "ти", category: "pronoun", sentence_de: "Du bist da.", sentence_mk: "Ти си таму.", image: "👤" },
  { word: "er", translation: "тој", category: "pronoun", sentence_de: "Er ist groß.", sentence_mk: "Тој е голем.", image: "👦" },
  { word: "sie", translation: "таа", category: "pronoun", sentence_de: "Sie ist klein.", sentence_mk: "Таа е мала.", image: "👧" },
  { word: "es", translation: "тоа", category: "pronoun", sentence_de: "Es ist ein Kind.", sentence_mk: "Тоа е дете.", image: "👶" },
  { word: "wir", translation: "ние", category: "pronoun", sentence_de: "Wir gehen jetzt.", sentence_mk: "Ние одиме сега.", image: "👥" },
  { word: "ihr", translation: "вие", category: "pronoun", sentence_de: "Ihr lernt Deutsch.", sentence_mk: "Вие учите германски.", image: "👥" },
  { word: "sie", translation: "тие", category: "pronoun", sentence_de: "Sie spielen Fußball.", sentence_mk: "Тие играат фудбал.", image: "👥" },
  { word: "Sie", translation: "Вие (персирање)", category: "pronoun", sentence_de: "Wie heißen Sie?", sentence_mk: "Како се викате Вие?", image: "👔" },

  // ПРИСВОЈНИ ЗАМЕНКИ (POSSESSIVE PRONOUNS)
  { word: "mein", translation: "мој", category: "pronoun", gender: "der", sentence_de: "Das ist mein Hund.", sentence_mk: "Ова е моето куче.", image: "🐕" },
  { word: "meine", translation: "моја", category: "pronoun", gender: "die", sentence_de: "Meine Mutter ist hier.", sentence_mk: "Мојата мајка е тука.", image: "👩" },
  { word: "dein", translation: "твој", category: "pronoun", gender: "der", sentence_de: "Dein Buch ist neu.", sentence_mk: "Твојата книга е нова.", image: "📚" },
  { word: "deine", translation: "твоја", category: "pronoun", gender: "die", sentence_de: "Deine Schwester ist nett.", sentence_mk: "Твојата сестра е фина.", image: "👧" },
  { word: "sein", translation: "негов", category: "pronoun", gender: "der", sentence_de: "Sein Auto ist rot.", sentence_mk: "Неговиот автомобил е црвен.", image: "🚗" },
  { word: "seine", translation: "негова", category: "pronoun", gender: "die", sentence_de: "Seine Frau arbeitet.", sentence_mk: "Неговата жена работи.", image: "👩‍💼" },
  { word: "ihr", translation: "нејзин", category: "pronoun", gender: "der", sentence_de: "Ihr Mann ist Arzt.", sentence_mk: "Нејзиниот маж е доктор.", image: "👨‍⚕️" },
  { word: "ihre", translation: "нејзина", category: "pronoun", gender: "die", sentence_de: "Ihre Kinder spielen.", sentence_mk: "Нејзините деца играат.", image: "👧👦" },
  { word: "unser", translation: "наш", category: "pronoun", gender: "der", sentence_de: "Unser Haus ist groß.", sentence_mk: "Нашата куќа е голема.", image: "🏠" },
  { word: "unsere", translation: "наша", category: "pronoun", gender: "die", sentence_de: "Unsere Stadt ist schön.", sentence_mk: "Нашиот град е убав.", image: "🏙️" },
  { word: "euer", translation: "ваш", category: "pronoun", gender: "der", sentence_de: "Euer Lehrer ist gut.", sentence_mk: "Вашиот учител е добар.", image: "👨‍🏫" },
  { word: "eure", translation: "ваша", category: "pronoun", gender: "die", sentence_de: "Eure Wohnung ist klein.", sentence_mk: "Вашиот стан е мал.", image: "🏢" },
  { word: "ihr", translation: "нивен", category: "pronoun", gender: "der", sentence_de: "Ihr Sohn ist in Berlin.", sentence_mk: "Нивниот син е во Берлин.", image: "🇩🇪" },
  { word: "ihre", translation: "нивна", category: "pronoun", gender: "die", sentence_de: "Ihre Tochter lernt Deutsch.", sentence_mk: "Нивната ќерка учи германски.", image: "📖" },
  { word: "Ihr", translation: "Ваш (персирање)", category: "pronoun", gender: "der", sentence_de: "Ist Ihr Pass hier?", sentence_mk: "Дали Вашиот пасош е овде?", image: "🛂" },

  // ПРАШАЛНИ ЗБОРОВИ (QUESTION WORDS)
  { word: "wer", translation: "кој", category: "other", sentence_de: "Wer ist das?", sentence_mk: "Кој е тоа?", image: "❓" },
  { word: "was", translation: "што", category: "other", sentence_de: "Was machst du?", sentence_mk: "Што правиш?", image: "❓" },
  { word: "wo", translation: "каде", category: "other", sentence_de: "Wo wohnst du?", sentence_mk: "Каде живееш?", image: "📍" },
  { word: "woher", translation: "од каде", category: "other", sentence_de: "Woher kommst du?", sentence_mk: "Од каде доаѓаш?", image: "🌍" },
  { word: "wohin", translation: "накаде", category: "other", sentence_de: "Wohin gehst du?", sentence_mk: "Каде одиш?", image: "➡️" },
  { word: "wann", translation: "кога", category: "other", sentence_de: "Wann kommst du?", sentence_mk: "Кога доаѓаш?", image: "⏰" },
  { word: "warum", translation: "зошто", category: "other", sentence_de: "Warum lernst du Deutsch?", sentence_mk: "Зошто учиш германски?", image: "🤔" },
  { word: "wie", translation: "како", category: "other", sentence_de: "Wie geht es dir?", sentence_mk: "Како си?", image: "😊" },
  { word: "wie viel", translation: "колку", category: "other", sentence_de: "Wie viel kostet das?", sentence_mk: "Колку чини тоа?", image: "💰" },
  { word: "welcher", translation: "кој (машки)", category: "other", sentence_de: "Welcher Tag ist heute?", sentence_mk: "Кој ден е денес?", image: "📅" },
  { word: "welche", translation: "која (женски)", category: "other", sentence_de: "Welche Farbe magst du?", sentence_mk: "Која боја ја сакаш?", image: "🎨" },
  { word: "welches", translation: "кое (среден)", category: "other", sentence_de: "Welches Buch liest du?", sentence_mk: "Која книга ја читаш?", image: "📖" },

  // ДЕНОВИ ВО НЕДЕЛАТА (DAYS OF THE WEEK)
  { word: "Montag", translation: "понеделник", category: "noun", gender: "der", sentence_de: "Am Montag arbeite ich.", sentence_mk: "Во понеделник работам.", image: "📅" },
  { word: "Dienstag", translation: "вторник", category: "noun", gender: "der", sentence_de: "Dienstag habe ich frei.", sentence_mk: "Во вторник сум слободен.", image: "📅" },
  { word: "Mittwoch", translation: "среда", category: "noun", gender: "der", sentence_de: "Heute ist Mittwoch.", sentence_mk: "Денес е среда.", image: "📅" },
  { word: "Donnerstag", translation: "четврток", category: "noun", gender: "der", sentence_de: "Donnerstag gehe ich zum Arzt.", sentence_mk: "Во четврток одам на доктор.", image: "📅" },
  { word: "Freitag", translation: "петок", category: "noun", gender: "der", sentence_de: "Am Freitag ist Party.", sentence_mk: "Во петок има забава.", image: "🎉" },
  { word: "Samstag", translation: "сабота", category: "noun", gender: "der", sentence_de: "Samstag gehe ich einkaufen.", sentence_mk: "Во сабота одам во купување.", image: "🛒" },
  { word: "Sonntag", translation: "недела", category: "noun", gender: "der", sentence_de: "Sonntag ist Ruhetag.", sentence_mk: "Недела е ден за одмор.", image: "🛌" },
  { word: "der Tag", translation: "денот", category: "noun", gender: "der", sentence_de: "Der Tag ist lang.", sentence_mk: "Денот е долг.", image: "☀️" },
  { word: "die Woche", translation: "неделата", category: "noun", gender: "die", sentence_de: "Die Woche hat sieben Tage.", sentence_mk: "Неделата има седум дена.", image: "📆" },
  { word: "das Wochenende", translation: "викендот", category: "noun", gender: "das", sentence_de: "Am Wochenende schlafe ich lang.", sentence_mk: "За викенд спијам долго.", image: "😴" },

  // МЕСЕЦИ (MONTHS)
  { word: "Januar", translation: "јануари", category: "noun", gender: "der", sentence_de: "Januar ist kalt.", sentence_mk: "Јануари е студен.", image: "❄️" },
  { word: "Februar", translation: "февруари", category: "noun", gender: "der", sentence_de: "Februar hat 28 Tage.", sentence_mk: "Февруари има 28 дена.", image: "📅" },
  { word: "März", translation: "март", category: "noun", gender: "der", sentence_de: "Im März wird es wärmer.", sentence_mk: "Во март станува потопло.", image: "🌱" },
  { word: "April", translation: "април", category: "noun", gender: "der", sentence_de: "April, April!", sentence_mk: "Април, април!", image: "🌸" },
  { word: "Mai", translation: "мај", category: "noun", gender: "der", sentence_de: "Im Mai blühen Blumen.", sentence_mk: "Во мај цветаат цвеќиња.", image: "🌼" },
  { word: "Juni", translation: "јуни", category: "noun", gender: "der", sentence_de: "Im Juni ist Sommer.", sentence_mk: "Во јуни е лето.", image: "☀️" },
  { word: "Juli", translation: "јули", category: "noun", gender: "der", sentence_de: "Im Juli habe ich Urlaub.", sentence_mk: "Во јули имам одмор.", image: "🏖️" },
  { word: "August", translation: "август", category: "noun", gender: "der", sentence_de: "August ist heiß.", sentence_mk: "Август е топол.", image: "🔥" },
  { word: "September", translation: "септември", category: "noun", gender: "der", sentence_de: "Im September beginnt die Schule.", sentence_mk: "Во септември започнува училиштето.", image: "🏫" },
  { word: "Oktober", translation: "октомври", category: "noun", gender: "der", sentence_de: "Im Oktober ist Herbst.", sentence_mk: "Во октомври е есен.", image: "🍂" },
  { word: "November", translation: "ноември", category: "noun", gender: "der", sentence_de: "November ist grau.", sentence_mk: "Ноември е сив.", image: "☁️" },
  { word: "Dezember", translation: "декември", category: "noun", gender: "der", sentence_de: "Im Dezember ist Weihnachten.", sentence_mk: "Во декември е Божиќ.", image: "🎄" },

  // ВРЕМЕ (TIME)
  { word: "die Uhr", translation: "часовникот", category: "noun", gender: "die", sentence_de: "Die Uhr tickt.", sentence_mk: "Часовникот отчукува.", image: "⏰" },
  { word: "die Stunde", translation: "часот (време)", category: "noun", gender: "die", sentence_de: "Eine Stunde hat 60 Minuten.", sentence_mk: "Еден час има 60 минути.", image: "⏱️" },
  { word: "die Minute", translation: "минутата", category: "noun", gender: "die", sentence_de: "Fünf Minuten Pause.", sentence_mk: "Пет минути пауза.", image: "⏲️" },
  { word: "die Sekunde", translation: "секундата", category: "noun", gender: "die", sentence_de: "Eine Sekunde, bitte!", sentence_mk: "Една секунда, ве молам!", image: "⏱️" },
  { word: "der Morgen", translation: "утрото", category: "noun", gender: "der", sentence_de: "Guten Morgen!", sentence_mk: "Добро утро!", image: "🌅" },
  { word: "der Vormittag", translation: "предпладнето", category: "noun", gender: "der", sentence_de: "Am Vormittag arbeite ich.", sentence_mk: "Предпладне работам.", image: "☀️" },
  { word: "der Mittag", translation: "пладнето", category: "noun", gender: "der", sentence_de: "Um 12 Uhr ist Mittag.", sentence_mk: "Во 12 часот е пладне.", image: "☀️" },
  { word: "der Nachmittag", translation: "попладнето", category: "noun", gender: "der", sentence_de: "Am Nachmittag lerne ich.", sentence_mk: "Попладне учам.", image: "🌤️" },
  { word: "der Abend", translation: "вечерта", category: "noun", gender: "der", sentence_de: "Guten Abend!", sentence_mk: "Добровечер!", image: "🌆" },
  { word: "die Nacht", translation: "ноќта", category: "noun", gender: "die", sentence_de: "Gute Nacht!", sentence_mk: "Добра ноќ!", image: "🌙" },
  { word: "heute", translation: "денес", category: "other", sentence_de: "Heute ist schönes Wetter.", sentence_mk: "Денес е убаво време.", image: "☀️" },
  { word: "gestern", translation: "вчера", category: "other", sentence_de: "Gestern war ich im Kino.", sentence_mk: "Вчера бев во кино.", image: "🎬" },
  { word: "morgen", translation: "утре", category: "other", sentence_de: "Morgen habe ich Zeit.", sentence_mk: "Утре имам време.", image: "📅" },
  { word: "übermorgen", translation: "задутре", category: "other", sentence_de: "Übermorgen ist Freitag.", sentence_mk: "Задутре е петок.", image: "📆" },
  { word: "jetzt", translation: "сега", category: "other", sentence_de: "Jetzt lerne ich Deutsch.", sentence_mk: "Сега учам германски.", image: "📚" },
  { word: "später", translation: "подоцна", category: "other", sentence_de: "Später gehe ich einkaufen.", sentence_mk: "Подоцна одам да купувам.", image: "🛒" },
  { word: "früh", translation: "рано", category: "other", sentence_de: "Ich stehe früh auf.", sentence_mk: "Станувам рано.", image: "🌄" },
  { word: "spät", translation: "доцна", category: "other", sentence_de: "Es ist spät.", sentence_mk: "Доцна е.", image: "🌃" },

  // ГОДИШНИ ВРЕМИЊА (SEASONS)
  { word: "der Frühling", translation: "пролетта", category: "noun", gender: "der", sentence_de: "Im Frühling ist es mild.", sentence_mk: "Во пролет е благо.", image: "🌸" },
  { word: "der Sommer", translation: "летото", category: "noun", gender: "der", sentence_de: "Im Sommer scheint die Sonne.", sentence_mk: "Во лето сонцето сјае.", image: "☀️" },
  { word: "der Herbst", translation: "есента", category: "noun", gender: "der", sentence_de: "Im Herbst regnet es oft.", sentence_mk: "Во есен често врне.", image: "🍂" },
  { word: "der Winter", translation: "зимата", category: "noun", gender: "der", sentence_de: "Im Winter schneit es.", sentence_mk: "Во зима врне снег.", image: "❄️" },

  // БОИ (COLORS)
  { word: "rot", translation: "црвена", category: "adjective", sentence_de: "Das Auto ist rot.", sentence_mk: "Автомобилот е црвен.", image: "🔴" },
  { word: "blau", translation: "сина", category: "adjective", sentence_de: "Der Himmel ist blau.", sentence_mk: "Небото е сино.", image: "🔵" },
  { word: "grün", translation: "зелена", category: "adjective", sentence_de: "Das Gras ist grün.", sentence_mk: "Тревата е зелена.", image: "🟢" },
  { word: "gelb", translation: "жолта", category: "adjective", sentence_de: "Die Banane ist gelb.", sentence_mk: "Бананата е жолта.", image: "🟡" },
  { word: "orange", translation: "портокалова", category: "adjective", sentence_de: "Die Orange ist orange.", sentence_mk: "Портокалот е портокалов.", image: "🟠" },
  { word: "braun", translation: "кафеава", category: "adjective", sentence_de: "Der Tisch ist braun.", sentence_mk: "Масата е кафеава.", image: "🟤" },
  { word: "schwarz", translation: "црна", category: "adjective", sentence_de: "Die Nacht ist schwarz.", sentence_mk: "Ноќта е црна.", image: "⚫" },
  { word: "weiß", translation: "бела", category: "adjective", sentence_de: "Der Schnee ist weiß.", sentence_mk: "Снегот е бел.", image: "⚪" },
  { word: "grau", translation: "сива", category: "adjective", sentence_de: "Der Himmel ist grau.", sentence_mk: "Небото е сиво.", image: "⬜" },
  { word: "pink", translation: "розова", category: "adjective", sentence_de: "Die Blume ist pink.", sentence_mk: "Цветот е розов.", image: "🌸" },
  { word: "lila", translation: "виолетова", category: "adjective", sentence_de: "Der Pullover ist lila.", sentence_mk: "Пуловерот е виолетов.", image: "🟣" },
  { word: "bunt", translation: "шарена", category: "adjective", sentence_de: "Das Bild ist bunt.", sentence_mk: "Сликата е шарена.", image: "🌈" },
  { word: "hell", translation: "светла", category: "adjective", sentence_de: "Das Zimmer ist hell.", sentence_mk: "Собата е светла.", image: "💡" },
  { word: "dunkel", translation: "темна", category: "adjective", sentence_de: "Es ist dunkel.", sentence_mk: "Темно е.", image: "🌑" },

  // БРОЕВИ (NUMBERS 1-100)
  { word: "null", translation: "нула", category: "other", sentence_de: "Null Grad.", sentence_mk: "Нула степени.", image: "0️⃣" },
  { word: "eins", translation: "еден", category: "other", sentence_de: "Eins, zwei, drei.", sentence_mk: "Еден, два, три.", image: "1️⃣" },
  { word: "zwei", translation: "два", category: "other", sentence_de: "Zwei Äpfel.", sentence_mk: "Две јаболка.", image: "2️⃣" },
  { word: "drei", translation: "три", category: "other", sentence_de: "Drei Katzen.", sentence_mk: "Три мачки.", image: "3️⃣" },
  { word: "vier", translation: "четири", category: "other", sentence_de: "Vier Hunde.", sentence_mk: "Четири кучиња.", image: "4️⃣" },
  { word: "fünf", translation: "пет", category: "other", sentence_de: "Fünf Finger.", sentence_mk: "Пет прсти.", image: "5️⃣" },
  { word: "sechs", translation: "шест", category: "other", sentence_de: "Sechs Kinder.", sentence_mk: "Шест деца.", image: "6️⃣" },
  { word: "sieben", translation: "седум", category: "other", sentence_de: "Sieben Tage.", sentence_mk: "Седум дена.", image: "7️⃣" },
  { word: "acht", translation: "осум", category: "other", sentence_de: "Acht Stunden.", sentence_mk: "Осум часа.", image: "8️⃣" },
  { word: "neun", translation: "девет", category: "other", sentence_de: "Neun Monate.", sentence_mk: "Девет месеци.", image: "9️⃣" },
  { word: "zehn", translation: "десет", category: "other", sentence_de: "Zehn Euro.", sentence_mk: "Десет евра.", image: "🔟" },
  { word: "elf", translation: "единаесет", category: "other", sentence_de: "Elf Spieler.", sentence_mk: "Единаесет играчи.", image: "1️⃣1️⃣" },
  { word: "zwölf", translation: "дванаесет", category: "other", sentence_de: "Zwölf Monate.", sentence_mk: "Дванаесет месеци.", image: "1️⃣2️⃣" },
  { word: "dreizehn", translation: "тринаесет", category: "other", sentence_de: "Dreizehn ist eine Unglückszahl.", sentence_mk: "Тринаесет е несреќен број.", image: "1️⃣3️⃣" },
  { word: "vierzehn", translation: "четиринаесет", category: "other", sentence_de: "Vierzehn Tage.", sentence_mk: "Четиринаесет дена.", image: "1️⃣4️⃣" },
  { word: "fünfzehn", translation: "петнаесет", category: "other", sentence_de: "Fünfzehn Minuten.", sentence_mk: "Петнаесет минути.", image: "1️⃣5️⃣" },
  { word: "sechzehn", translation: "шеснаесет", category: "other", sentence_de: "Sechzehn Jahre.", sentence_mk: "Шеснаесет години.", image: "1️⃣6️⃣" },
  { word: "siebzehn", translation: "седумнаесет", category: "other", sentence_de: "Siebzehn Uhr.", sentence_mk: "Седумнаесет часот.", image: "1️⃣7️⃣" },
  { word: "achtzehn", translation: "осумнаесет", category: "other", sentence_de: "Achtzehn Grad.", sentence_mk: "Осумнаесет степени.", image: "1️⃣8️⃣" },
  { word: "neunzehn", translation: "деветнаесет", category: "other", sentence_de: "Neunzehn Euro.", sentence_mk: "Деветнаесет евра.", image: "1️⃣9️⃣" },
  { word: "zwanzig", translation: "дваесет", category: "other", sentence_de: "Ich bin zwanzig Jahre alt.", sentence_mk: "Имам дваесет години.", image: "2️⃣0️⃣" },
  { word: "einundzwanzig", translation: "дваесет и еден", category: "other", sentence_de: "Einundzwanzig ist meine Glückszahl.", sentence_mk: "Дваесет и еден е мојот среќен број.", image: "2️⃣1️⃣" },
  { word: "dreißig", translation: "триесет", category: "other", sentence_de: "Dreißig Tage.", sentence_mk: "Триесет дена.", image: "3️⃣0️⃣" },
  { word: "vierzig", translation: "четириесет", category: "other", sentence_de: "Vierzig Wochen.", sentence_mk: "Четириесет недели.", image: "4️⃣0️⃣" },
  { word: "fünfzig", translation: "педесет", category: "other", sentence_de: "Fünfzig Euro.", sentence_mk: "Педесет евра.", image: "5️⃣0️⃣" },
  { word: "sechzig", translation: "шеесет", category: "other", sentence_de: "Sechzig Minuten.", sentence_mk: "Шеесет минути.", image: "6️⃣0️⃣" },
  { word: "siebzig", translation: "седумдесет", category: "other", sentence_de: "Siebzig Jahre.", sentence_mk: "Седумдесет години.", image: "7️⃣0️⃣" },
  { word: "achtzig", translation: "осумдесет", category: "other", sentence_de: "Achtzig Kilometer.", sentence_mk: "Осумдесет километри.", image: "8️⃣0️⃣" },
  { word: "neunzig", translation: "деведесет", category: "other", sentence_de: "Neunzig Prozent.", sentence_mk: "Деведесет проценти.", image: "9️⃣0️⃣" },
  { word: "hundert", translation: "сто", category: "other", sentence_de: "Hundert Euro.", sentence_mk: "Сто евра.", image: "💯" },

  // ЧЛЕНОВИ НА СЕМЕЈСТВО (FAMILY MEMBERS)
  { word: "der Vater", translation: "таткото", category: "noun", gender: "der", sentence_de: "Mein Vater arbeitet viel.", sentence_mk: "Татко ми работи многу.", image: "👨" },
  { word: "die Mutter", translation: "мајката", category: "noun", gender: "die", sentence_de: "Meine Mutter kocht gut.", sentence_mk: "Мајка ми готви добро.", image: "👩" },
  { word: "der Sohn", translation: "синот", category: "noun", gender: "der", sentence_de: "Unser Sohn geht zur Schule.", sentence_mk: "Нашиот син оди на училиште.", image: "👦" },
  { word: "die Tochter", translation: "ќерката", category: "noun", gender: "die", sentence_de: "Meine Tochter lernt Klavier.", sentence_mk: "Ќерка ми учи пијано.", image: "👧" },
  { word: "der Bruder", translation: "братот", category: "noun", gender: "der", sentence_de: "Mein Bruder ist älter.", sentence_mk: "Брат ми е постар.", image: "👨‍🦰" },
  { word: "die Schwester", translation: "сестрата", category: "noun", gender: "die", sentence_de: "Meine Schwester ist jünger.", sentence_mk: "Сестра ми е помлада.", image: "👩‍🦰" },
  { word: "der Opa", translation: "дедото", category: "noun", gender: "der", sentence_de: "Mein Opa erzählt Geschichten.", sentence_mk: "Дедо ми раскажува приказни.", image: "👴" },
  { word: "die Oma", translation: "бабата", category: "noun", gender: "die", sentence_de: "Meine Oma backt Kuchen.", sentence_mk: "Баба ми пече колачи.", image: "👵" },
  { word: "der Enkel", translation: "внукот", category: "noun", gender: "der", sentence_de: "Der Enkel besucht die Oma.", sentence_mk: "Внукот ја посетува бабата.", image: "👦" },
  { word: "die Enkelin", translation: "внуката", category: "noun", gender: "die", sentence_de: "Die Enkelin spielt mit dem Hund.", sentence_mk: "Внуката си игра со кучето.", image: "👧" },
  { word: "der Onkel", translation: "вујкото/чичкото", category: "noun", gender: "der", sentence_de: "Mein Onkel wohnt in Berlin.", sentence_mk: "Мојот чичко живее во Берлин.", image: "👨" },
  { word: "die Tante", translation: "тетката", category: "noun", gender: "die", sentence_de: "Meine Tante ist Ärztin.", sentence_mk: "Мојата тетка е докторка.", image: "👩‍⚕️" },
  { word: "der Cousin", translation: "братучедот", category: "noun", gender: "der", sentence_de: "Mein Cousin spielt Fußball.", sentence_mk: "Мојот братучед игра фудбал.", image: "⚽" },
  { word: "die Cousine", translation: "братучетката", category: "noun", gender: "die", sentence_de: "Meine Cousine tanzt gern.", sentence_mk: "Мојата братучетка сака да танцува.", image: "💃" },
  { word: "die Familie", translation: "семејството", category: "noun", gender: "die", sentence_de: "Meine Familie ist groß.", sentence_mk: "Моето семејство е големо.", image: "👨‍👩‍👧‍👦" },
  { word: "die Eltern", translation: "родителите", category: "noun", sentence_de: "Meine Eltern sind nett.", sentence_mk: "Моите родители се фини.", image: "👨‍👩" },
  { word: "die Großeltern", translation: "баба и дедо", category: "noun", sentence_de: "Meine Großeltern sind alt.", sentence_mk: "Моите баба и дедо се стари.", image: "👴👵" },
  { word: "die Geschwister", translation: "браќа и сестри", category: "noun", sentence_de: "Hast du Geschwister?", sentence_mk: "Имаш ли браќа или сестри?", image: "👨‍👧‍👦" },

  // ДЕЛОВИ ОД ТЕЛОТО (BODY PARTS)
  { word: "der Kopf", translation: "главата", category: "noun", gender: "der", sentence_de: "Der Kopf tut weh.", sentence_mk: "Главата боли.", image: "👤" },
  { word: "das Gesicht", translation: "лицето", category: "noun", gender: "das", sentence_de: "Sie hat ein schönes Gesicht.", sentence_mk: "Таа има убаво лице.", image: "😊" },
  { word: "das Auge", translation: "окото", category: "noun", gender: "das", sentence_de: "Er hat blaue Augen.", sentence_mk: "Тој има сини очи.", image: "👁️" },
  { word: "die Nase", translation: "носот", category: "noun", gender: "die", sentence_de: "Die Nase riecht.", sentence_mk: "Носот мириса.", image: "👃" },
  { word: "der Mund", translation: "устата", category: "noun", gender: "der", sentence_de: "Öffne den Mund.", sentence_mk: "Отвори ја устата.", image: "👄" },
  { word: "das Ohr", translation: "увото", category: "noun", gender: "das", sentence_de: "Ich höre mit den Ohren.", sentence_mk: "Слушам со ушите.", image: "👂" },
  { word: "die Haare", translation: "косата", category: "noun", sentence_de: "Sie hat lange Haare.", sentence_mk: "Таа има долга коса.", image: "💇" },
  { word: "der Hals", translation: "вратот", category: "noun", gender: "der", sentence_de: "Der Hals tut weh.", sentence_mk: "Грлото боли.", image: "🧣" },
  { word: "die Schulter", translation: "рамото", category: "noun", gender: "die", sentence_de: "Die Schulter schmerzt.", sentence_mk: "Рамото боли.", image: "🤷" },
  { word: "der Arm", translation: "раката", category: "noun", gender: "der", sentence_de: "Er hat starke Arme.", sentence_mk: "Тој има силни раце.", image: "💪" },
  { word: "die Hand", translation: "дланката", category: "noun", gender: "die", sentence_de: "Die Hand schreibt.", sentence_mk: "Раката пишува.", image: "✋" },
  { word: "der Finger", translation: "прстот", category: "noun", gender: "der", sentence_de: "Fünf Finger an der Hand.", sentence_mk: "Пет прсти на раката.", image: "🖐️" },
  { word: "der Daumen", translation: "палецот", category: "noun", gender: "der", sentence_de: "Den Daumen drücken.", sentence_mk: "Држи палци.", image: "👍" },
  { word: "der Bauch", translation: "стомакот", category: "noun", gender: "der", sentence_de: "Ich habe Bauchschmerzen.", sentence_mk: "Ме боли стомак.", image: "🤰" },
  { word: "der Rücken", translation: "грбот", category: "noun", gender: "der", sentence_de: "Der Rücken tut weh.", sentence_mk: "Грбот боли.", image: "🔙" },
  { word: "das Bein", translation: "ногата", category: "noun", gender: "das", sentence_de: "Das Bein ist gebrochen.", sentence_mk: "Ногата е скршена.", image: "🦵" },
  { word: "das Knie", translation: "коленото", category: "noun", gender: "das", sentence_de: "Das Knie schmerzt.", sentence_mk: "Коленото боли.", image: "🦵" },
  { word: "der Fuß", translation: "стапалото", category: "noun", gender: "der", sentence_de: "Der Fuß läuft.", sentence_mk: "Стапалото оди.", image: "🦶" },
  { word: "der Zeh", translation: "прстот на нога", category: "noun", gender: "der", sentence_de: "Ich habe zehn Zehen.", sentence_mk: "Имам десет прсти на нозе.", image: "🦶" },

  // ОБЛЕКА (CLOTHING)
  { word: "die Kleidung", translation: "облеката", category: "noun", gender: "die", sentence_de: "Die Kleidung ist modern.", sentence_mk: "Облеката е модерна.", image: "👚" },
  { word: "das Hemd", translation: "кошулата", category: "noun", gender: "das", sentence_de: "Das Hemd ist weiß.", sentence_mk: "Кошулата е бела.", image: "👔" },
  { word: "das T-Shirt", translation: "маицата", category: "noun", gender: "das", sentence_de: "Das T-Shirt ist blau.", sentence_mk: "Маицата е сина.", image: "👕" },
  { word: "die Bluse", translation: "блузата", category: "noun", gender: "die", sentence_de: "Die Bluse ist rot.", sentence_mk: "Блузата е црвена.", image: "👚" },
  { word: "die Hose", translation: "панталоните", category: "noun", gender: "die", sentence_de: "Die Hose ist neu.", sentence_mk: "Панталоните се нови.", image: "👖" },
  { word: "die Jeans", translation: "фармерките", category: "noun", gender: "die", sentence_de: "Die Jeans sind blau.", sentence_mk: "Фармерките се сини.", image: "👖" },
  { word: "der Rock", translation: "здолништето", category: "noun", gender: "der", sentence_de: "Der Rock ist kurz.", sentence_mk: "Здолништето е кратко.", image: "👗" },
  { word: "das Kleid", translation: "фустанот", category: "noun", gender: "das", sentence_de: "Das Kleid ist schön.", sentence_mk: "Фустанот е убав.", image: "👗" },
  { word: "der Anzug", translation: "оделото", category: "noun", gender: "der", sentence_de: "Der Anzug ist teuer.", sentence_mk: "Оделото е скапо.", image: "🤵" },
  { word: "die Jacke", translation: "јакната", category: "noun", gender: "die", sentence_de: "Die Jacke ist warm.", sentence_mk: "Јакната е топла.", image: "🧥" },
  { word: "der Mantel", translation: "палтото", category: "noun", gender: "der", sentence_de: "Der Mantel ist für den Winter.", sentence_mk: "Палтото е за зима.", image: "🧥" },
  { word: "der Pullover", translation: "пуловерот", category: "noun", gender: "der", sentence_de: "Der Pullover ist aus Wolle.", sentence_mk: "Пуловерот е од волна.", image: "🧶" },
  { word: "der Schuh", translation: "чевелот", category: "noun", gender: "der", sentence_de: "Der Schuh ist braun.", sentence_mk: "Чевелот е кафеав.", image: "👞" },
  { word: "die Schuhe", translation: "чевлите", category: "noun", sentence_de: "Die Schuhe sind neu.", sentence_mk: "Чевлите се нови.", image: "👟" },
  { word: "der Stiefel", translation: "чизмата", category: "noun", gender: "der", sentence_de: "Die Stiefel sind für den Schnee.", sentence_mk: "Чизмите се за снег.", image: "🥾" },
  { word: "die Socke", translation: "чорапот", category: "noun", gender: "die", sentence_de: "Die Socken sind warm.", sentence_mk: "Чорапите се топли.", image: "🧦" },
  { word: "der Hut", translation: "шапката", category: "noun", gender: "der", sentence_de: "Der Hut ist alt.", sentence_mk: "Шапката е стара.", image: "🎩" },
  { word: "die Mütze", translation: "капата", category: "noun", gender: "die", sentence_de: "Die Mütze ist rot.", sentence_mk: "Капата е црвена.", image: "🧢" },
  { word: "der Schal", translation: "шалот", category: "noun", gender: "der", sentence_de: "Der Schal ist lang.", sentence_mk: "Шалот е долг.", image: "🧣" },
  { word: "der Handschuh", translation: "ракавицата", category: "noun", gender: "der", sentence_de: "Die Handschuhe sind warm.", sentence_mk: "Ракавиците се топли.", image: "🧤" },
  { word: "die Brille", translation: "очилата", category: "noun", gender: "die", sentence_de: "Die Brille ist kaputt.", sentence_mk: "Очилата се скршени.", image: "👓" },

  // ХРАНА И ПИЈАЛОЦИ (FOOD AND DRINKS)
  { word: "das Essen", translation: "храната", category: "noun", gender: "das", sentence_de: "Das Essen schmeckt gut.", sentence_mk: "Храната има добар вкус.", image: "🍲" },
  { word: "das Frühstück", translation: "појадокот", category: "noun", gender: "das", sentence_de: "Das Frühstück ist um 8 Uhr.", sentence_mk: "Појадокот е во 8 часот.", image: "🍳" },
  { word: "das Mittagessen", translation: "ручекот", category: "noun", gender: "das", sentence_de: "Das Mittagessen ist fertig.", sentence_mk: "Ручекот е готов.", image: "🍲" },
  { word: "das Abendessen", translation: "вечерата", category: "noun", gender: "das", sentence_de: "Das Abendessen ist leicht.", sentence_mk: "Вечерата е лесна.", image: "🍽️" },
  { word: "das Brot", translation: "лебот", category: "noun", gender: "das", sentence_de: "Das Brot ist frisch.", sentence_mk: "Лебог е свеж.", image: "🍞" },
  { word: "die Butter", translation: "путерот", category: "noun", gender: "die", sentence_de: "Die Butter ist auf dem Tisch.", sentence_mk: "Путерот е на масата.", image: "🧈" },
  { word: "der Käse", translation: "сирењето", category: "noun", gender: "der", sentence_de: "Der Käse ist gelb.", sentence_mk: "Сирењето е жолто.", image: "🧀" },
  { word: "die Wurst", translation: "колбасот", category: "noun", gender: "die", sentence_de: "Die Wurst schmeckt gut.", sentence_mk: "Колбасот има добар вкус.", image: "🌭" },
  { word: "der Schinken", translation: "шунката", category: "noun", gender: "der", sentence_de: "Der Schinken ist auf der Pizza.", sentence_mk: "Шунката е на пицата.", image: "🍖" },
  { word: "das Ei", translation: "јајцето", category: "noun", gender: "das", sentence_de: "Das Ei ist hart gekocht.", sentence_mk: "Јајцето е тврдо варено.", image: "🥚" },
  { word: "der Joghurt", translation: "јогуртот", category: "noun", gender: "der", sentence_de: "Der Joghurt ist süß.", sentence_mk: "Јогуртот е сладок.", image: "🥛" },
  { word: "der Apfel", translation: "јаболкото", category: "noun", gender: "der", sentence_de: "Der Apfel ist rot.", sentence_mk: "Јаболкото е црвено.", image: "🍎" },
  { word: "die Banane", translation: "бананата", category: "noun", gender: "die", sentence_de: "Die Banane ist gelb.", sentence_mk: "Бананата е жолта.", image: "🍌" },
  { word: "die Orange", translation: "портокалот", category: "noun", gender: "die", sentence_de: "Die Orange ist saftig.", sentence_mk: "Портокалот е сочен.", image: "🍊" },
  { word: "die Zitrone", translation: "лимонот", category: "noun", gender: "die", sentence_de: "Die Zitrone ist sauer.", sentence_mk: "Лимонот е кисел.", image: "🍋" },
  { word: "die Erdbeere", translation: "јагодата", category: "noun", gender: "die", sentence_de: "Die Erdbeere ist süß.", sentence_mk: "Јагодата е слатка.", image: "🍓" },
  { word: "die Tomate", translation: "доматот", category: "noun", gender: "die", sentence_de: "Die Tomate ist rot.", sentence_mk: "Доматот е црвен.", image: "🍅" },
  { word: "die Kartoffel", translation: "компирот", category: "noun", gender: "die", sentence_de: "Die Kartoffel ist gesund.", sentence_mk: "Компирот е здрав.", image: "🥔" },
  { word: "die Karotte", translation: "морковот", category: "noun", gender: "die", sentence_de: "Die Karotte ist orange.", sentence_mk: "Морковот е портокалов.", image: "🥕" },
  { word: "der Salat", translation: "салатата", category: "noun", gender: "der", sentence_de: "Der Salat ist frisch.", sentence_mk: "Салатата е свежа.", image: "🥗" },
  { word: "das Fleisch", translation: "месото", category: "noun", gender: "das", sentence_de: "Das Fleisch ist zart.", sentence_mk: "Месото е меко.", image: "🥩" },
  { word: "das Huhn", translation: "пилешкото", category: "noun", gender: "das", sentence_de: "Das Huhn ist gebraten.", sentence_mk: "Пилешкото е печено.", image: "🍗" },
  { word: "der Fisch", translation: "рибата", category: "noun", gender: "der", sentence_de: "Der Fisch ist frisch.", sentence_mk: "Рибата е свежа.", image: "🐟" },
  { word: "die Suppe", translation: "супата", category: "noun", gender: "die", sentence_de: "Die Suppe ist heiß.", sentence_mk: "Супата е топла.", image: "🍲" },
  { word: "der Reis", translation: "оризот", category: "noun", gender: "der", sentence_de: "Der Reis ist weich.", sentence_mk: "Оризот е мек.", image: "🍚" },
  { word: "die Nudeln", translation: "тестенините", category: "noun", sentence_de: "Die Nudeln sind al dente.", sentence_mk: "Тестенините се ал денте.", image: "🍝" },
  { word: "die Pizza", translation: "пицата", category: "noun", gender: "die", sentence_de: "Die Pizza ist italienisch.", sentence_mk: "Пицата е италијанска.", image: "🍕" },
  { word: "der Kuchen", translation: "колачот", category: "noun", gender: "der", sentence_de: "Der Kuchen ist lecker.", sentence_mk: "Колачот е вкусен.", image: "🍰" },
  { word: "das Wasser", translation: "водата", category: "noun", gender: "das", sentence_de: "Das Wasser ist kalt.", sentence_mk: "Водата е ладна.", image: "💧" },
  { word: "der Kaffee", translation: "кафето", category: "noun", gender: "der", sentence_de: "Der Kaffee ist heiß.", sentence_mk: "Кафето е топло.", image: "☕" },
  { word: "der Tee", translation: "чајот", category: "noun", gender: "der", sentence_de: "Der Tee ist grün.", sentence_mk: "Чајот е зелен.", image: "🍵" },
  { word: "der Saft", translation: "сокот", category: "noun", gender: "der", sentence_de: "Der Saft ist süß.", sentence_mk: "Сокот е сладок.", image: "🧃" },
  { word: "die Milch", translation: "млекото", category: "noun", gender: "die", sentence_de: "Die Milch ist weiß.", sentence_mk: "Млекото е бело.", image: "🥛" },
  { word: "das Bier", translation: "пивото", category: "noun", gender: "das", sentence_de: "Das Bier ist kalt.", sentence_mk: "Пивото е ладно.", image: "🍺" },
  { word: "der Wein", translation: "виното", category: "noun", gender: "der", sentence_de: "Der Wein ist rot.", sentence_mk: "Виното е црвено.", image: "🍷" },

  // ГЛАГОЛИ (VERBS)
  { word: "sein", translation: "сум", category: "verb", sentence_de: "Ich bin müde.", sentence_mk: "Уморен сум.", image: "🥱" },
  { word: "haben", translation: "имам", category: "verb", sentence_de: "Ich habe ein Auto.", sentence_mk: "Имам автомобил.", image: "🚗" },
  { word: "werden", translation: "станувам", category: "verb", sentence_de: "Ich werde Lehrer.", sentence_mk: "Станувам учител.", image: "👨‍🏫" },
  { word: "gehen", translation: "одам", category: "verb", sentence_de: "Ich gehe nach Hause.", sentence_mk: "Одам дома.", image: "🚶" },
  { word: "kommen", translation: "доаѓам", category: "verb", sentence_de: "Ich komme aus Berlin.", sentence_mk: "Доаѓам од Берлин.", image: "🚂" },
  { word: "fahren", translation: "возам", category: "verb", sentence_de: "Ich fahre mit dem Bus.", sentence_mk: "Се возам со автобус.", image: "🚌" },
  { word: "fliegen", translation: "летам", category: "verb", sentence_de: "Ich fliege nach Spanien.", sentence_mk: "Летам за Шпанија.", image: "✈️" },
  { word: "laufen", translation: "трчам", category: "verb", sentence_de: "Ich laufe jeden Tag.", sentence_mk: "Трчам секој ден.", image: "🏃" },
  { word: "stehen", translation: "стојам", category: "verb", sentence_de: "Ich stehe an der Haltestelle.", sentence_mk: "Стојам на постојката.", image: "🚏" },
  { word: "sitzen", translation: "седам", category: "verb", sentence_de: "Ich sitze auf dem Stuhl.", sentence_mk: "Седам на столот.", image: "🪑" },
  { word: "liegen", translation: "лежам", category: "verb", sentence_de: "Das Buch liegt auf dem Tisch.", sentence_mk: "Книгата лежи на масата.", image: "📖" },
  { word: "schlafen", translation: "спијам", category: "verb", sentence_de: "Ich schlafe acht Stunden.", sentence_mk: "Спијам осум часа.", image: "😴" },
  { word: "aufstehen", translation: "станувам", category: "verb", sentence_de: "Ich stehe um 7 Uhr auf.", sentence_mk: "Станувам во 7 часот.", image: "⏰" },
  { word: "arbeiten", translation: "работам", category: "verb", sentence_de: "Ich arbeite im Büro.", sentence_mk: "Работам во канцеларија.", image: "💼" },
  { word: "lernen", translation: "учам", category: "verb", sentence_de: "Ich lerne Deutsch.", sentence_mk: "Учам германски.", image: "📚" },
  { word: "studieren", translation: "студирам", category: "verb", sentence_de: "Ich studiere Medizin.", sentence_mk: "Студирам медицина.", image: "🎓" },
  { word: "lesen", translation: "читам", category: "verb", sentence_de: "Ich lese ein Buch.", sentence_mk: "Читам книга.", image: "📖" },
  { word: "schreiben", translation: "пишувам", category: "verb", sentence_de: "Ich schreibe einen Brief.", sentence_mk: "Пишувам писмо.", image: "✍️" },
  { word: "sprechen", translation: "зборувам", category: "verb", sentence_de: "Ich spreche Deutsch.", sentence_mk: "Зборувам германски.", image: "🗣️" },
  { word: "verstehen", translation: "разбирам", category: "verb", sentence_de: "Ich verstehe dich.", sentence_mk: "Те разбирам.", image: "🤔" },
  { word: "fragen", translation: "прашувам", category: "verb", sentence_de: "Ich frage den Lehrer.", sentence_mk: "Го прашувам учителот.", image: "❓" },
  { word: "antworten", translation: "одговарам", category: "verb", sentence_de: "Ich antworte auf die Frage.", sentence_mk: "Одговарам на прашањето.", image: "💬" },
  { word: "erzählen", translation: "раскажувам", category: "verb", sentence_de: "Ich erzähle eine Geschichte.", sentence_mk: "Раскажувам приказна.", image: "📖" },
  { word: "essen", translation: "јадам", category: "verb", sentence_de: "Ich esse einen Apfel.", sentence_mk: "Јадам јаболко.", image: "🍎" },
  { word: "trinken", translation: "пијам", category: "verb", sentence_de: "Ich trinke Wasser.", sentence_mk: "Пијам вода.", image: "💧" },
  { word: "kochen", translation: "готвам", category: "verb", sentence_de: "Ich koche das Abendessen.", sentence_mk: "Готвам вечера.", image: "🍳" },
  { word: "backen", translation: "печам", category: "verb", sentence_de: "Ich backe einen Kuchen.", sentence_mk: "Печам колач.", image: "🍰" },
  { word: "einkaufen", translation: "купувам", category: "verb", sentence_de: "Ich kaufe im Supermarkt ein.", sentence_mk: "Купувам во супермаркет.", image: "🛒" },
  { word: "bezahlen", translation: "плаќам", category: "verb", sentence_de: "Ich bezahle mit Karte.", sentence_mk: "Плаќам со картичка.", image: "💳" },
  { word: "kosten", translation: "чини", category: "verb", sentence_de: "Das kostet 10 Euro.", sentence_mk: "Тоа чини 10 евра.", image: "💰" },
  { word: "spielen", translation: "играм", category: "verb", sentence_de: "Ich spiele Fußball.", sentence_mk: "Играм фудбал.", image: "⚽" },
  { word: "sehen", translation: "гледам", category: "verb", sentence_de: "Ich sehe einen Film.", sentence_mk: "Гледам филм.", image: "🎬" },
  { word: "hören", translation: "слушам", category: "verb", sentence_de: "Ich höre Musik.", sentence_mk: "Слушам музика.", image: "🎵" },
  { word: "fernsehen", translation: "гледам телевизија", category: "verb", sentence_de: "Ich sehe abends fern.", sentence_mk: "Гледам телевизија навечер.", image: "📺" },
  { word: "treffen", translation: "се среќавам", category: "verb", sentence_de: "Ich treffe meine Freunde.", sentence_mk: "Се среќавам со моите пријатели.", image: "🤝" },
  { word: "besuchen", translation: "посетувам", category: "verb", sentence_de: "Ich besuche meine Oma.", sentence_mk: "Ја посетувам баба ми.", image: "👵" },
  { word: "helfen", translation: "помагам", category: "verb", sentence_de: "Ich helfe dir.", sentence_mk: "Ти помагам.", image: "🤝" },
  { word: "danken", translation: "благодарам", category: "verb", sentence_de: "Ich danke dir.", sentence_mk: "Ти благодарам.", image: "🙏" },
  { word: "wünschen", translation: "посакувам", category: "verb", sentence_de: "Ich wünsche dir alles Gute.", sentence_mk: "Ти посакувам се најдобро.", image: "✨" },
  { word: "feiern", translation: "прославувам", category: "verb", sentence_de: "Wir feiern Geburtstag.", sentence_mk: "Прославуваме роденден.", image: "🎉" },
  { word: "tanzen", translation: "танцувам", category: "verb", sentence_de: "Ich tanze gern.", sentence_mk: "Сакам да танцувам.", image: "💃" },
  { word: "singen", translation: "пеам", category: "verb", sentence_de: "Ich singe ein Lied.", sentence_mk: "Пеам песна.", image: "🎤" },
  { word: "malen", translation: "сликам", category: "verb", sentence_de: "Ich male ein Bild.", sentence_mk: "Сликам слика.", image: "🎨" },
  { word: "zeichnen", translation: "цртам", category: "verb", sentence_de: "Ich zeichne einen Baum.", sentence_mk: "Цртам дрво.", image: "✏️" },
  { word: "fotografieren", translation: "фотографирам", category: "verb", sentence_de: "Ich fotografiere die Natur.", sentence_mk: "Го фотографирам пејзажот.", image: "📷" },
  { word: "reisen", translation: "патувам", category: "verb", sentence_de: "Ich reise gern.", sentence_mk: "Сакам да патувам.", image: "🧳" },
  { word: "bleiben", translation: "останувам", category: "verb", sentence_de: "Ich bleibe zu Hause.", sentence_mk: "Останувам дома.", image: "🏠" },
  { word: "wohnen", translation: "живеам", category: "verb", sentence_de: "Ich wohne in Berlin.", sentence_mk: "Живеам во Берлин.", image: "🏙️" },
  { word: "leben", translation: "живеам (постојам)", category: "verb", sentence_de: "Ich lebe glücklich.", sentence_mk: "Живеам среќно.", image: "😊" },
  { word: "gebären", translation: "раѓам", category: "verb", sentence_de: "Sie gebärt ein Kind.", sentence_mk: "Таа раѓа дете.", image: "👶" },
  { word: "sterben", translation: "умирам", category: "verb", sentence_de: "Der Patient stirbt.", sentence_mk: "Пациентот умира.", image: "💀" },
  { word: "lieben", translation: "сакам", category: "verb", sentence_de: "Ich liebe dich.", sentence_mk: "Те сакам.", image: "❤️" },
  { word: "mögen", translation: "сакам (ми се допаѓа)", category: "verb", sentence_de: "Ich mag Schokolade.", sentence_mk: "Сакам чоколадо.", image: "🍫" },
  { word: "hassen", translation: "мразам", category: "verb", sentence_de: "Ich hasse Lügen.", sentence_mk: "Мразам лаги.", image: "👿" },
  { word: "brauchen", translation: "треба (ми треба)", category: "verb", sentence_de: "Ich brauche Hilfe.", sentence_mk: "Ми треба помош.", image: "🆘" },
  { word: "nehmen", translation: "земам", category: "verb", sentence_de: "Ich nehme das Buch.", sentence_mk: "Ја земам книгата.", image: "📚" },
  { word: "geben", translation: "давам", category: "verb", sentence_de: "Ich gebe dir Geld.", sentence_mk: "Ти давам пари.", image: "💶" },
  { word: "bringen", translation: "носам", category: "verb", sentence_de: "Ich bringe Kaffee.", sentence_mk: "Носам кафе.", image: "☕" },
  { word: "holen", translation: "донесувам", category: "verb", sentence_de: "Ich hole das Auto.", sentence_mk: "Го донесувам автомобилот.", image: "🚗" },
  { word: "legen", translation: "ставам (хоризонтално)", category: "verb", sentence_de: "Ich lege das Buch auf den Tisch.", sentence_mk: "Ја ставам книгата на масата.", image: "📖" },
  { word: "stellen", translation: "ставам (вертикално)", category: "verb", sentence_de: "Ich stelle die Vase auf den Tisch.", sentence_mk: "Ја ставам вазната на масата.", image: "🏺" },
  { word: "setzen", translation: "седнувам", category: "verb", sentence_de: "Ich setze mich auf den Stuhl.", sentence_mk: "Седнувам на столот.", image: "🪑" },
  { word: "öffnen", translation: "отворам", category: "verb", sentence_de: "Ich öffne das Fenster.", sentence_mk: "Го отворам прозорецот.", image: "🪟" },
  { word: "schließen", translation: "затворам", category: "verb", sentence_de: "Ich schließe die Tür.", sentence_mk: "Ја затворам вратата.", image: "🚪" },
  { word: "machen", translation: "правам", category: "verb", sentence_de: "Ich mache die Hausaufgaben.", sentence_mk: "Ги правам домашните задачи.", image: "📝" },
  { word: "tun", translation: "чинам/правам", category: "verb", sentence_de: "Was tust du?", sentence_mk: "Што правиш?", image: "🤷" },
  { word: "können", translation: "можам", category: "verb", sentence_de: "Ich kann Deutsch sprechen.", sentence_mk: "Можам да зборувам германски.", image: "💪" },
  { word: "müssen", translation: "морам", category: "verb", sentence_de: "Ich muss lernen.", sentence_mk: "Морам да учам.", image: "📚" },
  { word: "dürfen", translation: "смеам", category: "verb", sentence_de: "Ich darf ins Kino gehen.", sentence_mk: "Смеам да одам во кино.", image: "🎬" },
  { word: "sollen", translation: "треба (препорака)", category: "verb", sentence_de: "Ich soll zum Arzt gehen.", sentence_mk: "Треба да одам на доктор.", image: "👨‍⚕️" },
  { word: "wollen", translation: "сакам (имам намера)", category: "verb", sentence_de: "Ich will Deutsch lernen.", sentence_mk: "Сакам да учам германски.", image: "🎯" },
  { word: "wissen", translation: "знам", category: "verb", sentence_de: "Ich weiß die Antwort.", sentence_mk: "Го знам одговорот.", image: "💡" },

  // ДОМ (HOME)
  { word: "das Haus", translation: "куќата", category: "noun", gender: "das", sentence_de: "Das Haus ist groß.", sentence_mk: "Куќата е голема.", image: "🏠" },
  { word: "die Wohnung", translation: "станот", category: "noun", gender: "die", sentence_de: "Die Wohnung ist klein.", sentence_mk: "Станот е мал.", image: "🏢" },
  { word: "das Zimmer", translation: "собата", category: "noun", gender: "das", sentence_de: "Das Zimmer ist hell.", sentence_mk: "Собата е светла.", image: "🚪" },
  { word: "das Wohnzimmer", translation: "дневната соба", category: "noun", gender: "das", sentence_de: "Das Wohnzimmer ist gemütlich.", sentence_mk: "Дневната соба е пријатна.", image: "🛋️" },
  { word: "das Schlafzimmer", translation: "спалната соба", category: "noun", gender: "das", sentence_de: "Das Schlafzimmer ist ruhig.", sentence_mk: "Спалната соба е тивка.", image: "🛏️" },
  { word: "das Kinderzimmer", translation: "детската соба", category: "noun", gender: "das", sentence_de: "Das Kinderzimmer ist bunt.", sentence_mk: "Детската соба е шарена.", image: "🧸" },
  { word: "die Küche", translation: "кујната", category: "noun", gender: "die", sentence_de: "Die Küche ist modern.", sentence_mk: "Кујната е модерна.", image: "🍳" },
  { word: "das Bad", translation: "бањата", category: "noun", gender: "das", sentence_de: "Das Bad ist sauber.", sentence_mk: "Бањата е чиста.", image: "🛁" },
  { word: "das Badezimmer", translation: "бањата", category: "noun", gender: "das", sentence_de: "Das Badezimmer hat eine Dusche.", sentence_mk: "Бањата има туш.", image: "🚿" },
  { word: "die Toilette", translation: "тоалетот", category: "noun", gender: "die", sentence_de: "Die Toilette ist besetzt.", sentence_mk: "Тоалетот е зафатен.", image: "🚽" },
  { word: "der Flur", translation: "ходникот", category: "noun", gender: "der", sentence_de: "Der Flur ist lang.", sentence_mk: "Ходникот е долг.", image: "🚪" },
  { word: "der Keller", translation: "подрумот", category: "noun", gender: "der", sentence_de: "Im Keller ist es kühl.", sentence_mk: "Во подрумот е ладно.", image: "🥶" },
  { word: "der Balkon", translation: "балконот", category: "noun", gender: "der", sentence_de: "Der Balkon ist klein.", sentence_mk: "Балконот е мал.", image: "🏢" },
  { word: "der Garten", translation: "градината", category: "noun", gender: "der", sentence_de: "Der Garten ist schön.", sentence_mk: "Градината е убава.", image: "🌳" },
  { word: "der Tisch", translation: "масата", category: "noun", gender: "der", sentence_de: "Der Tisch ist aus Holz.", sentence_mk: "Масата е од дрво.", image: "🪑" },
  { word: "der Stuhl", translation: "столот", category: "noun", gender: "der", sentence_de: "Der Stuhl ist bequem.", sentence_mk: "Столот е удобен.", image: "🪑" },
  { word: "das Bett", translation: "креветот", category: "noun", gender: "das", sentence_de: "Das Bett ist weich.", sentence_mk: "Креветот е мек.", image: "🛏️" },
  { word: "der Schrank", translation: "ормарот", category: "noun", gender: "der", sentence_de: "Der Schrank ist voll.", sentence_mk: "Ормарот е полн.", image: "🚪" },
  { word: "das Sofa", translation: "софата", category: "noun", gender: "das", sentence_de: "Das Sofa ist rot.", sentence_mk: "Софата е црвена.", image: "🛋️" },
  { word: "der Sessel", translation: "фотелјата", category: "noun", gender: "der", sentence_de: "Der Sessel ist alt.", sentence_mk: "Фотелјата е стара.", image: "🪑" },
  { word: "der Fernseher", translation: "телевизорот", category: "noun", gender: "der", sentence_de: "Der Fernseher ist kaputt.", sentence_mk: "Телевизорот е расипан.", image: "📺" },
  { word: "der Computer", translation: "компјутерот", category: "noun", gender: "der", sentence_de: "Der Computer ist neu.", sentence_mk: "Компјутерот е нов.", image: "💻" },
  { word: "das Telefon", translation: "телефонот", category: "noun", gender: "das", sentence_de: "Das Telefon klingelt.", sentence_mk: "Телефонот ѕвони.", image: "📞" },
  { word: "das Licht", translation: "светлото", category: "noun", gender: "das", sentence_de: "Das Licht ist an.", sentence_mk: "Светлото е вклучено.", image: "💡" },
  { word: "das Fenster", translation: "прозорецот", category: "noun", gender: "das", sentence_de: "Das Fenster ist offen.", sentence_mk: "Прозорецот е отворен.", image: "🪟" },
  { word: "die Tür", translation: "вратата", category: "noun", gender: "die", sentence_de: "Die Tür ist zu.", sentence_mk: "Вратата е затворена.", image: "🚪" },

  // ГРАД (CITY)
  { word: "die Stadt", translation: "градот", category: "noun", gender: "die", sentence_de: "Die Stadt ist groß.", sentence_mk: "Градот е голем.", image: "🏙️" },
  { word: "das Dorf", translation: "селото", category: "noun", gender: "das", sentence_de: "Das Dorf ist klein.", sentence_mk: "Селото е мало.", image: "🏘️" },
  { word: "die Straße", translation: "улицата", category: "noun", gender: "die", sentence_de: "Die Straße ist lang.", sentence_mk: "Улицата е долга.", image: "🛣️" },
  { word: "der Platz", translation: "плоштадот", category: "noun", gender: "der", sentence_de: "Der Platz ist voll.", sentence_mk: "Плоштадот е полн.", image: "🏛️" },
  { word: "die Brücke", translation: "мостот", category: "noun", gender: "die", sentence_de: "Die Brücke ist alt.", sentence_mk: "Мостот е стар.", image: "🌉" },
  { word: "das Gebäude", translation: "зградата", category: "noun", gender: "das", sentence_de: "Das Gebäude ist hoch.", sentence_mk: "Зградата е висока.", image: "🏢" },
  { word: "der Laden", translation: "продавницата", category: "noun", gender: "der", sentence_de: "Der Laden ist geschlossen.", sentence_mk: "Продавницата е затворена.", image: "🏪" },
  { word: "das Geschäft", translation: "продавницата", category: "noun", gender: "das", sentence_de: "Das Geschäft hat geöffnet.", sentence_mk: "Продавницата е отворена.", image: "🏬" },
  { word: "der Supermarkt", translation: "супермаркетот", category: "noun", gender: "der", sentence_de: "Der Supermarkt ist groß.", sentence_mk: "Супермаркетот е голем.", image: "🛒" },
  { word: "die Bäckerei", translation: "пекарницата", category: "noun", gender: "die", sentence_de: "In der Bäckerei gibt es Brot.", sentence_mk: "Во пекарницата има леб.", image: "🥖" },
  { word: "die Metzgerei", translation: "месарницата", category: "noun", gender: "die", sentence_de: "Die Metzgerei hat Wurst.", sentence_mk: "Месарницата има колбаси.", image: "🥩" },
  { word: "die Apotheke", translation: "аптеката", category: "noun", gender: "die", sentence_de: "In der Apotheke gibt es Medizin.", sentence_mk: "Во аптеката има лекови.", image: "💊" },
  { word: "die Bank", translation: "банката", category: "noun", gender: "die", sentence_de: "Die Bank ist am Markt.", sentence_mk: "Банката е на пазарот.", image: "🏦" },
  { word: "die Post", translation: "поштата", category: "noun", gender: "die", sentence_de: "Die Post ist geschlossen.", sentence_mk: "Поштата е затворена.", image: "📮" },
  { word: "die Schule", translation: "училиштето", category: "noun", gender: "die", sentence_de: "Die Schule beginnt um 8 Uhr.", sentence_mk: "Училиштето започнува во 8 часот.", image: "🏫" },
  { word: "der Kindergarten", translation: "градинката", category: "noun", gender: "der", sentence_de: "Der Kindergarten ist nah.", sentence_mk: "Градинката е близу.", image: "🧸" },
  { word: "die Universität", translation: "универзитетот", category: "noun", gender: "die", sentence_de: "Die Universität ist alt.", sentence_mk: "Универзитетот е стар.", image: "🏛️" },
  { word: "die Kirche", translation: "црквата", category: "noun", gender: "die", sentence_de: "Die Kirche ist groß.", sentence_mk: "Црквата е голема.", image: "⛪" },
  { word: "das Krankenhaus", translation: "болницата", category: "noun", gender: "das", sentence_de: "Das Krankenhaus ist modern.", sentence_mk: "Болницата е модерна.", image: "🏥" },
  { word: "der Bahnhof", translation: "железничката станица", category: "noun", gender: "der", sentence_de: "Der Bahnhof ist zentral.", sentence_mk: "Железничката станица е централна.", image: "🚉" },
  { word: "der Flughafen", translation: "аеродромот", category: "noun", gender: "der", sentence_de: "Der Flughafen ist groß.", sentence_mk: "Аеродромот е голем.", image: "✈️" },
  { word: "die Bushaltestelle", translation: "автобуската постојка", category: "noun", gender: "die", sentence_de: "Die Bushaltestelle ist hier.", sentence_mk: "Автобуската постојка е тука.", image: "🚏" },
  { word: "das Kino", translation: "киното", category: "noun", gender: "das", sentence_de: "Im Kino läuft ein guter Film.", sentence_mk: "Во киното се прикажува добар филм.", image: "🎬" },
  { word: "das Theater", translation: "театарот", category: "noun", gender: "das", sentence_de: "Das Theater ist alt.", sentence_mk: "Театарот е стар.", image: "🎭" },
  { word: "das Museum", translation: "музејот", category: "noun", gender: "das", sentence_de: "Im Museum gibt es Kunst.", sentence_mk: "Во музејот има уметност.", image: "🏛️" },
  { word: "der Park", translation: "паркот", category: "noun", gender: "der", sentence_de: "Der Park ist schön.", sentence_mk: "Паркот е убав.", image: "🌳" },
  { word: "das Restaurant", translation: "ресторанот", category: "noun", gender: "das", sentence_de: "Das Restaurant ist gut.", sentence_mk: "Ресторанот е добар.", image: "🍽️" },
  { word: "das Café", translation: "кафето", category: "noun", gender: "das", sentence_de: "Im Café gibt es Kuchen.", sentence_mk: "Во кафето има колачи.", image: "☕" },

  // ПАТУВАЊЕ (TRAVEL)
  { word: "das Auto", translation: "автомобилот", category: "noun", gender: "das", sentence_de: "Das Auto ist rot.", sentence_mk: "Автомобилот е црвен.", image: "🚗" },
  { word: "der Bus", translation: "автобусот", category: "noun", gender: "der", sentence_de: "Der Bus kommt um 10 Uhr.", sentence_mk: "Автобусот доаѓа во 10 часот.", image: "🚌" },
  { word: "die Straßenbahn", translation: "трамвајот", category: "noun", gender: "die", sentence_de: "Die Straßenbahn fährt durch die Stadt.", sentence_mk: "Трамвајот вози низ градот.", image: "🚊" },
  { word: "die U-Bahn", translation: "метрото", category: "noun", gender: "die", sentence_de: "Die U-Bahn ist schnell.", sentence_mk: "Метрото е брзо.", image: "🚇" },
  { word: "der Zug", translation: "возот", category: "noun", gender: "der", sentence_de: "Der Zug hat Verspätung.", sentence_mk: "Возот доцни.", image: "🚂" },
  { word: "das Fahrrad", translation: "велосипедот", category: "noun", gender: "das", sentence_de: "Das Fahrrad ist neu.", sentence_mk: "Велосипедот е нов.", image: "🚲" },
  { word: "das Motorrad", translation: "мотоциклот", category: "noun", gender: "das", sentence_de: "Das Motorrad ist laut.", sentence_mk: "Мотоциклот е гласен.", image: "🏍️" },
  { word: "das Taxi", translation: "таксито", category: "noun", gender: "das", sentence_de: "Das Taxi wartet.", sentence_mk: "Таксито чека.", image: "🚕" },
  { word: "das Flugzeug", translation: "авионот", category: "noun", gender: "das", sentence_de: "Das Flugzeug fliegt nach Berlin.", sentence_mk: "Авионот лета за Берлин.", image: "✈️" },
  { word: "das Schiff", translation: "бродот", category: "noun", gender: "das", sentence_de: "Das Schiff fährt auf dem Meer.", sentence_mk: "Бродот плови по море.", image: "🚢" },
  { word: "die Fahrkarte", translation: "билетот", category: "noun", gender: "die", sentence_de: "Die Fahrkarte kostet 10 Euro.", sentence_mk: "Билетот чини 10 евра.", image: "🎫" },
  { word: "der Reisepass", translation: "пасошот", category: "noun", gender: "der", sentence_de: "Der Reisepass ist gültig.", sentence_mk: "Пасошот е важечки.", image: "🛂" },
  { word: "das Gepäck", translation: "багажот", category: "noun", gender: "das", sentence_de: "Das Gepäck ist schwer.", sentence_mk: "Багажот е тежок.", image: "🧳" },
  { word: "der Koffer", translation: "куферот", category: "noun", gender: "der", sentence_de: "Der Koffer ist voll.", sentence_mk: "Куферот е полн.", image: "🧳" },
  { word: "die Reise", translation: "патувањето", category: "noun", gender: "die", sentence_de: "Die Reise war schön.", sentence_mk: "Патувањето беше убаво.", image: "✈️" },
  { word: "der Urlaub", translation: "одморот", category: "noun", gender: "der", sentence_de: "Der Urlaub ist im Sommer.", sentence_mk: "Одморот е во лето.", image: "🏖️" },

  // ПРИРОДА (NATURE)
  { word: "die Natur", translation: "природата", category: "noun", gender: "die", sentence_de: "Die Natur ist schön.", sentence_mk: "Природата е убава.", image: "🌳" },
  { word: "die Pflanze", translation: "растението", category: "noun", gender: "die", sentence_de: "Die Pflanze ist grün.", sentence_mk: "Растението е зелено.", image: "🌿" },
  { word: "der Baum", translation: "дрвото", category: "noun", gender: "der", sentence_de: "Der Baum ist groß.", sentence_mk: "Дрвото е големо.", image: "🌳" },
  { word: "die Blume", translation: "цветот", category: "noun", gender: "die", sentence_de: "Die Blume ist rot.", sentence_mk: "Цветот е црвен.", image: "🌹" },
  { word: "das Gras", translation: "тревата", category: "noun", gender: "das", sentence_de: "Das Gras ist grün.", sentence_mk: "Тревата е зелена.", image: "🌱" },
  { word: "der Wald", translation: "шумата", category: "noun", gender: "der", sentence_de: "Der Wald ist dunkel.", sentence_mk: "Шумата е темна.", image: "🌲" },
  { word: "das Feld", translation: "полето", category: "noun", gender: "das", sentence_de: "Das Feld ist groß.", sentence_mk: "Полето е големо.", image: "🌾" },
  { word: "der Berg", translation: "планината", category: "noun", gender: "der", sentence_de: "Der Berg ist hoch.", sentence_mk: "Планината е висока.", image: "⛰️" },
  { word: "das Meer", translation: "морето", category: "noun", gender: "das", sentence_de: "Das Meer ist blau.", sentence_mk: "Морето е сино.", image: "🌊" },
  { word: "der See", translation: "езерото", category: "noun", gender: "der", sentence_de: "Der See ist sauber.", sentence_mk: "Езерото е чисто.", image: "🏞️" },
  { word: "der Fluss", translation: "реката", category: "noun", gender: "der", sentence_de: "Der Fluss ist lang.", sentence_mk: "Реката е долга.", image: "🏞️" },
  { word: "die Sonne", translation: "сонцето", category: "noun", gender: "die", sentence_de: "Die Sonne scheint.", sentence_mk: "Сонцето сјае.", image: "☀️" },
  { word: "der Mond", translation: "месечината", category: "noun", gender: "der", sentence_de: "Der Mond ist rund.", sentence_mk: "Месечината е тркалезна.", image: "🌕" },
  { word: "der Stern", translation: "ѕвездата", category: "noun", gender: "der", sentence_de: "Die Sterne leuchten.", sentence_mk: "Ѕвездите светат.", image: "⭐" },
  { word: "der Himmel", translation: "небото", category: "noun", gender: "der", sentence_de: "Der Himmel ist blau.", sentence_mk: "Небото е сино.", image: "☁️" },
  { word: "die Wolke", translation: "облакот", category: "noun", gender: "die", sentence_de: "Die Wolke ist weiß.", sentence_mk: "Облакот е бел.", image: "☁️" },
  { word: "der Regen", translation: "дождот", category: "noun", gender: "der", sentence_de: "Der Regen ist nass.", sentence_mk: "Дождот е влажен.", image: "🌧️" },
  { word: "der Schnee", translation: "снегот", category: "noun", gender: "der", sentence_de: "Der Schnee ist weiß.", sentence_mk: "Снегот е бел.", image: "❄️" },
  { word: "der Wind", translation: "ветерот", category: "noun", gender: "der", sentence_de: "Der Wind ist stark.", sentence_mk: "Ветерот е силен.", image: "💨" },

  // ПРИДАВКИ (ADJECTIVES)
  { word: "gut", translation: "добар", category: "adjective", sentence_de: "Das Essen ist gut.", sentence_mk: "Храната е добра.", image: "👍" },
  { word: "schlecht", translation: "лош", category: "adjective", sentence_de: "Das Wetter ist schlecht.", sentence_mk: "Времето е лошо.", image: "👎" },
  { word: "groß", translation: "голем", category: "adjective", sentence_de: "Das Haus ist groß.", sentence_mk: "Куќата е голема.", image: "🏠" },
  { word: "klein", translation: "мал", category: "adjective", sentence_de: "Das Kind ist klein.", sentence_mk: "Детето е мало.", image: "👶" },
  { word: "lang", translation: "долг", category: "adjective", sentence_de: "Die Straße ist lang.", sentence_mk: "Улицата е долга.", image: "🛣️" },
  { word: "kurz", translation: "краток", category: "adjective", sentence_de: "Der Film ist kurz.", sentence_mk: "Филмот е краток.", image: "🎬" },
  { word: "hoch", translation: "висок", category: "adjective", sentence_de: "Der Berg ist hoch.", sentence_mk: "Планината е висока.", image: "⛰️" },
  { word: "niedrig", translation: "низок", category: "adjective", sentence_de: "Der Tisch ist niedrig.", sentence_mk: "Масата е ниска.", image: "🪑" },
  { word: "alt", translation: "стар", category: "adjective", sentence_de: "Der Mann ist alt.", sentence_mk: "Човекот е стар.", image: "👴" },
  { word: "neu", translation: "нов", category: "adjective", sentence_de: "Das Auto ist neu.", sentence_mk: "Автомобилот е нов.", image: "🚗" },
  { word: "jung", translation: "млад", category: "adjective", sentence_de: "Die Frau ist jung.", sentence_mk: "Жената е млада.", image: "👩" },
  { word: "heiß", translation: "топол", category: "adjective", sentence_de: "Der Kaffee ist heiß.", sentence_mk: "Кафето е топло.", image: "☕" },
  { word: "kalt", translation: "студен", category: "adjective", sentence_de: "Das Wasser ist kalt.", sentence_mk: "Водата е ладна.", image: "❄️" },
  { word: "warm", translation: "топол (пријатно)", category: "adjective", sentence_de: "Die Sonne ist warm.", sentence_mk: "Сонцето е топло.", image: "☀️" },
  { word: "süß", translation: "сладок", category: "adjective", sentence_de: "Der Kuchen ist süß.", sentence_mk: "Колачот е сладок.", image: "🍰" },
  { word: "sauer", translation: "кисел", category: "adjective", sentence_de: "Die Zitrone ist sauer.", sentence_mk: "Лимонот е кисел.", image: "🍋" },
  { word: "bitter", translation: "горчлив", category: "adjective", sentence_de: "Die Medizin ist bitter.", sentence_mk: "Лекот е горчлив.", image: "💊" },
  { word: "salzig", translation: "солен", category: "adjective", sentence_de: "Die Suppe ist salzig.", sentence_mk: "Супата е солена.", image: "🧂" },
  { word: "teuer", translation: "скап", category: "adjective", sentence_de: "Das Auto ist teuer.", sentence_mk: "Автомобилот е скап.", image: "💰" },
  { word: "billig", translation: "евтин", category: "adjective", sentence_de: "Das Hemd ist billig.", sentence_mk: "Кошулата е евтина.", image: "🏷️" },
  { word: "reich", translation: "богат", category: "adjective", sentence_de: "Der Mann ist reich.", sentence_mk: "Човекот е богат.", image: "🤑" },
  { word: "arm", translation: "сиромашен", category: "adjective", sentence_de: "Die Familie ist arm.", sentence_mk: "Семејството е сиромашно.", image: "😔" },
  { word: "glücklich", translation: "среќен", category: "adjective", sentence_de: "Ich bin glücklich.", sentence_mk: "Среќен сум.", image: "😊" },
  { word: "traurig", translation: "тажен", category: "adjective", sentence_de: "Der Film ist traurig.", sentence_mk: "Филмот е тажен.", image: "😢" },
  { word: "müde", translation: "уморен", category: "adjective", sentence_de: "Ich bin müde.", sentence_mk: "Уморен сум.", image: "🥱" },
  { word: "krank", translation: "болен", category: "adjective", sentence_de: "Er ist krank.", sentence_mk: "Тој е болен.", image: "🤒" },
  { word: "gesund", translation: "здрав", category: "adjective", sentence_de: "Sie ist gesund.", sentence_mk: "Таа е здрава.", image: "💪" },
  { word: "sauber", translation: "чист", category: "adjective", sentence_de: "Das Zimmer ist sauber.", sentence_mk: "Собата е чиста.", image: "🧹" },
  { word: "schmutzig", translation: "валкан", category: "adjective", sentence_de: "Die Hose ist schmutzig.", sentence_mk: "Панталоните се валкани.", image: "💩" },
  { word: "schön", translation: "убав", category: "adjective", sentence_de: "Die Blume ist schön.", sentence_mk: "Цветот е убав.", image: "🌸" },
  { word: "hässlich", translation: "грд", category: "adjective", sentence_de: "Das Bild ist hässlich.", sentence_mk: "Сликата е грда.", image: "👹" },
  { word: "interessant", translation: "интересен", category: "adjective", sentence_de: "Das Buch ist interessant.", sentence_mk: "Книгата е интересна.", image: "📚" },
  { word: "langweilig", translation: "досаден", category: "adjective", sentence_de: "Der Film ist langweilig.", sentence_mk: "Филмот е досаден.", image: "😴" },
  { word: "laut", translation: "гласен", category: "adjective", sentence_de: "Die Musik ist laut.", sentence_mk: "Музиката е гласна.", image: "🔊" },
  { word: "leise", translation: "тивок", category: "adjective", sentence_de: "Das Kind ist leise.", sentence_mk: "Детето е тивко.", image: "🤫" },
  { word: "schnell", translation: "брз", category: "adjective", sentence_de: "Das Auto ist schnell.", sentence_mk: "Автомобилот е брз.", image: "🚗💨" },
  { word: "langsam", translation: "бавен", category: "adjective", sentence_de: "Der Bus ist langsam.", sentence_mk: "Автобусот е бавен.", image: "🐢" },
  { word: "früh", translation: "ран", category: "adjective", sentence_de: "Der Morgen ist früh.", sentence_mk: "Утрото е рано.", image: "🌅" },
  { word: "spät", translation: "доцен", category: "adjective", sentence_de: "Der Abend ist spät.", sentence_mk: "Вечерта е доцна.", image: "🌃" },

  // ПРЕДЛОЗИ (PREPOSITIONS)
  { word: "in", translation: "во", category: "other", sentence_de: "Ich bin in Berlin.", sentence_mk: "Јас сум во Берлин.", image: "🏙️" },
  { word: "auf", translation: "на", category: "other", sentence_de: "Das Buch ist auf dem Tisch.", sentence_mk: "Книгата е на масата.", image: "📖" },
  { word: "unter", translation: "под", category: "other", sentence_de: "Der Hund ist unter dem Tisch.", sentence_mk: "Кучето е под масата.", image: "🐕" },
  { word: "über", translation: "над", category: "other", sentence_de: "Das Bild hängt über dem Tisch.", sentence_mk: "Сликата виси над масата.", image: "🖼️" },
  { word: "neben", translation: "до", category: "other", sentence_de: "Die Bank ist neben dem Supermarkt.", sentence_mk: "Банката е до супермаркетот.", image: "🏦" },
  { word: "zwischen", translation: "помеѓу", category: "other", sentence_de: "Das Kino ist zwischen der Bank und der Post.", sentence_mk: "Киното е помеѓу банката и поштата.", image: "🎬" },
  { word: "vor", translation: "пред", category: "other", sentence_de: "Ich stehe vor dem Haus.", sentence_mk: "Стојам пред куќата.", image: "🏠" },
  { word: "hinter", translation: "зад", category: "other", sentence_de: "Der Garten ist hinter dem Haus.", sentence_mk: "Градината е зад куќата.", image: "🌳" },
  { word: "an", translation: "на (вертикално)", category: "other", sentence_de: "Das Bild ist an der Wand.", sentence_mk: "Сликата е на ѕидот.", image: "🖼️" },
  { word: "bei", translation: "кај", category: "other", sentence_de: "Ich bin beim Arzt.", sentence_mk: "Јас сум кај доктор.", image: "👨‍⚕️" },
  { word: "mit", translation: "со", category: "other", sentence_de: "Ich fahre mit dem Bus.", sentence_mk: "Се возам со автобус.", image: "🚌" },
  { word: "ohne", translation: "без", category: "other", sentence_de: "Ich trinke Kaffee ohne Milch.", sentence_mk: "Пијам кафе без млеко.", image: "☕" },
  { word: "für", translation: "за", category: "other", sentence_de: "Das Geschenk ist für dich.", sentence_mk: "Подарокот е за тебе.", image: "🎁" },
  { word: "gegen", translation: "против", category: "other", sentence_de: "Ich bin gegen Krieg.", sentence_mk: "Јас сум против војна.", image: "🕊️" },
  { word: "um", translation: "околу", category: "other", sentence_de: "Wir treffen uns um 8 Uhr.", sentence_mk: "Се среќаваме околу 8 часот.", image: "⏰" },
  { word: "durch", translation: "низ", category: "other", sentence_de: "Wir gehen durch den Park.", sentence_mk: "Одиме низ паркот.", image: "🌳" },
  { word: "für", translation: "за", category: "other", sentence_de: "Das ist für dich.", sentence_mk: "Ова е за тебе.", image: "🎁" },
  { word: "bis", translation: "до", category: "other", sentence_de: "Bis morgen!", sentence_mk: "До утре!", image: "👋" },
  { word: "seit", translation: "од (време)", category: "other", sentence_de: "Ich lerne seit einem Jahr Deutsch.", sentence_mk: "Учам германски од една година.", image: "📅" },
  { word: "aus", translation: "од (потекло)", category: "other", sentence_de: "Ich komme aus Berlin.", sentence_mk: "Доаѓам од Берлин.", image: "🇩🇪" },

  // ВЕЗНИЦИ (CONJUNCTIONS)
  { word: "und", translation: "и", category: "other", sentence_de: "Ich lerne Deutsch und Englisch.", sentence_mk: "Учам германски и англиски.", image: "➕" },
  { word: "oder", translation: "или", category: "other", sentence_de: "Möchtest du Tee oder Kaffee?", sentence_mk: "Сакаш чај или кафе?", image: "☕" },
  { word: "aber", translation: "но", category: "other", sentence_de: "Ich bin müde, aber ich lerne.", sentence_mk: "Уморен сум, но учам.", image: "😴" },
  { word: "denn", translation: "бидејќи", category: "other", sentence_de: "Ich gehe nicht aus, denn es regnet.", sentence_mk: "Не излегувам, бидејќи врне дожд.", image: "🌧️" },
  { word: "weil", translation: "затоа што", category: "other", sentence_de: "Ich lerne Deutsch, weil ich in Berlin wohne.", sentence_mk: "Учам германски, затоа што живеам во Берлин.", image: "🏙️" },
  { word: "dass", translation: "дека", category: "other", sentence_de: "Ich weiß, dass du kommst.", sentence_mk: "Знам дека доаѓаш.", image: "💭" },
  { word: "wenn", translation: "ако / кога", category: "other", sentence_de: "Wenn es regnet, bleibe ich zu Hause.", sentence_mk: "Ако врне дожд, останувам дома.", image: "🏠" },
  { word: "als", translation: "кога (минато)", category: "other", sentence_de: "Als ich Kind war, spielte ich Fußball.", sentence_mk: "Кога бев дете, играв фудбал.", image: "⚽" },

  // ПРИЛОЗИ (ADVERBS)
  { word: "hier", translation: "тука", category: "other", sentence_de: "Ich bin hier.", sentence_mk: "Тука сум.", image: "📍" },
  { word: "da", translation: "таму", category: "other", sentence_de: "Das Buch ist da.", sentence_mk: "Книгата е таму.", image: "📖" },
  { word: "dort", translation: "таму (подалеку)", category: "other", sentence_de: "Dort drüben ist der Bahnhof.", sentence_mk: "Таму настрана е железничката станица.", image: "🚉" },
  { word: "links", translation: "лево", category: "other", sentence_de: "Die Bank ist links.", sentence_mk: "Банката е лево.", image: "⬅️" },
  { word: "rechts", translation: "десно", category: "other", sentence_de: "Das Kino ist rechts.", sentence_mk: "Киното е десно.", image: "➡️" },
  { word: "geradeaus", translation: "право", category: "other", sentence_de: "Gehen Sie geradeaus.", sentence_mk: "Одете право.", image: "⬆️" },
  { word: "viel", translation: "многу", category: "other", sentence_de: "Ich habe viel Arbeit.", sentence_mk: "Имам многу работа.", image: "💼" },
  { word: "wenig", translation: "малку", category: "other", sentence_de: "Ich habe wenig Zeit.", sentence_mk: "Имам малку време.", image: "⏰" },
  { word: "oft", translation: "често", category: "other", sentence_de: "Ich gehe oft ins Kino.", sentence_mk: "Одам често во кино.", image: "🎬" },
  { word: "selten", translation: "ретко", category: "other", sentence_de: "Ich esse selten Fleisch.", sentence_mk: "Јадам ретко месо.", image: "🥩" },
  { word: "immer", translation: "секогаш", category: "other", sentence_de: "Ich lerne immer am Abend.", sentence_mk: "Учам секогаш навечер.", image: "🌆" },
  { word: "nie", translation: "никогаш", category: "other", sentence_de: "Ich trinke nie Alkohol.", sentence_mk: "Никогаш не пијам алкохол.", image: "🚫" },
  { word: "auch", translation: "исто така", category: "other", sentence_de: "Ich lerne auch Spanisch.", sentence_mk: "Учам исто така шпански.", image: "🇪🇸" },
  { word: "nur", translation: "само", category: "other", sentence_de: "Ich habe nur 10 Euro.", sentence_mk: "Имам само 10 евра.", image: "💰" },
  { word: "schon", translation: "веќе", category: "other", sentence_de: "Ich bin schon fertig.", sentence_mk: "Веќе сум готов.", image: "✅" },
  { word: "noch", translation: "уште", category: "other", sentence_de: "Ich lerne noch Deutsch.", sentence_mk: "Учам уште германски.", image: "📚" },
  { word: "vielleicht", translation: "можеби", category: "other", sentence_de: "Vielleicht komme ich morgen.", sentence_mk: "Можеби ќе дојдам утре.", image: "🤔" },
  { word: "vorn", translation: "напред", category: "other", sentence_de: "Ich sitze vorn.", sentence_mk: "Седам напред.", image: "⬆️" },
  { word: "hinten", translation: "позади", category: "other", sentence_de: "Der Eingang ist hinten.", sentence_mk: "Влезот е позади.", image: "⬇️" },
  { word: "oben", translation: "горе", category: "other", sentence_de: "Die Wohnung ist oben.", sentence_mk: "Станот е горе.", image: "⬆️" },
  { word: "unten", translation: "долу", category: "other", sentence_de: "Der Keller ist unten.", sentence_mk: "Подрумот е долу.", image: "⬇️" },
  { word: "draußen", translation: "надвор", category: "other", sentence_de: "Es ist kalt draußen.", sentence_mk: "Надвор е ладно.", image: "❄️" },
  { word: "drinnen", translation: "внатре", category: "other", sentence_de: "Es ist warm drinnen.", sentence_mk: "Внатре е топло.", image: "🏠" },
  { word: "zusammen", translation: "заедно", category: "other", sentence_de: "Wir lernen zusammen.", sentence_mk: "Учиме заедно.", image: "👥" },
  { word: "allein", translation: "сам", category: "other", sentence_de: "Ich bin allein.", sentence_mk: "Сам сум.", image: "👤" }
];