import { ImportData } from './types';

export const A2_VOCABULARY: ImportData[] = [

  // ПРОФЕСИИ (PROFESSIONS)
  { word: "der Arzt", translation: "докторот (маж)", category: "noun", gender: "der", sentence_de: "Der Arzt untersucht den Patienten.", sentence_mk: "Докторот го прегледува пациентот.", image: "👨‍⚕️" },
  { word: "die Ärztin", translation: "докторката (жена)", category: "noun", gender: "die", sentence_de: "Die Ärztin ist sehr nett.", sentence_mk: "Докторката е многу фина.", image: "👩‍⚕️" },
  { word: "der Lehrer", translation: "учителот (маж)", category: "noun", gender: "der", sentence_de: "Der Lehrer erklärt die Aufgabe.", sentence_mk: "Учителот ја објаснува задачата.", image: "👨‍🏫" },
  { word: "die Lehrerin", translation: "учителката (жена)", category: "noun", gender: "die", sentence_de: "Die Lehrerin ist streng.", sentence_mk: "Учителката е строга.", image: "👩‍🏫" },
  { word: "der Ingenieur", translation: "инженерот", category: "noun", gender: "der", sentence_de: "Der Ingenieur baut Brücken.", sentence_mk: "Инженерот гради мостови.", image: "👷" },
  { word: "der Architekt", translation: "архитектот", category: "noun", gender: "der", sentence_de: "Der Architekt plant das Haus.", sentence_mk: "Архитектот ја планира куќата.", image: "🏗️" },
  { word: "der Anwalt", translation: "адвокатот", category: "noun", gender: "der", sentence_de: "Der Anwalt verteidigt seinen Klienten.", sentence_mk: "Адвокатот го брани својот клиент.", image: "⚖️" },
  { word: "der Koch", translation: "готвачот (маж)", category: "noun", gender: "der", sentence_de: "Der Koch kocht ausgezeichnet.", sentence_mk: "Готвачот готви одлично.", image: "👨‍🍳" },
  { word: "die Köchin", translation: "готвачката (жена)", category: "noun", gender: "die", sentence_de: "Die Köchin macht eine Suppe.", sentence_mk: "Готвачката прави супа.", image: "👩‍🍳" },
  { word: "der Polizist", translation: "полицаецот", category: "noun", gender: "der", sentence_de: "Der Polizist regelt den Verkehr.", sentence_mk: "Полицаецот го регулира сообраќајот.", image: "👮" },
  { word: "der Feuerwehrmann", translation: "пожарникарот", category: "noun", gender: "der", sentence_de: "Der Feuerwehrmann löscht den Brand.", sentence_mk: "Пожарникарот го гаси пожарот.", image: "🧑‍🚒" },
  { word: "der Fahrer", translation: "возачот", category: "noun", gender: "der", sentence_de: "Der Fahrer kennt die Stadt gut.", sentence_mk: "Возачот добро го познава градот.", image: "🚗" },
  { word: "der Verkäufer", translation: "продавачот (маж)", category: "noun", gender: "der", sentence_de: "Der Verkäufer hilft dem Kunden.", sentence_mk: "Продавачот му помага на купувачот.", image: "🧑‍💼" },
  { word: "die Verkäuferin", translation: "продавачката (жена)", category: "noun", gender: "die", sentence_de: "Die Verkäuferin ist freundlich.", sentence_mk: "Продавачката е пријатна.", image: "👩‍💼" },
  { word: "der Kellner", translation: "конобарот (маж)", category: "noun", gender: "der", sentence_de: "Der Kellner bringt die Speisekarte.", sentence_mk: "Конобарот го носи менито.", image: "🧑‍🍽️" },
  { word: "die Kellnerin", translation: "конобарката (жена)", category: "noun", gender: "die", sentence_de: "Die Kellnerin nimmt die Bestellung auf.", sentence_mk: "Конобарката ја зема нарачката.", image: "👩‍🍽️" },
  { word: "der Bäcker", translation: "пекарот", category: "noun", gender: "der", sentence_de: "Der Bäcker backt frisches Brot.", sentence_mk: "Пекарот пече свеж леб.", image: "🥖" },
  { word: "der Mechaniker", translation: "механичарот", category: "noun", gender: "der", sentence_de: "Der Mechaniker repariert das Auto.", sentence_mk: "Механичарот го поправа автомобилот.", image: "🔧" },
  { word: "der Elektriker", translation: "електричарот", category: "noun", gender: "der", sentence_de: "Der Elektriker repariert die Lampe.", sentence_mk: "Електричарот ја поправа ламбата.", image: "⚡" },
  { word: "der Sekretär", translation: "секретарот (маж)", category: "noun", gender: "der", sentence_de: "Der Sekretär beantwortet die E-Mails.", sentence_mk: "Секретарот одговара на е-маиловите.", image: "💻" },
  { word: "die Sekretärin", translation: "секретарката (жена)", category: "noun", gender: "die", sentence_de: "Die Sekretärin organisiert die Termine.", sentence_mk: "Секретарката ги организира термините.", image: "📅" },
  { word: "der Journalist", translation: "новинарот", category: "noun", gender: "der", sentence_de: "Der Journalist schreibt einen Artikel.", sentence_mk: "Новинарот пишува статија.", image: "📰" },
  { word: "der Fotograf", translation: "фотографот", category: "noun", gender: "der", sentence_de: "Der Fotograf macht Fotos.", sentence_mk: "Фотографот прави фотографии.", image: "📷" },
  { word: "der Musiker", translation: "музичарот", category: "noun", gender: "der", sentence_de: "Der Musiker spielt Gitarre.", sentence_mk: "Музичарот свири гитара.", image: "🎸" },
  { word: "der Schauspieler", translation: "актерот (маж)", category: "noun", gender: "der", sentence_de: "Der Schauspieler spielt im Theater.", sentence_mk: "Актерот игра во театар.", image: "🎭" },
  { word: "die Schauspielerin", translation: "актерката (жена)", category: "noun", gender: "die", sentence_de: "Die Schauspielerin ist berühmt.", sentence_mk: "Актерката е позната.", image: "🌟" },
  { word: "der Sportler", translation: "спортистот", category: "noun", gender: "der", sentence_de: "Der Sportler trainiert täglich.", sentence_mk: "Спортистот тренира секојдневно.", image: "🏋️" },
  { word: "der Tierarzt", translation: "ветеринарот", category: "noun", gender: "der", sentence_de: "Der Tierarzt behandelt kranke Tiere.", sentence_mk: "Ветеринарот лекува болни животни.", image: "🐾" },
  { word: "der Zahnarzt", translation: "стоматологот", category: "noun", gender: "der", sentence_de: "Der Zahnarzt zieht einen Zahn.", sentence_mk: "Стоматологот вади заб.", image: "🦷" },
  { word: "der Krankenpfleger", translation: "медицинарот (маж)", category: "noun", gender: "der", sentence_de: "Der Krankenpfleger pflegt die Patienten.", sentence_mk: "Медицинарот се грижи за пациентите.", image: "🏥" },
  { word: "die Krankenschwester", translation: "медицинарката (жена)", category: "noun", gender: "die", sentence_de: "Die Krankenschwester gibt Medikamente.", sentence_mk: "Медицинарката дава лекови.", image: "💊" },

  // УЧИЛИШТЕ И ОБРАЗОВАНИЕ (SCHOOL AND EDUCATION)
  { word: "der Schüler", translation: "ученикот (маж)", category: "noun", gender: "der", sentence_de: "Der Schüler lernt fleißig.", sentence_mk: "Ученикот учи марливо.", image: "📚" },
  { word: "die Schülerin", translation: "ученичката (жена)", category: "noun", gender: "die", sentence_de: "Die Schülerin schreibt einen Aufsatz.", sentence_mk: "Ученичката пишува состав.", image: "✍️" },
  { word: "der Student", translation: "студентот (маж)", category: "noun", gender: "der", sentence_de: "Der Student studiert Mathematik.", sentence_mk: "Студентот студира математика.", image: "🎓" },
  { word: "die Studentin", translation: "студентката (жена)", category: "noun", gender: "die", sentence_de: "Die Studentin wohnt im Wohnheim.", sentence_mk: "Студентката живее во студентски дом.", image: "🏠" },
  { word: "die Hausaufgabe", translation: "домашната задача", category: "noun", gender: "die", sentence_de: "Ich mache meine Hausaufgaben.", sentence_mk: "Ги правам домашните задачи.", image: "📝" },
  { word: "die Prüfung", translation: "испитот", category: "noun", gender: "die", sentence_de: "Die Prüfung ist schwer.", sentence_mk: "Испитот е тежок.", image: "📋" },
  { word: "die Note", translation: "оценката", category: "noun", gender: "die", sentence_de: "Ich habe eine gute Note.", sentence_mk: "Имам добра оценка.", image: "⭐" },
  { word: "das Heft", translation: "тетратката", category: "noun", gender: "das", sentence_de: "Das Heft ist voll.", sentence_mk: "Тетратката е полна.", image: "📓" },
  { word: "der Stift", translation: "пенкалото", category: "noun", gender: "der", sentence_de: "Der Stift schreibt schlecht.", sentence_mk: "Пенкалото пишува лошо.", image: "✏️" },
  { word: "das Wörterbuch", translation: "речникот", category: "noun", gender: "das", sentence_de: "Das Wörterbuch ist hilfreich.", sentence_mk: "Речникот е корисен.", image: "📖" },
  { word: "die Tafel", translation: "таблата", category: "noun", gender: "die", sentence_de: "Der Lehrer schreibt an die Tafel.", sentence_mk: "Учителот пишува на таблата.", image: "🪣" },
  { word: "der Unterricht", translation: "наставата", category: "noun", gender: "der", sentence_de: "Der Unterricht beginnt um 8 Uhr.", sentence_mk: "Наставата започнува во 8 часот.", image: "🏫" },
  { word: "die Pause", translation: "паузата", category: "noun", gender: "die", sentence_de: "In der Pause essen wir.", sentence_mk: "За пауза јадеме.", image: "🍎" },
  { word: "das Fach", translation: "предметот", category: "noun", gender: "das", sentence_de: "Mein Lieblingsfach ist Deutsch.", sentence_mk: "Мојот омилен предмет е германски.", image: "📚" },
  { word: "die Mathematik", translation: "математиката", category: "noun", gender: "die", sentence_de: "Mathematik ist schwierig.", sentence_mk: "Математиката е тешка.", image: "🔢" },
  { word: "die Biologie", translation: "биологијата", category: "noun", gender: "die", sentence_de: "In Biologie lernen wir über Tiere.", sentence_mk: "На биологија учиме за животни.", image: "🌿" },
  { word: "die Geschichte", translation: "историјата", category: "noun", gender: "die", sentence_de: "Geschichte ist interessant.", sentence_mk: "Историјата е интересна.", image: "🏛️" },
  { word: "die Geographie", translation: "географија", category: "noun", gender: "die", sentence_de: "In Geographie lernen wir über Länder.", sentence_mk: "На географија учиме за земји.", image: "🌍" },
  { word: "die Physik", translation: "физиката", category: "noun", gender: "die", sentence_de: "Physik ist kompliziert.", sentence_mk: "Физиката е комплицирана.", image: "⚛️" },
  { word: "die Chemie", translation: "хемијата", category: "noun", gender: "die", sentence_de: "Chemie macht Spaß.", sentence_mk: "Хемијата е забавна.", image: "🧪" },
  { word: "die Kunst", translation: "уметноста", category: "noun", gender: "die", sentence_de: "Kunst ist mein Lieblingsfach.", sentence_mk: "Уметноста е мојот омилен предмет.", image: "🎨" },
  { word: "die Musik", translation: "музиката", category: "noun", gender: "die", sentence_de: "Musik macht glücklich.", sentence_mk: "Музиката прави среќа.", image: "🎵" },
  { word: "der Stundenplan", translation: "распоредот на часови", category: "noun", gender: "der", sentence_de: "Der Stundenplan hängt an der Wand.", sentence_mk: "Распоредот виси на ѕидот.", image: "📅" },
  { word: "die Klasse", translation: "класот/одделението", category: "noun", gender: "die", sentence_de: "Die Klasse hat 25 Schüler.", sentence_mk: "Класот има 25 ученици.", image: "🏫" },

  // ЗДРАВЈЕ (HEALTH)
  { word: "die Gesundheit", translation: "здравјето", category: "noun", gender: "die", sentence_de: "Gesundheit ist das Wichtigste.", sentence_mk: "Здравјето е најважно.", image: "💚" },
  { word: "die Krankheit", translation: "болеста", category: "noun", gender: "die", sentence_de: "Die Krankheit dauert eine Woche.", sentence_mk: "Болеста трае една недела.", image: "🤒" },
  { word: "das Medikament", translation: "лекот", category: "noun", gender: "das", sentence_de: "Das Medikament hilft sofort.", sentence_mk: "Лекот помага веднаш.", image: "💊" },
  { word: "die Tablette", translation: "таблетата", category: "noun", gender: "die", sentence_de: "Ich nehme eine Tablette.", sentence_mk: "Земам таблета.", image: "💊" },
  { word: "der Schmerz", translation: "болката", category: "noun", gender: "der", sentence_de: "Der Schmerz ist stark.", sentence_mk: "Болката е силна.", image: "🤕" },
  { word: "das Fieber", translation: "температурата", category: "noun", gender: "das", sentence_de: "Das Kind hat Fieber.", sentence_mk: "Детето има температура.", image: "🌡️" },
  { word: "der Husten", translation: "кашлицата", category: "noun", gender: "der", sentence_de: "Der Husten ist stark.", sentence_mk: "Кашлицата е јака.", image: "😷" },
  { word: "der Schnupfen", translation: "кивавицата", category: "noun", gender: "der", sentence_de: "Ich habe Schnupfen.", sentence_mk: "Имам кивавица.", image: "🤧" },
  { word: "die Erkältung", translation: "настинката", category: "noun", gender: "die", sentence_de: "Ich habe eine Erkältung.", sentence_mk: "Имам настинка.", image: "🤧" },
  { word: "die Grippe", translation: "грипот", category: "noun", gender: "die", sentence_de: "Die Grippe ist ansteckend.", sentence_mk: "Грипот е заразен.", image: "🤒" },
  { word: "der Termin", translation: "термин/закажан час", category: "noun", gender: "der", sentence_de: "Ich habe einen Termin beim Arzt.", sentence_mk: "Имам термин кај доктор.", image: "📅" },
  { word: "das Rezept", translation: "рецептот", category: "noun", gender: "das", sentence_de: "Der Arzt schreibt ein Rezept.", sentence_mk: "Докторот пишува рецепт.", image: "📋" },
  { word: "die Versicherung", translation: "осигурувањето", category: "noun", gender: "die", sentence_de: "Ich habe eine Krankenversicherung.", sentence_mk: "Имам здравствено осигурување.", image: "🏥" },
  { word: "die Operation", translation: "операцијата", category: "noun", gender: "die", sentence_de: "Die Operation war erfolgreich.", sentence_mk: "Операцијата беше успешна.", image: "🔪" },
  { word: "der Verband", translation: "завојот", category: "noun", gender: "der", sentence_de: "Der Arzt legt einen Verband an.", sentence_mk: "Докторот ставя завој.", image: "🩹" },
  { word: "das Pflaster", translation: "лепенката", category: "noun", gender: "das", sentence_de: "Ich brauche ein Pflaster.", sentence_mk: "Ми треба лепенка.", image: "🩹" },

  // БАНКА И ПАРИ (BANK AND MONEY)
  { word: "das Geld", translation: "парите", category: "noun", gender: "das", sentence_de: "Ich habe kein Geld.", sentence_mk: "Немам пари.", image: "💰" },
  { word: "der Euro", translation: "еврото", category: "noun", gender: "der", sentence_de: "Das kostet zehn Euro.", sentence_mk: "Тоа чини десет евра.", image: "💶" },
  { word: "der Cent", translation: "центот", category: "noun", gender: "der", sentence_de: "Das kostet fünfzig Cent.", sentence_mk: "Тоа чини педесет центи.", image: "🪙" },
  { word: "die Münze", translation: "монетата", category: "noun", gender: "die", sentence_de: "Die Münze ist alt.", sentence_mk: "Монетата е стара.", image: "🪙" },
  { word: "der Schein", translation: "банкнотата", category: "noun", gender: "der", sentence_de: "Hast du einen Schein?", sentence_mk: "Имаш ли банкнота?", image: "💵" },
  { word: "die Kreditkarte", translation: "кредитната картичка", category: "noun", gender: "die", sentence_de: "Ich zahle mit Kreditkarte.", sentence_mk: "Плаќам со кредитна картичка.", image: "💳" },
  { word: "das Konto", translation: "сметката", category: "noun", gender: "das", sentence_de: "Ich habe ein Konto bei der Bank.", sentence_mk: "Имам сметка во банка.", image: "🏦" },
  { word: "die Überweisung", translation: "уплатата", category: "noun", gender: "die", sentence_de: "Ich mache eine Überweisung.", sentence_mk: "Правам уплата.", image: "💸" },
  { word: "der Geldautomat", translation: "банкоматот", category: "noun", gender: "der", sentence_de: "Ich hole Geld am Geldautomat.", sentence_mk: "Земам пари на банкомат.", image: "🏧" },
  { word: "der Preis", translation: "цената", category: "noun", gender: "der", sentence_de: "Der Preis ist zu hoch.", sentence_mk: "Цената е премногу висока.", image: "🏷️" },
  { word: "der Rabatt", translation: "попустот", category: "noun", gender: "der", sentence_de: "Es gibt 20% Rabatt.", sentence_mk: "Има 20% попуст.", image: "🏷️" },
  { word: "die Rechnung", translation: "сметката/фактурата", category: "noun", gender: "die", sentence_de: "Die Rechnung ist hoch.", sentence_mk: "Сметката е висока.", image: "🧾" },
  { word: "das Wechselgeld", translation: "кусурот", category: "noun", gender: "das", sentence_de: "Hier ist Ihr Wechselgeld.", sentence_mk: "Еве го вашиот кусур.", image: "🪙" },

  // КУПУВАЊЕ (SHOPPING)
  { word: "das Einkaufszentrum", translation: "трговскиот центар", category: "noun", gender: "das", sentence_de: "Das Einkaufszentrum ist groß.", sentence_mk: "Трговскиот центар е голем.", image: "🏬" },
  { word: "der Markt", translation: "пазарот", category: "noun", gender: "der", sentence_de: "Auf dem Markt gibt es frisches Gemüse.", sentence_mk: "На пазарот има свеж зеленчук.", image: "🛒" },
  { word: "das Angebot", translation: "понудата/акцијата", category: "noun", gender: "das", sentence_de: "Das Angebot ist gut.", sentence_mk: "Понудата е добра.", image: "🏷️" },
  { word: "die Größe", translation: "големината", category: "noun", gender: "die", sentence_de: "Welche Größe haben Sie?", sentence_mk: "Каква големина имате?", image: "📏" },
  { word: "die Kasse", translation: "касата", category: "noun", gender: "die", sentence_de: "Die Kasse ist dort.", sentence_mk: "Касата е таму.", image: "🛒" },
  { word: "der Kassenbon", translation: "сметката (касова лента)", category: "noun", gender: "der", sentence_de: "Behalten Sie den Kassenbon.", sentence_mk: "Задржете ја касовата лента.", image: "🧾" },
  { word: "die Tüte", translation: "кесата", category: "noun", gender: "die", sentence_de: "Ich brauche eine Tüte.", sentence_mk: "Ми треба кеса.", image: "🛍️" },
  { word: "umtauschen", translation: "заменувам (производ)", category: "verb", sentence_de: "Ich möchte das Hemd umtauschen.", sentence_mk: "Сакам да ја заменам кошулата.", image: "🔄" },
  { word: "zurückgeben", translation: "враќам (производ)", category: "verb", sentence_de: "Ich gebe das Buch zurück.", sentence_mk: "Ја враќам книгата.", image: "↩️" },

  // РЕСТОРАН И ЈАДЕЊЕ (RESTAURANT AND FOOD)
  { word: "die Speisekarte", translation: "менито", category: "noun", gender: "die", sentence_de: "Die Speisekarte ist auf Deutsch.", sentence_mk: "Менито е на германски.", image: "📋" },
  { word: "die Bestellung", translation: "нарачката", category: "noun", gender: "die", sentence_de: "Die Bestellung kommt bald.", sentence_mk: "Нарачката доаѓа наскоро.", image: "🍽️" },
  { word: "die Vorspeise", translation: "предјадењето", category: "noun", gender: "die", sentence_de: "Als Vorspeise nehme ich Suppe.", sentence_mk: "Како предјадење земам супа.", image: "🍲" },
  { word: "das Hauptgericht", translation: "главното јадење", category: "noun", gender: "das", sentence_de: "Das Hauptgericht ist Fleisch.", sentence_mk: "Главното јадење е месо.", image: "🍖" },
  { word: "der Nachtisch", translation: "десертот", category: "noun", gender: "der", sentence_de: "Als Nachtisch möchte ich Eis.", sentence_mk: "Како десерт сакам сладолед.", image: "🍨" },
  { word: "das Trinkgeld", translation: "бакшишот", category: "noun", gender: "das", sentence_de: "Ich gebe dem Kellner Trinkgeld.", sentence_mk: "Му давам бакшиш на конобарот.", image: "💶" },
  { word: "der Tisch reservieren", translation: "резервирам маса", category: "verb", sentence_de: "Ich möchte einen Tisch reservieren.", sentence_mk: "Сакам да резервирам маса.", image: "🍽️" },
  { word: "das Gericht", translation: "јадењето", category: "noun", gender: "das", sentence_de: "Das Gericht schmeckt lecker.", sentence_mk: "Јадењето е вкусно.", image: "🍲" },
  { word: "vegetarisch", translation: "вегетаријански", category: "adjective", sentence_de: "Ich esse vegetarisch.", sentence_mk: "Јадам вегетаријански.", image: "🥗" },
  { word: "lecker", translation: "вкусен", category: "adjective", sentence_de: "Das Essen ist sehr lecker.", sentence_mk: "Храната е многу вкусна.", image: "😋" },
  { word: "scharf", translation: "лут (зачинет)", category: "adjective", sentence_de: "Das Essen ist zu scharf.", sentence_mk: "Храната е премногу лута.", image: "🌶️" },
  { word: "frisch", translation: "свеж", category: "adjective", sentence_de: "Das Brot ist frisch.", sentence_mk: "Лебот е свеж.", image: "🥖" },
  { word: "das Öl", translation: "маслото", category: "noun", gender: "das", sentence_de: "Das Öl ist für den Salat.", sentence_mk: "Маслото е за салатата.", image: "🫙" },
  { word: "der Essig", translation: "оцетот", category: "noun", gender: "der", sentence_de: "Essig macht den Salat sauer.", sentence_mk: "Оцетот го прави кисел салатот.", image: "🍶" },
  { word: "das Salz", translation: "солта", category: "noun", gender: "das", sentence_de: "Das Salz fehlt in der Suppe.", sentence_mk: "Солта недостасува во супата.", image: "🧂" },
  { word: "der Pfeffer", translation: "бибeрот", category: "noun", gender: "der", sentence_de: "Ich nehme Pfeffer auf das Essen.", sentence_mk: "Ставам бибер на јадењето.", image: "🌶️" },
  { word: "der Zucker", translation: "шеќерот", category: "noun", gender: "der", sentence_de: "Ich nehme keinen Zucker im Kaffee.", sentence_mk: "Не земам шеќер во кафето.", image: "🍬" },
  { word: "das Mehl", translation: "брашното", category: "noun", gender: "das", sentence_de: "Das Mehl ist für den Kuchen.", sentence_mk: "Брашното е за колачот.", image: "🌾" },

  // ЖИВОТНИ (ANIMALS)
  { word: "das Tier", translation: "животното", category: "noun", gender: "das", sentence_de: "Das Tier ist niedlich.", sentence_mk: "Животното е симпатично.", image: "🐾" },
  { word: "der Hund", translation: "кучето", category: "noun", gender: "der", sentence_de: "Der Hund bellt laut.", sentence_mk: "Кучето лае гласно.", image: "🐕" },
  { word: "die Katze", translation: "мачката", category: "noun", gender: "die", sentence_de: "Die Katze schläft gern.", sentence_mk: "Мачката сака да спие.", image: "🐈" },
  { word: "das Pferd", translation: "коњот", category: "noun", gender: "das", sentence_de: "Das Pferd läuft schnell.", sentence_mk: "Коњот трча брзо.", image: "🐎" },
  { word: "die Kuh", translation: "кравата", category: "noun", gender: "die", sentence_de: "Die Kuh gibt Milch.", sentence_mk: "Кравата дава млеко.", image: "🐄" },
  { word: "das Schwein", translation: "свињата", category: "noun", gender: "das", sentence_de: "Das Schwein ist rosa.", sentence_mk: "Свињата е розова.", image: "🐷" },
  { word: "das Schaf", translation: "овцата", category: "noun", gender: "das", sentence_de: "Das Schaf ist auf der Wiese.", sentence_mk: "Овцата е на ливадата.", image: "🐑" },
  { word: "der Vogel", translation: "птицата", category: "noun", gender: "der", sentence_de: "Der Vogel singt schön.", sentence_mk: "Птицата пее убаво.", image: "🐦" },
  { word: "der Fisch", translation: "рибата", category: "noun", gender: "der", sentence_de: "Der Fisch schwimmt im Wasser.", sentence_mk: "Рибата плива во вода.", image: "🐟" },
  { word: "der Löwe", translation: "лавот", category: "noun", gender: "der", sentence_de: "Der Löwe ist der König der Tiere.", sentence_mk: "Лавот е кралот на животните.", image: "🦁" },
  { word: "der Tiger", translation: "тигарот", category: "noun", gender: "der", sentence_de: "Der Tiger hat Streifen.", sentence_mk: "Тигарот има пруги.", image: "🐯" },
  { word: "der Elefant", translation: "слонот", category: "noun", gender: "der", sentence_de: "Der Elefant ist sehr groß.", sentence_mk: "Слонот е многу голем.", image: "🐘" },
  { word: "der Bär", translation: "мечката", category: "noun", gender: "der", sentence_de: "Der Bär schläft im Winter.", sentence_mk: "Мечката спие во зима.", image: "🐻" },
  { word: "der Affe", translation: "мајмунот", category: "noun", gender: "der", sentence_de: "Der Affe klettert auf den Baum.", sentence_mk: "Мајмунот се качува на дрво.", image: "🐒" },
  { word: "die Schlange", translation: "змијата", category: "noun", gender: "die", sentence_de: "Die Schlange ist giftig.", sentence_mk: "Змијата е отровна.", image: "🐍" },
  { word: "der Hase", translation: "зајакот", category: "noun", gender: "der", sentence_de: "Der Hase läuft schnell.", sentence_mk: "Зајакот трча брзо.", image: "🐇" },
  { word: "die Maus", translation: "глувчето", category: "noun", gender: "die", sentence_de: "Die Maus ist klein.", sentence_mk: "Глувчето е мало.", image: "🐭" },
  { word: "der Vogel", translation: "птицата", category: "noun", gender: "der", sentence_de: "Der Vogel fliegt hoch.", sentence_mk: "Птицата лета високо.", image: "🦅" },

  // СПОРТ И СЛОБОДНО ВРЕМЕ (SPORTS AND FREE TIME)
  { word: "der Sport", translation: "спортот", category: "noun", gender: "der", sentence_de: "Sport ist gesund.", sentence_mk: "Спортот е здрав.", image: "⚽" },
  { word: "das Training", translation: "тренингот", category: "noun", gender: "das", sentence_de: "Das Training beginnt um 18 Uhr.", sentence_mk: "Тренингот започнува во 18 часот.", image: "🏋️" },
  { word: "das Spiel", translation: "играта/натпреварот", category: "noun", gender: "das", sentence_de: "Das Spiel dauert 90 Minuten.", sentence_mk: "Натпреварот трае 90 минути.", image: "⚽" },
  { word: "die Mannschaft", translation: "тимот", category: "noun", gender: "die", sentence_de: "Unsere Mannschaft gewinnt.", sentence_mk: "Нашиот тим победува.", image: "🏆" },
  { word: "der Gewinner", translation: "победникот", category: "noun", gender: "der", sentence_de: "Der Gewinner bekommt eine Medaille.", sentence_mk: "Победникот добива медал.", image: "🥇" },
  { word: "der Verlierer", translation: "губитникот", category: "noun", gender: "der", sentence_de: "Der Verlierer gibt nicht auf.", sentence_mk: "Губитникот не се предава.", image: "😔" },
  { word: "der Fußball", translation: "фудбалот", category: "noun", gender: "der", sentence_de: "Fußball ist mein Lieblingssport.", sentence_mk: "Фудбалот е мојот омилен спорт.", image: "⚽" },
  { word: "das Schwimmen", translation: "пливањето", category: "noun", gender: "das", sentence_de: "Schwimmen ist gesund.", sentence_mk: "Пливањето е здраво.", image: "🏊" },
  { word: "das Tennis", translation: "тенисот", category: "noun", gender: "das", sentence_de: "Tennis spielen macht Spaß.", sentence_mk: "Играњето тенис е забавно.", image: "🎾" },
  { word: "das Basketball", translation: "кошарката", category: "noun", gender: "das", sentence_de: "Basketball ist populär.", sentence_mk: "Кошарката е популарна.", image: "🏀" },
  { word: "das Volleyball", translation: "одбојката", category: "noun", gender: "das", sentence_de: "Volleyball spielen wir am Strand.", sentence_mk: "Одбојка играме на плажа.", image: "🏐" },
  { word: "das Radfahren", translation: "возењето велосипед", category: "noun", gender: "das", sentence_de: "Radfahren macht Spaß.", sentence_mk: "Возењето велосипед е забавно.", image: "🚲" },
  { word: "das Wandern", translation: "планинарењето", category: "noun", gender: "das", sentence_de: "Wandern in den Bergen ist schön.", sentence_mk: "Планинарењето во планините е убаво.", image: "🥾" },
  { word: "das Klettern", translation: "качувањето", category: "noun", gender: "das", sentence_de: "Klettern ist gefährlich.", sentence_mk: "Качувањето е опасно.", image: "🧗" },
  { word: "das Schwimmbad", translation: "базенот", category: "noun", gender: "das", sentence_de: "Das Schwimmbad ist kalt.", sentence_mk: "Базенот е ладен.", image: "🏊" },
  { word: "das Stadion", translation: "стадионот", category: "noun", gender: "das", sentence_de: "Das Stadion ist voll.", sentence_mk: "Стадионот е полн.", image: "🏟️" },
  { word: "die Turnhalle", translation: "салата", category: "noun", gender: "die", sentence_de: "Die Turnhalle ist groß.", sentence_mk: "Салата е голема.", image: "🏋️" },
  { word: "das Hobby", translation: "хобито", category: "noun", gender: "das", sentence_de: "Mein Hobby ist Lesen.", sentence_mk: "Моето хоби е читање.", image: "📚" },
  { word: "die Freizeit", translation: "слободното време", category: "noun", gender: "die", sentence_de: "In der Freizeit spiele ich Gitarre.", sentence_mk: "Во слободното време свирам гитара.", image: "🎸" },
  { word: "trainieren", translation: "тренирам", category: "verb", sentence_de: "Ich trainiere dreimal pro Woche.", sentence_mk: "Тренирам три пати неделно.", image: "🏋️" },
  { word: "gewinnen", translation: "победувам", category: "verb", sentence_de: "Wir gewinnen das Spiel.", sentence_mk: "Ја победуваме играта.", image: "🏆" },
  { word: "verlieren", translation: "губам", category: "verb", sentence_de: "Wir verlieren manchmal.", sentence_mk: "Понекогаш губиме.", image: "😔" },
  { word: "schwimmen", translation: "пливам", category: "verb", sentence_de: "Ich schwimme jeden Morgen.", sentence_mk: "Пливам секое утро.", image: "🏊" },

  // МЕДИИ И ТЕХНОЛОГИЈА (MEDIA AND TECHNOLOGY)
  { word: "das Internet", translation: "интернетот", category: "noun", gender: "das", sentence_de: "Das Internet ist überall.", sentence_mk: "Интернетот е насекаде.", image: "🌐" },
  { word: "die Website", translation: "веб-страницата", category: "noun", gender: "die", sentence_de: "Die Website ist modern.", sentence_mk: "Веб-страницата е модерна.", image: "🌐" },
  { word: "die E-Mail", translation: "е-маилот", category: "noun", gender: "die", sentence_de: "Ich schreibe eine E-Mail.", sentence_mk: "Пишувам е-маил.", image: "📧" },
  { word: "das Handy", translation: "мобилниот телефон", category: "noun", gender: "das", sentence_de: "Mein Handy ist kaputt.", sentence_mk: "Мојот мобилен е расипан.", image: "📱" },
  { word: "der Laptop", translation: "лаптопот", category: "noun", gender: "der", sentence_de: "Ich arbeite am Laptop.", sentence_mk: "Работам на лаптоп.", image: "💻" },
  { word: "die App", translation: "апликацијата", category: "noun", gender: "die", sentence_de: "Die App ist kostenlos.", sentence_mk: "Апликацијата е бесплатна.", image: "📱" },
  { word: "das Foto", translation: "фотографијата", category: "noun", gender: "das", sentence_de: "Das Foto ist schön.", sentence_mk: "Фотографијата е убава.", image: "📸" },
  { word: "das Video", translation: "видеото", category: "noun", gender: "das", sentence_de: "Das Video ist lustig.", sentence_mk: "Видеото е смешно.", image: "🎥" },
  { word: "die Nachricht", translation: "пораката/вестите", category: "noun", gender: "die", sentence_de: "Die Nachricht ist wichtig.", sentence_mk: "Пораката е важна.", image: "💬" },
  { word: "das Radio", translation: "радиото", category: "noun", gender: "das", sentence_de: "Ich höre Radio.", sentence_mk: "Слушам радио.", image: "📻" },
  { word: "die Zeitung", translation: "весникот", category: "noun", gender: "die", sentence_de: "Die Zeitung ist von heute.", sentence_mk: "Весникот е од денес.", image: "📰" },
  { word: "die Zeitschrift", translation: "списанието", category: "noun", gender: "die", sentence_de: "Die Zeitschrift ist bunt.", sentence_mk: "Списанието е шарено.", image: "📰" },
  { word: "herunterladen", translation: "преземам (датотека)", category: "verb", sentence_de: "Ich lade das Programm herunter.", sentence_mk: "Ја преземам програмата.", image: "⬇️" },
  { word: "hochladen", translation: "прикачувам", category: "verb", sentence_de: "Ich lade ein Foto hoch.", sentence_mk: "Прикачувам фотографија.", image: "⬆️" },
  { word: "suchen", translation: "барам", category: "verb", sentence_de: "Ich suche eine Information.", sentence_mk: "Барам информација.", image: "🔍" },
  { word: "drucken", translation: "печатам", category: "verb", sentence_de: "Ich drucke das Dokument.", sentence_mk: "Го печатам документот.", image: "🖨️" },
  { word: "speichern", translation: "зачувувам", category: "verb", sentence_de: "Ich speichere die Datei.", sentence_mk: "Ја зачувувам датотеката.", image: "💾" },

  // ОПИШУВАЊЕ НА КАРАКТЕР (DESCRIBING CHARACTER)
  { word: "freundlich", translation: "пријатен", category: "adjective", sentence_de: "Er ist sehr freundlich.", sentence_mk: "Тој е многу пријатен.", image: "😊" },
  { word: "nett", translation: "мил/убав", category: "adjective", sentence_de: "Die Lehrerin ist nett.", sentence_mk: "Учителката е мила.", image: "😊" },
  { word: "höflich", translation: "учтив", category: "adjective", sentence_de: "Das Kind ist höflich.", sentence_mk: "Детето е учтиво.", image: "🙏" },
  { word: "unhöflich", translation: "неучтив", category: "adjective", sentence_de: "Er ist unhöflich.", sentence_mk: "Тој е неучтив.", image: "😤" },
  { word: "fleißig", translation: "марлив", category: "adjective", sentence_de: "Sie ist sehr fleißig.", sentence_mk: "Таа е многу марлива.", image: "💪" },
  { word: "faul", translation: "мрзлив", category: "adjective", sentence_de: "Er ist zu faul.", sentence_mk: "Тој е премногу мрзлив.", image: "😴" },
  { word: "ehrlich", translation: "чесен", category: "adjective", sentence_de: "Sie ist immer ehrlich.", sentence_mk: "Таа е секогаш чесна.", image: "🤝" },
  { word: "lustig", translation: "смешен", category: "adjective", sentence_de: "Der Film ist lustig.", sentence_mk: "Филмот е смешен.", image: "😂" },
  { word: "ruhig", translation: "мирен", category: "adjective", sentence_de: "Er ist ein ruhiger Mensch.", sentence_mk: "Тој е мирен човек.", image: "😌" },
  { word: "nervös", translation: "нервозен", category: "adjective", sentence_de: "Sie ist vor der Prüfung nervös.", sentence_mk: "Таа е нервозна пред испитот.", image: "😰" },
  { word: "neugierig", translation: "љубопитен", category: "adjective", sentence_de: "Das Kind ist neugierig.", sentence_mk: "Детето е љубопитно.", image: "🧐" },
  { word: "mutig", translation: "храбар", category: "adjective", sentence_de: "Der Feuerwehrmann ist mutig.", sentence_mk: "Пожарникарот е храбар.", image: "🦸" },
  { word: "ängstlich", translation: "плашлив", category: "adjective", sentence_de: "Das Kind ist ängstlich.", sentence_mk: "Детето е плашливо.", image: "😨" },
  { word: "geduldig", translation: "трпелив", category: "adjective", sentence_de: "Gute Lehrer sind geduldig.", sentence_mk: "Добрите учители се трпеливи.", image: "⏳" },
  { word: "stolz", translation: "горд", category: "adjective", sentence_de: "Ich bin stolz auf dich.", sentence_mk: "Горд сум на тебе.", image: "😤" },
  { word: "zuverlässig", translation: "доверлив", category: "adjective", sentence_de: "Er ist sehr zuverlässig.", sentence_mk: "Тој е многу доверлив.", image: "🤝" },
  { word: "kreativ", translation: "креативен", category: "adjective", sentence_de: "Sie ist sehr kreativ.", sentence_mk: "Таа е многу креативна.", image: "🎨" },
  { word: "intelligent", translation: "интелигентен", category: "adjective", sentence_de: "Das Kind ist sehr intelligent.", sentence_mk: "Детето е многу интелигентно.", image: "🧠" },

  // ЧУВСТВА И ЕМОЦИИ (FEELINGS AND EMOTIONS)
  { word: "die Freude", translation: "радоста", category: "noun", gender: "die", sentence_de: "Die Freude ist groß.", sentence_mk: "Радоста е голема.", image: "😊" },
  { word: "die Trauer", translation: "тагата", category: "noun", gender: "die", sentence_de: "Die Trauer ist tief.", sentence_mk: "Тагата е длабока.", image: "😢" },
  { word: "die Wut", translation: "лутината", category: "noun", gender: "die", sentence_de: "Die Wut ist stark.", sentence_mk: "Лутината е силна.", image: "😡" },
  { word: "die Angst", translation: "стравот", category: "noun", gender: "die", sentence_de: "Die Angst ist groß.", sentence_mk: "Стравот е голем.", image: "😨" },
  { word: "die Überraschung", translation: "изненадувањето", category: "noun", gender: "die", sentence_de: "Die Überraschung ist groß.", sentence_mk: "Изненадувањето е големо.", image: "😲" },
  { word: "die Liebe", translation: "љубовта", category: "noun", gender: "die", sentence_de: "Die Liebe ist schön.", sentence_mk: "Љубовта е убава.", image: "❤️" },
  { word: "der Stress", translation: "стресот", category: "noun", gender: "der", sentence_de: "Der Stress ist zu viel.", sentence_mk: "Стресот е премногу.", image: "😤" },
  { word: "sich freuen", translation: "се радувам", category: "verb", sentence_de: "Ich freue mich auf den Urlaub.", sentence_mk: "Се радувам на одморот.", image: "😊" },
  { word: "sich ärgern", translation: "се лутам", category: "verb", sentence_de: "Er ärgert sich über den Fehler.", sentence_mk: "Тој се лути на грешката.", image: "😡" },
  { word: "sich fürchten", translation: "се плашам", category: "verb", sentence_de: "Das Kind fürchtet sich vor dem Hund.", sentence_mk: "Детето се плаши од кучето.", image: "😨" },
  { word: "sich wundern", translation: "се чудам", category: "verb", sentence_de: "Ich wundere mich darüber.", sentence_mk: "Се чудам на тоа.", image: "😲" },
  { word: "sich langweilen", translation: "се здодевувам", category: "verb", sentence_de: "Ich langweile mich.", sentence_mk: "Ми е здодевно.", image: "😴" },
  { word: "lachen", translation: "се смеам", category: "verb", sentence_de: "Wir lachen zusammen.", sentence_mk: "Заедно се смееме.", image: "😂" },
  { word: "weinen", translation: "плачам", category: "verb", sentence_de: "Das Kind weint.", sentence_mk: "Детето плаче.", image: "😢" },

  // ВРЕМЕНСКИ ПРИЛИКИ (WEATHER)
  { word: "das Wetter", translation: "времето (атмосферско)", category: "noun", gender: "das", sentence_de: "Das Wetter ist schön.", sentence_mk: "Времето е убаво.", image: "⛅" },
  { word: "die Temperatur", translation: "температурата", category: "noun", gender: "die", sentence_de: "Die Temperatur ist niedrig.", sentence_mk: "Температурата е ниска.", image: "🌡️" },
  { word: "der Grad", translation: "степенот", category: "noun", gender: "der", sentence_de: "Es sind 20 Grad.", sentence_mk: "Има 20 степени.", image: "🌡️" },
  { word: "das Gewitter", translation: "грмотевицата", category: "noun", gender: "das", sentence_de: "Das Gewitter kommt.", sentence_mk: "Грмотевицата доаѓа.", image: "⛈️" },
  { word: "der Blitz", translation: "молњата", category: "noun", gender: "der", sentence_de: "Der Blitz ist hell.", sentence_mk: "Молњата е светла.", image: "⚡" },
  { word: "der Donner", translation: "громот", category: "noun", gender: "der", sentence_de: "Der Donner ist laut.", sentence_mk: "Громот е гласен.", image: "⛈️" },
  { word: "der Nebel", translation: "маглата", category: "noun", gender: "der", sentence_de: "Der Nebel ist dicht.", sentence_mk: "Маглата е густа.", image: "🌫️" },
  { word: "der Frost", translation: "мразот", category: "noun", gender: "der", sentence_de: "Der Frost ist stark.", sentence_mk: "Мразот е силен.", image: "🥶" },
  { word: "die Hitze", translation: "жегата", category: "noun", gender: "die", sentence_de: "Die Hitze ist unerträglich.", sentence_mk: "Жегата е неподнослива.", image: "🔥" },
  { word: "sonnig", translation: "сончево", category: "adjective", sentence_de: "Heute ist es sonnig.", sentence_mk: "Денес е сончево.", image: "☀️" },
  { word: "bewölkt", translation: "облачно", category: "adjective", sentence_de: "Es ist bewölkt.", sentence_mk: "Облачно е.", image: "☁️" },
  { word: "regnerisch", translation: "дождовно", category: "adjective", sentence_de: "Das Wetter ist regnerisch.", sentence_mk: "Времето е дождовно.", image: "🌧️" },
  { word: "windig", translation: "ветровито", category: "adjective", sentence_de: "Es ist sehr windig.", sentence_mk: "Многу е ветровито.", image: "💨" },
  { word: "neblig", translation: "магловито", category: "adjective", sentence_de: "Der Morgen ist neblig.", sentence_mk: "Утрото е магловито.", image: "🌫️" },
  { word: "trocken", translation: "суво", category: "adjective", sentence_de: "Das Klima ist trocken.", sentence_mk: "Климата е сува.", image: "🏜️" },
  { word: "feucht", translation: "влажно", category: "adjective", sentence_de: "Das Wetter ist feucht.", sentence_mk: "Времето е влажно.", image: "💧" },

  // НАСОКИ И ЛОКАЦИЈА (DIRECTIONS AND LOCATION)
  { word: "die Richtung", translation: "насоката", category: "noun", gender: "die", sentence_de: "In welche Richtung?", sentence_mk: "Во која насока?", image: "🧭" },
  { word: "die Ecke", translation: "аголот", category: "noun", gender: "die", sentence_de: "Biegen Sie an der Ecke ab.", sentence_mk: "Свртете на аголот.", image: "🔀" },
  { word: "die Kreuzung", translation: "раскрсницата", category: "noun", gender: "die", sentence_de: "An der Kreuzung rechts.", sentence_mk: "На раскрсницата десно.", image: "🚦" },
  { word: "die Ampel", translation: "семафорот", category: "noun", gender: "die", sentence_de: "Die Ampel ist rot.", sentence_mk: "Семафорот е црвен.", image: "🚦" },
  { word: "der Zebrastreifen", translation: "пешачкиот премин", category: "noun", gender: "der", sentence_de: "Geh über den Zebrastreifen.", sentence_mk: "Помини на пешачкиот премин.", image: "🦓" },
  { word: "der Wegweiser", translation: "патоказот", category: "noun", gender: "der", sentence_de: "Der Wegweiser zeigt rechts.", sentence_mk: "Патоказот покажува десно.", image: "🪧" },
  { word: "die Entfernung", translation: "растојанието", category: "noun", gender: "die", sentence_de: "Die Entfernung ist kurz.", sentence_mk: "Растојанието е кратко.", image: "📏" },
  { word: "der Kilometer", translation: "километарот", category: "noun", gender: "der", sentence_de: "Es sind 5 Kilometer.", sentence_mk: "Тоа е 5 километри.", image: "🛣️" },
  { word: "abbiegen", translation: "свртувам", category: "verb", sentence_de: "Biegen Sie links ab.", sentence_mk: "Свртете лево.", image: "↩️" },
  { word: "überqueren", translation: "преминувам", category: "verb", sentence_de: "Überquere die Straße.", sentence_mk: "Премини ја улицата.", image: "🚶" },
  { word: "entlang", translation: "покрај/по должина", category: "other", sentence_de: "Gehen Sie die Straße entlang.", sentence_mk: "Одете по улицата.", image: "🛣️" },
  { word: "gegenüber", translation: "наспроти", category: "other", sentence_de: "Die Bank ist gegenüber dem Bahnhof.", sentence_mk: "Банката е наспроти станицата.", image: "🏦" },

  // ДОПОЛНИТЕЛНИ ГЛАГОЛИ (ADDITIONAL VERBS)
  { word: "erklären", translation: "објаснувам", category: "verb", sentence_de: "Kannst du das erklären?", sentence_mk: "Можеш ли тоа да го објасниш?", image: "💡" },
  { word: "beschreiben", translation: "опишувам", category: "verb", sentence_de: "Beschreibe das Bild.", sentence_mk: "Опиши ја сликата.", image: "🖼️" },
  { word: "vergleichen", translation: "споредувам", category: "verb", sentence_de: "Ich vergleiche die Preise.", sentence_mk: "Ги споредувам цените.", image: "⚖️" },
  { word: "wiederholen", translation: "повторувам", category: "verb", sentence_de: "Wiederhol das bitte.", sentence_mk: "Повтори, те молам.", image: "🔁" },
  { word: "übersetzen", translation: "преведувам", category: "verb", sentence_de: "Kannst du das übersetzen?", sentence_mk: "Можеш ли да преведеш?", image: "🌐" },
  { word: "buchstabieren", translation: "кажувам по букви", category: "verb", sentence_de: "Buchstabiere deinen Namen.", sentence_mk: "Кажи го твоето име по букви.", image: "🔤" },
  { word: "ausfüllen", translation: "пополнувам", category: "verb", sentence_de: "Fülle das Formular aus.", sentence_mk: "Пополни го формуларот.", image: "📝" },
  { word: "unterschreiben", translation: "потпишувам", category: "verb", sentence_de: "Unterschreib hier.", sentence_mk: "Потпиши тука.", image: "✍️" },
  { word: "anrufen", translation: "се јавувам (телефон)", category: "verb", sentence_de: "Ich rufe dich an.", sentence_mk: "Ќе ти се јавам.", image: "📞" },
  { word: "zurückrufen", translation: "се јавувам назад", category: "verb", sentence_de: "Ich rufe zurück.", sentence_mk: "Ќе се јавам назад.", image: "📞" },
  { word: "abholen", translation: "доаѓам да земам/пречекувам", category: "verb", sentence_de: "Ich hole dich ab.", sentence_mk: "Ќе те дојдам да те земам.", image: "🚗" },
  { word: "einladen", translation: "канам", category: "verb", sentence_de: "Ich lade dich ein.", sentence_mk: "Те канам.", image: "🎉" },
  { word: "ablehnen", translation: "одбивам", category: "verb", sentence_de: "Ich lehne das Angebot ab.", sentence_mk: "Ја одбивам понудата.", image: "❌" },
  { word: "zustimmen", translation: "се согласувам", category: "verb", sentence_de: "Ich stimme zu.", sentence_mk: "Се согласувам.", image: "✅" },
  { word: "versprechen", translation: "ветувам", category: "verb", sentence_de: "Ich verspreche dir das.", sentence_mk: "Ти ветувам тоа.", image: "🤝" },
  { word: "vergessen", translation: "заборавам", category: "verb", sentence_de: "Ich habe den Termin vergessen.", sentence_mk: "Го заборавив термин.", image: "🤦" },
  { word: "sich erinnern", translation: "се сетувам", category: "verb", sentence_de: "Ich erinnere mich an dich.", sentence_mk: "Се сеќавам на тебе.", image: "🧠" },
  { word: "passieren", translation: "се случува", category: "verb", sentence_de: "Was ist passiert?", sentence_mk: "Што се случи?", image: "❓" },
  { word: "dauern", translation: "трае", category: "verb", sentence_de: "Das dauert lange.", sentence_mk: "Тоа трае долго.", image: "⏳" },
  { word: "beginnen", translation: "започнувам", category: "verb", sentence_de: "Der Film beginnt um 20 Uhr.", sentence_mk: "Филмот започнува во 20 часот.", image: "▶️" },
  { word: "enden", translation: "завршувам", category: "verb", sentence_de: "Der Unterricht endet um 14 Uhr.", sentence_mk: "Наставата завршува во 14 часот.", image: "⏹️" },
  { word: "warten", translation: "чекам", category: "verb", sentence_de: "Ich warte auf den Bus.", sentence_mk: "Чекам автобус.", image: "⏳" },
  { word: "benutzen", translation: "користам", category: "verb", sentence_de: "Ich benutze den Computer.", sentence_mk: "Го користам компјутерот.", image: "💻" },
  { word: "funktionieren", translation: "функционира", category: "verb", sentence_de: "Das Handy funktioniert nicht.", sentence_mk: "Мобилниот не функционира.", image: "📱" },
  { word: "reparieren", translation: "поправам", category: "verb", sentence_de: "Ich repariere das Auto.", sentence_mk: "Го поправам автомобилот.", image: "🔧" },
  { word: "putzen", translation: "чистам", category: "verb", sentence_de: "Ich putze das Zimmer.", sentence_mk: "Ја чистам собата.", image: "🧹" },
  { word: "waschen", translation: "перам", category: "verb", sentence_de: "Ich wasche die Wäsche.", sentence_mk: "Ја перам облеката.", image: "🧺" },
  { word: "bügeln", translation: "пеглам", category: "verb", sentence_de: "Ich bügle das Hemd.", sentence_mk: "Ја пеглам кошулата.", image: "👔" },
  { word: "aufräumen", translation: "средувам", category: "verb", sentence_de: "Ich räume das Zimmer auf.", sentence_mk: "Ја средувам собата.", image: "🧹" },
  { word: "staubsaugen", translation: "правосмукувам", category: "verb", sentence_de: "Ich staubsauge das Zimmer.", sentence_mk: "Го правосмукувам собата.", image: "🧹" },

  // ОПИШУВАЊЕ НА ПРЕДМЕТИ (DESCRIBING OBJECTS)
  { word: "schwer", translation: "тежок", category: "adjective", sentence_de: "Der Koffer ist schwer.", sentence_mk: "Куферот е тежок.", image: "🏋️" },
  { word: "leicht", translation: "лесен (тежина)", category: "adjective", sentence_de: "Das Buch ist leicht.", sentence_mk: "Книгата е лесна.", image: "🪶" },
  { word: "weich", translation: "мек", category: "adjective", sentence_de: "Das Bett ist weich.", sentence_mk: "Креветот е мек.", image: "🛏️" },
  { word: "hart", translation: "тврд", category: "adjective", sentence_de: "Der Boden ist hart.", sentence_mk: "Подот е тврд.", image: "🪨" },
  { word: "rund", translation: "тркалезен", category: "adjective", sentence_de: "Der Ball ist rund.", sentence_mk: "Топката е тркалезна.", image: "⚽" },
  { word: "eckig", translation: "аголест", category: "adjective", sentence_de: "Der Tisch ist eckig.", sentence_mk: "Масата е аголеста.", image: "⬜" },
  { word: "flach", translation: "рамен", category: "adjective", sentence_de: "Das Land ist flach.", sentence_mk: "Земјата е рамна.", image: "⬜" },
  { word: "tief", translation: "длабок", category: "adjective", sentence_de: "Das Wasser ist tief.", sentence_mk: "Водата е длабока.", image: "🌊" },
  { word: "breit", translation: "широк", category: "adjective", sentence_de: "Die Straße ist breit.", sentence_mk: "Улицата е широка.", image: "🛣️" },
  { word: "eng", translation: "тесен", category: "adjective", sentence_de: "Die Hose ist eng.", sentence_mk: "Панталоните се тесни.", image: "👖" },
  { word: "voll", translation: "полн", category: "adjective", sentence_de: "Der Bus ist voll.", sentence_mk: "Автобусот е полн.", image: "🚌" },
  { word: "leer", translation: "празен", category: "adjective", sentence_de: "Die Flasche ist leer.", sentence_mk: "Шишето е празно.", image: "🍾" },
  { word: "einfach", translation: "едноставен/лесен", category: "adjective", sentence_de: "Das ist einfach.", sentence_mk: "Тоа е едноставно.", image: "✅" },
  { word: "schwierig", translation: "тежок/сложен", category: "adjective", sentence_de: "Das ist schwierig.", sentence_mk: "Тоа е тешко.", image: "❌" },
  { word: "möglich", translation: "можно", category: "adjective", sentence_de: "Das ist möglich.", sentence_mk: "Тоа е можно.", image: "✅" },
  { word: "unmöglich", translation: "невозможно", category: "adjective", sentence_de: "Das ist unmöglich.", sentence_mk: "Тоа е невозможно.", image: "❌" },
  { word: "wichtig", translation: "важен", category: "adjective", sentence_de: "Das ist sehr wichtig.", sentence_mk: "Тоа е многу важно.", image: "❗" },
  { word: "notwendig", translation: "неопходен", category: "adjective", sentence_de: "Das ist notwendig.", sentence_mk: "Тоа е неопходно.", image: "❗" },
  { word: "beliebt", translation: "омилен/популарен", category: "adjective", sentence_de: "Das Lied ist beliebt.", sentence_mk: "Песната е популарна.", image: "❤️" },
  { word: "bekannt", translation: "познат", category: "adjective", sentence_de: "Er ist ein bekannter Künstler.", sentence_mk: "Тој е познат уметник.", image: "🌟" },

  // ДОПОЛНИТЕЛНИ ИМЕНКИ (ADDITIONAL NOUNS)
  { word: "das Problem", translation: "проблемот", category: "noun", gender: "das", sentence_de: "Das Problem ist gelöst.", sentence_mk: "Проблемот е решен.", image: "❓" },
  { word: "die Lösung", translation: "решението", category: "noun", gender: "die", sentence_de: "Ich habe eine Lösung.", sentence_mk: "Имам решение.", image: "💡" },
  { word: "die Frage", translation: "прашањето", category: "noun", gender: "die", sentence_de: "Ich habe eine Frage.", sentence_mk: "Имам прашање.", image: "❓" },
  { word: "die Antwort", translation: "одговорот", category: "noun", gender: "die", sentence_de: "Die Antwort ist richtig.", sentence_mk: "Одговорот е точен.", image: "💬" },
  { word: "der Fehler", translation: "грешката", category: "noun", gender: "der", sentence_de: "Ich habe einen Fehler gemacht.", sentence_mk: "Направив грешка.", image: "❌" },
  { word: "der Grund", translation: "причината", category: "noun", gender: "der", sentence_de: "Was ist der Grund?", sentence_mk: "Која е причината?", image: "🤔" },
  { word: "das Beispiel", translation: "примерот", category: "noun", gender: "das", sentence_de: "Zum Beispiel...", sentence_mk: "На пример...", image: "📋" },
  { word: "die Möglichkeit", translation: "можноста", category: "noun", gender: "die", sentence_de: "Es gibt viele Möglichkeiten.", sentence_mk: "Има многу можности.", image: "🚀" },
  { word: "die Entscheidung", translation: "одлуката", category: "noun", gender: "die", sentence_de: "Die Entscheidung ist schwer.", sentence_mk: "Одлуката е тешка.", image: "⚖️" },
  { word: "der Plan", translation: "планот", category: "noun", gender: "der", sentence_de: "Der Plan ist gut.", sentence_mk: "Планот е добар.", image: "📋" },
  { word: "das Ziel", translation: "целта", category: "noun", gender: "das", sentence_de: "Mein Ziel ist es, Deutsch zu lernen.", sentence_mk: "Мојата цел е да учам германски.", image: "🎯" },
  { word: "die Erfahrung", translation: "искуството", category: "noun", gender: "die", sentence_de: "Ich habe viel Erfahrung.", sentence_mk: "Имам многу искуство.", image: "🧠" },
  { word: "das Ergebnis", translation: "резултатот", category: "noun", gender: "das", sentence_de: "Das Ergebnis ist positiv.", sentence_mk: "Резултатот е позитивен.", image: "✅" },
  { word: "die Veranstaltung", translation: "настанот", category: "noun", gender: "die", sentence_de: "Die Veranstaltung ist morgen.", sentence_mk: "Настанот е утре.", image: "🎉" },
  { word: "das Fest", translation: "прославата", category: "noun", gender: "das", sentence_de: "Das Fest ist laut.", sentence_mk: "Прославата е гласна.", image: "🎊" },
  { word: "die Einladung", translation: "поканата", category: "noun", gender: "die", sentence_de: "Ich habe eine Einladung bekommen.", sentence_mk: "Добив покана.", image: "💌" },
  { word: "das Geschenk", translation: "подарокот", category: "noun", gender: "das", sentence_de: "Das Geschenk ist schön.", sentence_mk: "Подарокот е убав.", image: "🎁" },
  { word: "die Glückwunschkarte", translation: "честитката", category: "noun", gender: "die", sentence_de: "Ich schreibe eine Glückwunschkarte.", sentence_mk: "Пишувам честитка.", image: "💌" },
  { word: "der Geburtstag", translation: "роденденот", category: "noun", gender: "der", sentence_de: "Heute ist mein Geburtstag.", sentence_mk: "Денес е мојот роденден.", image: "🎂" },
  { word: "die Hochzeit", translation: "свадбата", category: "noun", gender: "die", sentence_de: "Die Hochzeit ist im Juni.", sentence_mk: "Свадбата е во јуни.", image: "💒" },
  { word: "Weihnachten", translation: "Божиќ", category: "noun", gender: "das", sentence_de: "Frohe Weihnachten!", sentence_mk: "Среќен Божиќ!", image: "🎄" },
  { word: "Ostern", translation: "Велигден", category: "noun", gender: "das", sentence_de: "Frohe Ostern!", sentence_mk: "Среќен Велигден!", image: "🐣" },
  { word: "Silvester", translation: "Нова Година (31 дек)", category: "noun", gender: "der", sentence_de: "Silvester feiern wir zusammen.", sentence_mk: "Нова Година ја прославуваме заедно.", image: "🎆" },

  // КОМУНИКАЦИЈА (COMMUNICATION)
  { word: "Entschuldigung!", translation: "Извинете!", category: "other", sentence_de: "Entschuldigung, wo ist die Bank?", sentence_mk: "Извинете, каде е банката?", image: "🙏" },
  { word: "Bitte!", translation: "Те молам/Ве молам!", category: "other", sentence_de: "Ein Kaffee, bitte!", sentence_mk: "Едно кафе, те молам!", image: "☕" },
  { word: "Danke!", translation: "Благодарам!", category: "other", sentence_de: "Danke sehr!", sentence_mk: "Многу благодарам!", image: "🙏" },
  { word: "Bitte sehr!", translation: "Заповедај!", category: "other", sentence_de: "Hier ist dein Kaffee. – Bitte sehr!", sentence_mk: "Еве твоето кафе. – Заповедај!", image: "☕" },
  { word: "Gern geschehen!", translation: "Нема на што!", category: "other", sentence_de: "Danke! – Gern geschehen!", sentence_mk: "Благодарам! – Нема на што!", image: "😊" },
  { word: "Wie bitte?", translation: "Молам?", category: "other", sentence_de: "Wie bitte? Ich habe das nicht verstanden.", sentence_mk: "Молам? Не разбрав.", image: "🤔" },
  { word: "Ich verstehe nicht.", translation: "Не разбирам.", category: "other", sentence_de: "Ich verstehe nicht. Kannst du das wiederholen?", sentence_mk: "Не разбирам. Можеш ли да повториш?", image: "🤷" },
  { word: "Kannst du langsamer sprechen?", translation: "Можеш ли да зборуваш побавно?", category: "other", sentence_de: "Kannst du bitte langsamer sprechen?", sentence_mk: "Можеш ли те молам да зборуваш побавно?", image: "🐢" },
  { word: "Was bedeutet das?", translation: "Што значи тоа?", category: "other", sentence_de: "Was bedeutet das Wort?", sentence_mk: "Што значи тој збор?", image: "❓" },
  { word: "Ich bin einverstanden.", translation: "Се согласувам.", category: "other", sentence_de: "Ich bin einverstanden.", sentence_mk: "Се согласувам.", image: "✅" },
  { word: "Das stimmt.", translation: "Тоа е точно.", category: "other", sentence_de: "Das stimmt, du hast recht.", sentence_mk: "Тоа е точно, ти имаш право.", image: "✅" },
  { word: "Das stimmt nicht.", translation: "Тоа не е точно.", category: "other", sentence_de: "Das stimmt nicht.", sentence_mk: "Тоа не е точно.", image: "❌" },
  { word: "Meiner Meinung nach", translation: "Според моето мислење", category: "other", sentence_de: "Meiner Meinung nach ist das falsch.", sentence_mk: "Според моето мислење тоа е грешно.", image: "💭" },
  { word: "Ich glaube, dass...", translation: "Верувам дека...", category: "other", sentence_de: "Ich glaube, dass das stimmt.", sentence_mk: "Верувам дека тоа е точно.", image: "💭" },
  { word: "Es tut mir leid.", translation: "Жалам/Извини.", category: "other", sentence_de: "Es tut mir leid, ich komme zu spät.", sentence_mk: "Жалам, задоцнувам.", image: "😔" },
  { word: "Macht nichts!", translation: "Ништо страшно!", category: "other", sentence_de: "Entschuldigung! – Macht nichts!", sentence_mk: "Извинете! – Ништо страшно!", image: "😊" },
  { word: "Auf Wiedersehen!", translation: "Довидување!", category: "other", sentence_de: "Auf Wiedersehen und alles Gute!", sentence_mk: "Довидување и се најдобро!", image: "👋" },
  { word: "Tschüss!", translation: "Пај-пај!/Чао!", category: "other", sentence_de: "Tschüss, bis morgen!", sentence_mk: "Чао, до утре!", image: "👋" },
  { word: "Bis bald!", translation: "До наскоро!", category: "other", sentence_de: "Bis bald, mein Freund!", sentence_mk: "До наскоро, мој пријателу!", image: "👋" },
  { word: "Herzlich willkommen!", translation: "Добредојдовте!", category: "other", sentence_de: "Herzlich willkommen in Berlin!", sentence_mk: "Добредојдовте во Берлин!", image: "🎉" },
];
