import { ImportData } from './types';

export const B1_VOCABULARY: ImportData[] = [
  // РАБОТА И КАРИЕРА (WORK AND CAREER)
  { word: "die Berufserfahrung", translation: "работното искуство", category: "noun", gender: "die", sentence_de: "Ich habe viel Berufserfahrung.", sentence_mk: "Имам многу работно искуство.", image: "💼" },
  { word: "die Bewerbung", translation: "апликацијата (за работа)", category: "noun", gender: "die", sentence_de: "Ich schreibe eine Bewerbung.", sentence_mk: "Пишувам апликација за работа.", image: "📝" },
  { word: "der Lebenslauf", translation: "биографијата", category: "noun", gender: "der", sentence_de: "Mein Lebenslauf ist aktuell.", sentence_mk: "Мојата биографија е ажурирана.", image: "📄" },
  { word: "das Vorstellungsgespräch", translation: "интервјуто за работа", category: "noun", gender: "das", sentence_de: "Das Vorstellungsgespräch war erfolgreich.", sentence_mk: "Интервјуто за работа беше успешно.", image: "🤝" },
  { word: "die Stelle", translation: "работното место", category: "noun", gender: "die", sentence_de: "Die Stelle ist interessant.", sentence_mk: "Работното место е интересно.", image: "💼" },
  { word: "die Firma", translation: "фирмата", category: "noun", gender: "die", sentence_de: "Die Firma ist international.", sentence_mk: "Фирмата е интернационална.", image: "🏢" },
  { word: "der Chef", translation: "шефот", category: "noun", gender: "der", sentence_de: "Mein Chef ist freundlich.", sentence_mk: "Мојот шеф е пријатен.", image: "👔" },
  { word: "der Kollege", translation: "колегата", category: "noun", gender: "der", sentence_de: "Mein Kollege hilft mir.", sentence_mk: "Мојот колега ми помага.", image: "👥" },
  { word: "die Abteilung", translation: "одделот", category: "noun", gender: "die", sentence_de: "Ich arbeite in der Marketingabteilung.", sentence_mk: "Работам во маркетинг одделот.", image: "📊" },
  { word: "das Gehalt", translation: "платата", category: "noun", gender: "das", sentence_de: "Das Gehalt ist gut.", sentence_mk: "Платата е добра.", image: "💰" },
  { word: "die Steuern", translation: "даноците", category: "noun", sentence_de: "Die Steuern sind hoch.", sentence_mk: "Даноците се високи.", image: "📊" },
  { word: "der Urlaub", translation: "одморот", category: "noun", gender: "der", sentence_de: "Ich habe 30 Tage Urlaub.", sentence_mk: "Имам 30 дена одмор.", image: "🏖️" },
  { word: "die Kündigung", translation: "отказот", category: "noun", gender: "die", sentence_de: "Die Kündigung kam überraschend.", sentence_mk: "Отказот дојде изненадно.", image: "📄" },
  { word: "arbeitslos", translation: "невработен", category: "adjective", sentence_de: "Er ist arbeitslos.", sentence_mk: "Тој е невработен.", image: "😔" },
  { word: "selbstständig", translation: "самовработен", category: "adjective", sentence_de: "Sie ist selbstständig.", sentence_mk: "Таа е самовработена.", image: "💪" },
  { word: "die Gewerkschaft", translation: "синдикатот", category: "noun", gender: "die", sentence_de: "Die Gewerkschaft kämpft für bessere Löhne.", sentence_mk: "Синдикатот се бори за подобри плати.", image: "⚖️" },
  { word: "die Arbeitszeit", translation: "работното време", category: "noun", gender: "die", sentence_de: "Meine Arbeitszeit ist flexibel.", sentence_mk: "Моето работно време е флексибилно.", image: "⏰" },
  { word: "die Überstunden", translation: "прекувремените часови", category: "noun", sentence_de: "Ich mache oft Überstunden.", sentence_mk: "Често работам прекувремено.", image: "⏳" },

  // ПАТУВАЊЕ (TRAVEL)
  { word: "die Reise", translation: "патувањето", category: "noun", gender: "die", sentence_de: "Die Reise war wunderschön.", sentence_mk: "Патувањето беше прекрасно.", image: "✈️" },
  { word: "die Reiseapotheke", translation: "патната аптека", category: "noun", gender: "die", sentence_de: "Meine Reiseapotheke ist voll.", sentence_mk: "Мојата патна аптека е полна.", image: "💊" },
  { word: "die Bordkarte", translation: "бординг картата", category: "noun", gender: "die", sentence_de: "Hier ist meine Bordkarte.", sentence_mk: "Еве ја мојата бординг карта.", image: "🎫" },
  { word: "der Koffer", translation: "куферот", category: "noun", gender: "der", sentence_de: "Mein Koffer ist schwer.", sentence_mk: "Мојот куфер е тежок.", image: "🧳" },
  { word: "das Handgepäck", translation: "рачниот багаж", category: "noun", gender: "das", sentence_de: "Das Handgepäck ist klein.", sentence_mk: "Рачниот багаж е мал.", image: "🛄" },
  { word: "die Unterkunft", translation: "сместувањето", category: "noun", gender: "die", sentence_de: "Die Unterkunft ist gemütlich.", sentence_mk: "Сместувањето е пријатно.", image: "🏨" },
  { word: "das Hotel", translation: "хотелот", category: "noun", gender: "das", sentence_de: "Das Hotel hat vier Sterne.", sentence_mk: "Хотелот има четири ѕвезди.", image: "🏨" },
  { word: "die Jugendherberge", translation: "младинскиот хостел", category: "noun", gender: "die", sentence_de: "Die Jugendherberge ist preiswert.", sentence_mk: "Младинскиот хостел е евтин.", image: "🛏️" },
  { word: "die Pension", translation: "пансионот", category: "noun", gender: "die", sentence_de: "Die Pension ist familiär.", sentence_mk: "Пансионот е семеен.", image: "🏡" },
  { word: "der Campingplatz", translation: "кампот", category: "noun", gender: "der", sentence_de: "Der Campingplatz ist am See.", sentence_mk: "Кампот е на езерото.", image: "🏕️" },
  { word: "die Reiseleitung", translation: "туристичкиот водич", category: "noun", gender: "die", sentence_de: "Die Reiseleitung ist kompetent.", sentence_mk: "Туристичкиот водич е компетентен.", image: "🧑‍🏫" },
  { word: "der Ausflug", translation: "излетот", category: "noun", gender: "der", sentence_de: "Wir machen einen Ausflug.", sentence_mk: "Правиме излет.", image: "🚌" },
  { word: "die Rundfahrt", translation: "кружниот тур", category: "noun", gender: "die", sentence_de: "Die Stadtrundfahrt dauert zwei Stunden.", sentence_mk: "Кружниот тур низ градот трае два часа.", image: "🚌" },
  { word: "die Besichtigung", translation: "разгледувањето", category: "noun", gender: "die", sentence_de: "Die Besichtigung des Museums war interessant.", sentence_mk: "Разгледувањето на музејот беше интересно.", image: "🏛️" },
  { word: "das Reiseziel", translation: "дестинацијата", category: "noun", gender: "das", sentence_de: "Unser Reiseziel ist Italien.", sentence_mk: "Нашата дестинација е Италија.", image: "🌍" },
  { word: "die Grenze", translation: "границата", category: "noun", gender: "die", sentence_de: "Wir überqueren die Grenze.", sentence_mk: "Ја преминуваме границата.", image: "🛂" },
  { word: "der Zoll", translation: "царината", category: "noun", gender: "der", sentence_de: "Am Zoll muss man den Pass zeigen.", sentence_mk: "На царина треба да се покаже пасош.", image: "🛃" },
  { word: "das Visum", translation: "визата", category: "noun", gender: "das", sentence_de: "Für die USA braucht man ein Visum.", sentence_mk: "За САД потребна е виза.", image: "🛂" },
  { word: "der Reiseführer", translation: "туристичкиот водич (книга)", category: "noun", gender: "der", sentence_de: "Der Reiseführer ist sehr informativ.", sentence_mk: "Туристичкиот водич е многу информативен.", image: "📚" },
  { word: "die Sehenswürdigkeit", translation: "знаменитоста", category: "noun", gender: "die", sentence_de: "Der Kölner Dom ist eine Sehenswürdigkeit.", sentence_mk: "Келнската катедрала е знаменитост.", image: "🏛️" },

  // МЕДИУМИ (MEDIA)
  { word: "die Nachrichten", translation: "вестите", category: "noun", sentence_de: "Ich sehe jeden Tag die Nachrichten.", sentence_mk: "Гледам вести секој ден.", image: "📺" },
  { word: "die Tagesschau", translation: "дневните вести (ТВ)", category: "noun", gender: "die", sentence_de: "Die Tagesschau kommt um 20 Uhr.", sentence_mk: "Дневните вести доаѓаат во 20 часот.", image: "📺" },
  { word: "die Sendung", translation: "емисијата", category: "noun", gender: "die", sentence_de: "Die Sendung ist interessant.", sentence_mk: "Емисијата е интересна.", image: "📻" },
  { word: "der Sender", translation: "каналот", category: "noun", gender: "der", sentence_de: "Welcher Sender zeigt den Film?", sentence_mk: "Кој канал го прикажува филмот?", image: "📺" },
  { word: "die Zeitschrift", translation: "списанието", category: "noun", gender: "die", sentence_de: "Ich lese eine Zeitschrift.", sentence_mk: "Читам списание.", image: "📰" },
  { word: "die Illustrierte", translation: "илустрираното списание", category: "noun", gender: "die", sentence_de: "In der Illustrierten sind viele Bilder.", sentence_mk: "Во илустрираното списание има многу слики.", image: "📰" },
  { word: "die Schlagzeile", translation: "насловот", category: "noun", gender: "die", sentence_de: "Die Schlagzeile ist groß.", sentence_mk: "Насловот е голем.", image: "📰" },
  { word: "der Artikel", translation: "статијата", category: "noun", gender: "der", sentence_de: "Der Artikel ist lang.", sentence_mk: "Статијата е долга.", image: "📄" },
  { word: "der Reporter", translation: "репортерот", category: "noun", gender: "der", sentence_de: "Der Reporter interviewt den Star.", sentence_mk: "Репортерот интервјуира ѕвезда.", image: "🎤" },
  { word: "die Pressefreiheit", translation: "слободата на печатот", category: "noun", gender: "die", sentence_de: "Die Pressefreiheit ist wichtig.", sentence_mk: "Слободата на печатот е важна.", image: "🗽" },
  { word: "die Reportage", translation: "репортажата", category: "noun", gender: "die", sentence_de: "Die Reportage ist spannend.", sentence_mk: "Репортажата е возбудлива.", image: "📹" },
  { word: "das Interview", translation: "интервјуто", category: "noun", gender: "das", sentence_de: "Das Interview war informativ.", sentence_mk: "Интервјуто беше информативно.", image: "🎙️" },
  { word: "die Serie", translation: "серијата", category: "noun", gender: "die", sentence_de: "Die Serie hat zehn Folgen.", sentence_mk: "Серијата има десет епизоди.", image: "📺" },
  { word: "die Folge", translation: "епизодата", category: "noun", gender: "die", sentence_de: "Die nächste Folge kommt morgen.", sentence_mk: "Следната епизода доаѓа утре.", image: "📺" },
  { word: "die Staffel", translation: "сезоната (ТВ)", category: "noun", gender: "die", sentence_de: "Die dritte Staffel beginnt.", sentence_mk: "Третата сезона започнува.", image: "📺" },
  { word: "der Dokumentarfilm", translation: "документарниот филм", category: "noun", gender: "der", sentence_de: "Der Dokumentarfilm zeigt Tiere.", sentence_mk: "Документарниот филм покажува животни.", image: "🎥" },
  { word: "die Talkshow", translation: "ток-шоуто", category: "noun", gender: "die", sentence_de: "In der Talkshow diskutieren Prominente.", sentence_mk: "Во ток-шоуто дискутираат познати личности.", image: "🎙️" },
  { word: "die Werbung", translation: "рекламата", category: "noun", gender: "die", sentence_de: "Die Werbung unterbricht den Film.", sentence_mk: "Рекламата го прекинува филмот.", image: "📺" },
  { word: "fernsehen", translation: "гледа телевизија", category: "verb", sentence_de: "Ich sehe abends gern fern.", sentence_mk: "Сакам да гледам телевизија навечер.", image: "📺" },
  { word: "einschalten", translation: "вклучува (ТВ/радио)", category: "verb", sentence_de: "Ich schalte den Fernseher ein.", sentence_mk: "Го вклучувам телевизорот.", image: "🔛" },
  { word: "ausschalten", translation: "исклучува", category: "verb", sentence_de: "Ich schalte den Fernseher aus.", sentence_mk: "Го исклучувам телевизорот.", image: "🔚" },
  { word: "veröffentlichen", translation: "објавува", category: "verb", sentence_de: "Die Zeitung veröffentlicht einen Artikel.", sentence_mk: "Весникот објавува статија.", image: "📰" },

  // ПОЛИТИКА (POLITICS)
  { word: "die Politik", translation: "политиката", category: "noun", gender: "die", sentence_de: "Politik interessiert mich.", sentence_mk: "Политиката ме интересира.", image: "🏛️" },
  { word: "der Politiker", translation: "политичарот", category: "noun", gender: "der", sentence_de: "Der Politiker hält eine Rede.", sentence_mk: "Политичарот држи говор.", image: "🎙️" },
  { word: "die Partei", translation: "партијата", category: "noun", gender: "die", sentence_de: "Welche Partei wählst du?", sentence_mk: "Која партија ја гласаш?", image: "🗳️" },
  { word: "die Wahl", translation: "изборите", category: "noun", gender: "die", sentence_de: "Die Wahl ist im September.", sentence_mk: "Изборите се во септември.", image: "🗳️" },
  { word: "wählen", translation: "гласа/избира", category: "verb", sentence_de: "Ich wähle den Kandidaten.", sentence_mk: "Го гласам кандидатот.", image: "✅" },
  { word: "der Wähler", translation: "гласачот", category: "noun", gender: "der", sentence_de: "Die Wähler gehen zur Wahl.", sentence_mk: "Гласачите одат на избори.", image: "🗳️" },
  { word: "die Stimme", translation: "гласот", category: "noun", gender: "die", sentence_de: "Er bekommt viele Stimmen.", sentence_mk: "Тој добива многу гласови.", image: "🗳️" },
  { word: "der Kanzler", translation: "канцеларот", category: "noun", gender: "der", sentence_de: "Der Bundeskanzler regiert das Land.", sentence_mk: "Сојузниот канцелар ја води државата.", image: "👔" },
  { word: "der Präsident", translation: "претседателот", category: "noun", gender: "der", sentence_de: "Der Präsident besucht Deutschland.", sentence_mk: "Претседателот ја посетува Германија.", image: "👔" },
  { word: "das Parlament", translation: "парламентот", category: "noun", gender: "das", sentence_de: "Das Parlament debattiert.", sentence_mk: "Парламентот дебатира.", image: "🏛️" },
  { word: "der Bundestag", translation: "Бундестагот", category: "noun", gender: "der", sentence_de: "Der Bundestag tagt in Berlin.", sentence_mk: "Бундестагот заседава во Берлин.", image: "🏛️" },
  { word: "die Regierung", translation: "владата", category: "noun", gender: "die", sentence_de: "Die Regierung beschließt ein Gesetz.", sentence_mk: "Владата донесува закон.", image: "📜" },
  { word: "die Opposition", translation: "опозицијата", category: "noun", gender: "die", sentence_de: "Die Opposition kritisiert die Regierung.", sentence_mk: "Опозицијата ја критикува владата.", image: "🗣️" },
  { word: "das Gesetz", translation: "законот", category: "noun", gender: "das", sentence_de: "Das neue Gesetz tritt in Kraft.", sentence_mk: "Новиот закон стапува на сила.", image: "📜" },
  { word: "die Demokratie", translation: "демократијата", category: "noun", gender: "die", sentence_de: "Deutschland ist eine Demokratie.", sentence_mk: "Германија е демократија.", image: "🗽" },
  { word: "die Diktatur", translation: "диктатурата", category: "noun", gender: "die", sentence_de: "Die Diktatur ist unfrei.", sentence_mk: "Диктатурата е неслободна.", image: "⛓️" },
  { word: "die Freiheit", translation: "слободата", category: "noun", gender: "die", sentence_de: "Die Freiheit der Presse ist wichtig.", sentence_mk: "Слободата на печатот е важна.", image: "🕊️" },
  { word: "die Menschenrechte", translation: "човековите права", category: "noun", sentence_de: "Die Menschenrechte gelten für alle.", sentence_mk: "Човековите права важат за сите.", image: "⚖️" },
  { word: "die Gleichberechtigung", translation: "еднаквоста", category: "noun", gender: "die", sentence_de: "Frauen kämpfen für Gleichberechtigung.", sentence_mk: "Жените се борат за еднаквост.", image: "♀️" },

  // ОКОЛИНА (ENVIRONMENT)
  { word: "die Umwelt", translation: "животната средина", category: "noun", gender: "die", sentence_de: "Wir müssen die Umwelt schützen.", sentence_mk: "Мораме да ја заштитиме животната средина.", image: "🌍" },
  { word: "der Umweltschutz", translation: "заштитата на околината", category: "noun", gender: "der", sentence_de: "Umweltschutz ist wichtig.", sentence_mk: "Заштитата на околината е важна.", image: "🌱" },
  { word: "die Klimaänderung", translation: "климатската промена", category: "noun", gender: "die", sentence_de: "Die Klimaänderung ist gefährlich.", sentence_mk: "Климатската промена е опасна.", image: "🌡️" },
  { word: "der Klimawandel", translation: "климатските промени", category: "noun", gender: "der", sentence_de: "Der Klimawandel betrifft uns alle.", sentence_mk: "Климатските промени не засегаат сите.", image: "🌍" },
  { word: "die Erderwärmung", translation: "затоплувањето", category: "noun", gender: "die", sentence_de: "Die Erderwärmung schreitet voran.", sentence_mk: "Затоплувањето напредува.", image: "🔥" },
  { word: "der Treibhauseffekt", translation: "ефектот на стаклена градина", category: "noun", gender: "der", sentence_de: "Der Treibhauseffekt erwärmt die Erde.", sentence_mk: "Ефектот на стаклена градина ја загрева земјата.", image: "🌍" },
  { word: "das Ozonloch", translation: "озонската дупка", category: "noun", gender: "das", sentence_de: "Das Ozonloch wird kleiner.", sentence_mk: "Озонската дупка станува помала.", image: "🕳️" },
  { word: "die Luftverschmutzung", translation: "загадувањето на воздухот", category: "noun", gender: "die", sentence_de: "Die Luftverschmutzung ist hoch.", sentence_mk: "Загадувањето на воздухот е високо.", image: "💨" },
  { word: "die erneuerbare Energie", translation: "обновливата енергија", category: "noun", gender: "die", sentence_de: "Erneuerbare Energien sind wichtig.", sentence_mk: "Обновливите енергии се важни.", image: "☀️" },
  { word: "die Solarenergie", translation: "сончевата енергија", category: "noun", gender: "die", sentence_de: "Solarenergie kommt von der Sonne.", sentence_mk: "Сончевата енергија доаѓа од сонцето.", image: "☀️" },
  { word: "die Windenergie", translation: "енергијата од ветер", category: "noun", gender: "die", sentence_de: "Windenergie ist sauber.", sentence_mk: "Енергијата од ветер е чиста.", image: "💨" },
  { word: "die Wasserkraft", translation: "хидроенергијата", category: "noun", gender: "die", sentence_de: "Wasserkraft produziert Strom.", sentence_mk: "Хидроенергијата произведува струја.", image: "🌊" },
  { word: "der Müll", translation: "ѓубрето", category: "noun", gender: "der", sentence_de: "Der Müll muss getrennt werden.", sentence_mk: "Ѓубрето мора да се одвојува.", image: "🗑️" },
  { word: "die Mülltrennung", translation: "одвојувањето на ѓубре", category: "noun", gender: "die", sentence_de: "Mülltrennung ist wichtig für die Umwelt.", sentence_mk: "Одвојувањето на ѓубре е важно за околината.", image: "♻️" },
  { word: "der Plastikmüll", translation: "пластичниот отпад", category: "noun", gender: "der", sentence_de: "Plastikmüll verschmutzt die Meere.", sentence_mk: "Пластичниот отпад ги загадува морињата.", image: "🥤" },
  { word: "das Recycling", translation: "рециклирањето", category: "noun", gender: "das", sentence_de: "Recycling schont die Umwelt.", sentence_mk: "Рециклирањето ја штеди околината.", image: "♻️" },
  { word: "die Umweltverschmutzung", translation: "загадувањето на околината", category: "noun", gender: "die", sentence_de: "Die Umweltverschmutzung nimmt zu.", sentence_mk: "Загадувањето на околината се зголемува.", image: "🏭" },
  { word: "der Umweltschützer", translation: "еколошкиот активист", category: "noun", gender: "der", sentence_de: "Umweltschützer demonstrieren.", sentence_mk: "Еколошките активисти демонстрираат.", image: "🌱" },
  { word: "nachhaltig", translation: "одржлив", category: "adjective", sentence_de: "Nachhaltige Entwicklung ist wichtig.", sentence_mk: "Одржливиот развој е важен.", image: "🌱" },
  { word: "ökologisch", translation: "еколошки", category: "adjective", sentence_de: "Ökologische Produkte sind besser.", sentence_mk: "Еколошките производи се подобри.", image: "🌿" },
  { word: "recyceln", translation: "рециклира", category: "verb", sentence_de: "Wir recyceln Papier und Glas.", sentence_mk: "Рециклираме хартија и стакло.", image: "♻️" },
  { word: "verschmutzen", translation: "загадува", category: "verb", sentence_de: "Fabriken verschmutzen die Luft.", sentence_mk: "Фабриките го загадуваат воздухот.", image: "🏭" },
  { word: "schützen", translation: "заштитува", category: "verb", sentence_de: "Wir müssen die Tiere schützen.", sentence_mk: "Мораме да ги заштитиме животните.", image: "🛡️" },

  // ТЕХНОЛОГИЈА (TECHNOLOGY)
  { word: "die Technologie", translation: "технологијата", category: "noun", gender: "die", sentence_de: "Die Technologie entwickelt sich schnell.", sentence_mk: "Технологијата се развива брзо.", image: "💻" },
  { word: "die Digitalisierung", translation: "дигитализацијата", category: "noun", gender: "die", sentence_de: "Die Digitalisierung verändert die Arbeitswelt.", sentence_mk: "Дигитализацијата го менува светот на работа.", image: "💿" },
  { word: "das Internet", translation: "интернетот", category: "noun", gender: "das", sentence_de: "Das Internet ist überall.", sentence_mk: "Интернетот е насекаде.", image: "🌐" },
  { word: "das WLAN", translation: "вај-фај мрежата", category: "noun", gender: "das", sentence_de: "Das WLAN ist kostenlos.", sentence_mk: "Вај-фај мрежата е бесплатна.", image: "📶" },
  { word: "der Router", translation: "рутерот", category: "noun", gender: "der", sentence_de: "Der Router verteilt das Internet.", sentence_mk: "Рутерот го дистрибуира интернетот.", image: "📶" },
  { word: "die Daten", translation: "податоците", category: "noun", sentence_de: "Die Daten sind gespeichert.", sentence_mk: "Податоците се зачувани.", image: "💾" },
  { word: "der Datenschutz", translation: "заштитата на податоци", category: "noun", gender: "der", sentence_de: "Datenschutz ist wichtig.", sentence_mk: "Заштитата на податоци е важна.", image: "🔒" },
  { word: "die Cloud", translation: "облакот (складирање)", category: "noun", gender: "die", sentence_de: "Meine Fotos sind in der Cloud.", sentence_mk: "Моите фотографии се во облак.", image: "☁️" },
  { word: "die Software", translation: "софтверот", category: "noun", gender: "die", sentence_de: "Die Software ist neu.", sentence_mk: "Софтверот е нов.", image: "💿" },
  { word: "die Hardware", translation: "хардверот", category: "noun", gender: "die", sentence_de: "Die Hardware ist kaputt.", sentence_mk: "Хардверот е расипан.", image: "🖥️" },
  { word: "das Passwort", translation: "лозинката", category: "noun", gender: "das", sentence_de: "Mein Passwort ist geheim.", sentence_mk: "Мојата лозинка е тајна.", image: "🔑" },
  { word: "der Benutzername", translation: "корисничкото име", category: "noun", gender: "der", sentence_de: "Gib deinen Benutzernamen ein.", sentence_mk: "Внеси го твоето корисничко име.", image: "👤" },
  { word: "sich anmelden", translation: "се најавува", category: "verb", sentence_de: "Ich melde mich im System an.", sentence_mk: "Се најавувам во системот.", image: "🔑" },
  { word: "sich abmelden", translation: "се одјавува", category: "verb", sentence_de: "Ich melde mich ab.", sentence_mk: "Се одјавувам.", image: "🔚" },
  { word: "hochladen", translation: "прикачува", category: "verb", sentence_de: "Ich lade ein Foto hoch.", sentence_mk: "Прикачувам фотографија.", image: "⬆️" },
  { word: "herunterladen", translation: "презема", category: "verb", sentence_de: "Ich lade Musik herunter.", sentence_mk: "Преземам музика.", image: "⬇️" },
  { word: "aktualisieren", translation: "ажурира", category: "verb", sentence_de: "Ich aktualisiere die App.", sentence_mk: "Ја ажурирам апликацијата.", image: "🔄" },
  { word: "installieren", translation: "инсталира", category: "verb", sentence_de: "Ich installiere ein neues Programm.", sentence_mk: "Инсталирам нова програма.", image: "💿" },
  { word: "deinstallieren", translation: "деинсталира", category: "verb", sentence_de: "Ich deinstalliere die App.", sentence_mk: "Ја деинсталирам апликацијата.", image: "🗑️" },
  { word: "programmieren", translation: "програмира", category: "verb", sentence_de: "Er programmiert eine Website.", sentence_mk: "Тој програмира веб-страница.", image: "👨‍💻" },
  { word: "der Bildschirm", translation: "екранот", category: "noun", gender: "der", sentence_de: "Der Bildschirm ist groß.", sentence_mk: "Екранот е голем.", image: "🖥️" },
  { word: "die Tastatur", translation: "тастатурата", category: "noun", gender: "die", sentence_de: "Die Tastatur ist deutsch.", sentence_mk: "Тастатурата е германска.", image: "⌨️" },
  { word: "die Maus", translation: "глувчето", category: "noun", gender: "die", sentence_de: "Die Maus funktioniert nicht.", sentence_mk: "Глувчето не работи.", image: "🖱️" },
  { word: "der Drucker", translation: "печатачот", category: "noun", gender: "der", sentence_de: "Der Drucker hat kein Papier.", sentence_mk: "Печатачот нема хартија.", image: "🖨️" },
  { word: "der Scanner", translation: "скенерот", category: "noun", gender: "der", sentence_de: "Ich scanne das Dokument.", sentence_mk: "Го скенирам документот.", image: "📠" },

  // ПСИХОЛОГИЈА (PSYCHOLOGY)
  { word: "die Psyche", translation: "психата", category: "noun", gender: "die", sentence_de: "Die Psyche ist komplex.", sentence_mk: "Психата е сложена.", image: "🧠" },
  { word: "die Psychologie", translation: "психологијата", category: "noun", gender: "die", sentence_de: "Psychologie studieren ist interessant.", sentence_mk: "Да се студира психологија е интересно.", image: "🧠" },
  { word: "der Psychologe", translation: "психологот (маж)", category: "noun", gender: "der", sentence_de: "Der Psychologe hilft seinen Patienten.", sentence_mk: "Психологот им помага на своите пациенти.", image: "👨‍⚕️" },
  { word: "die Psychologin", translation: "психологистката (жена)", category: "noun", gender: "die", sentence_de: "Die Psychologin gibt Ratschläge.", sentence_mk: "Психологистката дава совети.", image: "👩‍⚕️" },
  { word: "das Verhalten", translation: "однесувањето", category: "noun", gender: "das", sentence_de: "Sein Verhalten ist seltsam.", sentence_mk: "Неговото однесување е чудно.", image: "🤔" },
  { word: "die Persönlichkeit", translation: "личноста", category: "noun", gender: "die", sentence_de: "Sie hat eine starke Persönlichkeit.", sentence_mk: "Таа има силна личност.", image: "👤" },
  { word: "der Charakter", translation: "карактерот", category: "noun", gender: "der", sentence_de: "Sein Charakter ist kompliziert.", sentence_mk: "Неговиот карактер е комплициран.", image: "🧩" },
  { word: "die Eigenschaft", translation: "особината", category: "noun", gender: "die", sentence_de: "Geduld ist eine gute Eigenschaft.", sentence_mk: "Трпеливоста е добра особина.", image: "⭐" },
  { word: "die Emotion", translation: "емоцијата", category: "noun", gender: "die", sentence_de: "Emotionen sind schwer zu kontrollieren.", sentence_mk: "Емоциите се тешки за контролирање.", image: "😊" },
  { word: "das Gefühl", translation: "чувството", category: "noun", gender: "das", sentence_de: "Ich habe ein komisches Gefühl.", sentence_mk: "Имам чудно чувство.", image: "💭" },
  { word: "die Stimmung", translation: "расположението", category: "noun", gender: "die", sentence_de: "Die Stimmung ist gut.", sentence_mk: "Расположението е добро.", image: "😊" },
  { word: "die Laune", translation: "расположението", category: "noun", gender: "die", sentence_de: "Er hat schlechte Laune.", sentence_mk: "Тој има лошо расположение.", image: "😠" },
  { word: "der Stress", translation: "стресот", category: "noun", gender: "der", sentence_de: "Stress ist ungesund.", sentence_mk: "Стресот е нездрав.", image: "😫" },
  { word: "die Angst", translation: "стравот", category: "noun", gender: "die", sentence_de: "Die Angst ist groß.", sentence_mk: "Стравот е голем.", image: "😨" },
  { word: "die Depression", translation: "депресијата", category: "noun", gender: "die", sentence_de: "Depression ist eine ernste Krankheit.", sentence_mk: "Депресијата е сериозна болест.", image: "😔" },
  { word: "die Trauer", translation: "тагата", category: "noun", gender: "die", sentence_de: "Die Trauer ist tief.", sentence_mk: "Тагата е длабока.", image: "😢" },
  { word: "die Freude", translation: "радоста", category: "noun", gender: "die", sentence_de: "Die Freude ist groß.", sentence_mk: "Радоста е голема.", image: "😊" },
  { word: "die Liebe", translation: "љубовта", category: "noun", gender: "die", sentence_de: "Die Liebe macht glücklich.", sentence_mk: "Љубовта прави среќа.", image: "❤️" },
  { word: "der Hass", translation: "омразата", category: "noun", gender: "der", sentence_de: "Hass ist ein starkes Gefühl.", sentence_mk: "Омразата е силно чувство.", image: "😠" },
  { word: "die Zufriedenheit", translation: "задоволството", category: "noun", gender: "die", sentence_de: "Zufriedenheit ist wichtig.", sentence_mk: "Задоволството е важно.", image: "😊" },
  { word: "das Selbstbewusstsein", translation: "самодовербата", category: "noun", gender: "das", sentence_de: "Selbstbewusstsein ist gut.", sentence_mk: "Самодовербата е добра.", image: "💪" },
  { word: "das Selbstwertgefühl", translation: "чувството на сопствена вредност", category: "noun", gender: "das", sentence_de: "Ein gesundes Selbstwertgefühl ist wichtig.", sentence_mk: "Здравото чувство на сопствена вредност е важно.", image: "🌟" },
  { word: "die Entwicklung", translation: "развојот", category: "noun", gender: "die", sentence_de: "Die Entwicklung des Kindes ist normal.", sentence_mk: "Развојот на детето е нормален.", image: "🌱" },
  { word: "die Phase", translation: "фазата", category: "noun", gender: "die", sentence_de: "Das Kind ist in einer schwierigen Phase.", sentence_mk: "Детето е во тешка фаза.", image: "⏳" },
  { word: "die Krise", translation: "кризата", category: "noun", gender: "die", sentence_de: "Die Krise überwinden wir gemeinsam.", sentence_mk: "Кризата ја надминуваме заедно.", image: "⚠️" },

  // КРИМИНАЛИТЕТ (CRIME)
  { word: "das Verbrechen", translation: "злосторството", category: "noun", gender: "das", sentence_de: "Das Verbrechen wurde aufgeklärt.", sentence_mk: "Злосторството е расчистено.", image: "🔪" },
  { word: "der Verbrecher", translation: "злосторникот", category: "noun", gender: "der", sentence_de: "Der Verbrecher wurde verhaftet.", sentence_mk: "Злосторникот е уапсен.", image: "👮" },
  { word: "die Straftat", translation: "кривичното дело", category: "noun", gender: "die", sentence_de: "Die Straftat ist schwer.", sentence_mk: "Кривичното дело е тешко.", image: "⚖️" },
  { word: "der Diebstahl", translation: "кражбата", category: "noun", gender: "der", sentence_de: "Der Diebstahl wurde gemeldet.", sentence_mk: "Кражбата е пријавена.", image: "💰" },
  { word: "der Einbruch", translation: "провалата", category: "noun", gender: "der", sentence_de: "Der Einbruch war nachts.", sentence_mk: "Провалата беше ноќе.", image: "🔨" },
  { word: "der Raub", translation: "ограбувањето", category: "noun", gender: "der", sentence_de: "Der Raub fand in der Bank statt.", sentence_mk: "Ограбувањето се случи во банката.", image: "🏦" },
  { word: "der Mord", translation: "убиството", category: "noun", gender: "der", sentence_de: "Der Mord ist schrecklich.", sentence_mk: "Убиството е страшно.", image: "🔪" },
  { word: "der Totschlag", translation: "убиството (непреднамерно)", category: "noun", gender: "der", sentence_de: "Totschlag wird anders bestraft als Mord.", sentence_mk: "Непреднамерното убиство се казнува поинаку од убиството.", image: "⚖️" },
  { word: "die Polizei", translation: "полицијата", category: "noun", gender: "die", sentence_de: "Die Polizei sucht den Täter.", sentence_mk: "Полицијата го бара сторителот.", image: "👮" },
  { word: "der Polizist", translation: "полицаецот", category: "noun", gender: "der", sentence_de: "Der Polizist regelt den Verkehr.", sentence_mk: "Полицаецот го регулира сообраќајот.", image: "👮" },
  { word: "der Täter", translation: "сторителот", category: "noun", gender: "der", sentence_de: "Der Täter wurde gefasst.", sentence_mk: "Сторителот е фатен.", image: "🕵️" },
  { word: "das Opfer", translation: "жртвата", category: "noun", gender: "das", sentence_de: "Das Opfer ist verletzt.", sentence_mk: "Жртвата е повредена.", image: "😢" },
  { word: "der Zeuge", translation: "сведокот", category: "noun", gender: "der", sentence_de: "Der Zeuge sagt vor Gericht aus.", sentence_mk: "Сведокот сведочи на суд.", image: "👁️" },
  { word: "die Zeugin", translation: "сведокот (жена)", category: "noun", gender: "die", sentence_de: "Die Zeugin hat alles gesehen.", sentence_mk: "Сведокот (жена) виде сè.", image: "👁️" },
  { word: "der Verdächtige", translation: "осомничениот", category: "noun", gender: "der", sentence_de: "Der Verdächtige schweigt.", sentence_mk: "Осомничениот молчи.", image: "🤐" },
  { word: "das Alibi", translation: "алибито", category: "noun", gender: "das", sentence_de: "Sein Alibi ist wasserdicht.", sentence_mk: "Неговото алиби е водонепропустливо.", image: "⏰" },
  { word: "das Gericht", translation: "судот", category: "noun", gender: "das", sentence_de: "Das Gericht verkündet das Urteil.", sentence_mk: "Судот ја објавува пресудата.", image: "⚖️" },
  { word: "der Richter", translation: "судијата (маж)", category: "noun", gender: "der", sentence_de: "Der Richter spricht das Urteil.", sentence_mk: "Судијата ја изрекува пресудата.", image: "⚖️" },
  { word: "die Richterin", translation: "судијката (жена)", category: "noun", gender: "die", sentence_de: "Die Richterin ist streng.", sentence_mk: "Судијката е строга.", image: "⚖️" },
  { word: "der Anwalt", translation: "адвокатот", category: "noun", gender: "der", sentence_de: "Der Anwalt verteidigt den Angeklagten.", sentence_mk: "Адвокатот го брани обвинетиот.", image: "⚖️" },
  { word: "die Anwältin", translation: "адвокатката", category: "noun", gender: "die", sentence_de: "Die Anwältin plädiert auf unschuldig.", sentence_mk: "Адвокатката тврди дека е невин.", image: "⚖️" },
  { word: "der Staatsanwalt", translation: "јавниот обвинител", category: "noun", gender: "der", sentence_de: "Der Staatsanwalt erhebt Anklage.", sentence_mk: "Јавниот обвинител подигнува обвинение.", image: "⚖️" },
  { word: "das Gefängnis", translation: "затворот", category: "noun", gender: "das", sentence_de: "Der Verbrecher sitzt im Gefängnis.", sentence_mk: "Злосторникот е во затвор.", image: "🔒" },
  { word: "die Strafe", translation: "казната", category: "noun", gender: "die", sentence_de: "Die Strafe ist gerecht.", sentence_mk: "Казната е праведна.", image: "⚖️" },
  { word: "die Geldstrafe", translation: "паричната казна", category: "noun", gender: "die", sentence_de: "Er muss eine Geldstrafe zahlen.", sentence_mk: "Тој мора да плати парична казна.", image: "💰" },
  { word: "die Freiheitsstrafe", translation: "затворската казна", category: "noun", gender: "die", sentence_de: "Die Freiheitsstrafe beträgt zwei Jahre.", sentence_mk: "Затворската казна изнесува две години.", image: "🔒" },
  { word: "das Urteil", translation: "пресудата", category: "noun", gender: "das", sentence_de: "Das Urteil wird morgen gesprochen.", sentence_mk: "Пресудата ќе биде изречена утре.", image: "⚖️" },
  { word: "verhaften", translation: "апси", category: "verb", sentence_de: "Die Polizei verhaftet den Täter.", sentence_mk: "Полицијата го апси сторителот.", image: "👮" },
  { word: "verurteilen", translation: "осудува", category: "verb", sentence_de: "Das Gericht verurteilt den Angeklagten.", sentence_mk: "Судот го осудува обвинетиот.", image: "⚖️" },
  { word: "freisprechen", translation: "ослободува од обвинение", category: "verb", sentence_de: "Der Richter spricht den Angeklagten frei.", sentence_mk: "Судијата го ослободува обвинетиот.", image: "✅" },

  // КУЛТУРА (CULTURE)
  { word: "die Kultur", translation: "културата", category: "noun", gender: "die", sentence_de: "Die deutsche Kultur ist vielfältig.", sentence_mk: "Германската култура е разновидна.", image: "🎭" },
  { word: "die Tradition", translation: "традицијата", category: "noun", gender: "die", sentence_de: "Traditionen sind wichtig.", sentence_mk: "Традициите се важни.", image: "📜" },
  { word: "der Brauch", translation: "обичајот", category: "noun", gender: "der", sentence_de: "Das ist ein alter Brauch.", sentence_mk: "Тоа е стар обичај.", image: "🎊" },
  { word: "das Fest", translation: "празникот", category: "noun", gender: "das", sentence_de: "Das Fest dauert drei Tage.", sentence_mk: "Празникот трае три дена.", image: "🎉" },
  { word: "der Feiertag", translation: "празничниот ден", category: "noun", gender: "der", sentence_de: "Morgen ist ein Feiertag.", sentence_mk: "Утре е празничен ден.", image: "📅" },
  { word: "das Oktoberfest", translation: "Октоберфест", category: "noun", gender: "das", sentence_de: "Das Oktoberfest ist in München.", sentence_mk: "Октоберфест е во Минхен.", image: "🍺" },
  { word: "der Karneval", translation: "карневалот", category: "noun", gender: "der", sentence_de: "In Köln ist Karneval sehr beliebt.", sentence_mk: "Во Келн карневалот е многу популарен.", image: "🎭" },
  { word: "Weihnachten", translation: "Божиќ", category: "noun", gender: "das", sentence_de: "Weihnachten ist ein Familienfest.", sentence_mk: "Божиќ е семеен празник.", image: "🎄" },
  { word: "Ostern", translation: "Велигден", category: "noun", gender: "das", sentence_de: "Zu Ostern bemalen wir Eier.", sentence_mk: "За Велигден боиме јајца.", image: "🐣" },
  { word: "der Nikolaustag", translation: "Николаевден", category: "noun", gender: "der", sentence_de: "Am Nikolaustag bekommen Kinder Süßigkeiten.", sentence_mk: "За Николаевден децата добиваат слатки.", image: "🎅" },
  { word: "die Volksmusik", translation: "народната музика", category: "noun", gender: "die", sentence_de: "Volksmusik höre ich gern.", sentence_mk: "Сакам да слушам народна музика.", image: "🎵" },
  { word: "das Volkslied", translation: "народната песна", category: "noun", gender: "das", sentence_de: "Das ist ein bekanntes Volkslied.", sentence_mk: "Тоа е позната народна песна.", image: "🎤" },
  { word: "der Volkstanz", translation: "народниот танц", category: "noun", gender: "der", sentence_de: "Volkstänze werden traditionell getanzt.", sentence_mk: "Народните танци се играат традиционално.", image: "💃" },
  { word: "die Tracht", translation: "народната носија", category: "noun", gender: "die", sentence_de: "In Bayern tragen viele Tracht.", sentence_mk: "Во Баварија многумина носат народна носија.", image: "👗" },
  { word: "das Dirndl", translation: "дирндл (женска носија)", category: "noun", gender: "das", sentence_de: "Das Dirndl ist typisch bayerisch.", sentence_mk: "Дирндлот е типично баварски.", image: "👗" },
  { word: "die Lederhose", translation: "кожените панталони", category: "noun", gender: "die", sentence_de: "Die Lederhose trägt der Mann.", sentence_mk: "Мажот носи кожени панталони.", image: "🩳" },
  { word: "die Literatur", translation: "литературата", category: "noun", gender: "die", sentence_de: "Deutsche Literatur ist weltbekannt.", sentence_mk: "Германската литература е светски позната.", image: "📚" },
  { word: "der Schriftsteller", translation: "писателот", category: "noun", gender: "der", sentence_de: "Dieser Schriftsteller schreibt Romane.", sentence_mk: "Овој писател пишува романи.", image: "✍️" },
  { word: "der Dichter", translation: "поетот", category: "noun", gender: "der", sentence_de: "Goethe ist ein berühmter Dichter.", sentence_mk: "Гете е познат поет.", image: "📜" },
  { word: "das Gedicht", translation: "песната (поезија)", category: "noun", gender: "das", sentence_de: "Das Gedicht ist sehr romantisch.", sentence_mk: "Песната е многу романтична.", image: "📝" },
  { word: "der Roman", translation: "романот", category: "noun", gender: "der", sentence_de: "Der Roman hat 500 Seiten.", sentence_mk: "Романот има 500 страници.", image: "📖" },
  { word: "die Kurzgeschichte", translation: "расказот", category: "noun", gender: "die", sentence_de: "Die Kurzgeschichte ist spannend.", sentence_mk: "Расказот е возбудлив.", image: "📘" },
  { word: "das Theater", translation: "театарот", category: "noun", gender: "das", sentence_de: "Das Theater spielt ein Drama.", sentence_mk: "Театарот игра драма.", image: "🎭" },
  { word: "das Schauspiel", translation: "драмата", category: "noun", gender: "das", sentence_de: "Das Schauspiel war ergreifend.", sentence_mk: "Драмата беше трогателна.", image: "🎭" },
  { word: "die Oper", translation: "операта", category: "noun", gender: "die", sentence_de: "Die Oper ist ausverkauft.", sentence_mk: "Операта е распродадена.", image: "🎭" },
  { word: "das Ballett", translation: "балетот", category: "noun", gender: "das", sentence_de: "Das Ballett tanzt wunderbar.", sentence_mk: "Балетот танцува прекрасно.", image: "🩰" },
  { word: "das Orchester", translation: "оркестарот", category: "noun", gender: "das", sentence_de: "Das Orchester spielt klassische Musik.", sentence_mk: "Оркестарот свири класична музика.", image: "🎻" },
  { word: "die Ausstellung", translation: "изложбата", category: "noun", gender: "die", sentence_de: "Die Ausstellung zeigt moderne Kunst.", sentence_mk: "Изложбата покажува модерна уметност.", image: "🖼️" },
  { word: "das Museum", translation: "музејот", category: "noun", gender: "das", sentence_de: "Das Museum ist sehr interessant.", sentence_mk: "Музејот е многу интересен.", image: "🏛️" },
  { word: "die Galerie", translation: "галеријата", category: "noun", gender: "die", sentence_de: "Die Galerie zeigt Bilder.", sentence_mk: "Галеријата покажува слики.", image: "🖼️" },
  { word: "die Malerei", translation: "сликарството", category: "noun", gender: "die", sentence_de: "Die Malerei ist ihre Leidenschaft.", sentence_mk: "Сликарството е нејзината страст.", image: "🎨" },
  { word: "die Bildhauerei", translation: "вајарството", category: "noun", gender: "die", sentence_de: "Die Bildhauerei ist eine alte Kunst.", sentence_mk: "Вајарството е стара уметност.", image: "🗿" },
  { word: "die Skulptur", translation: "скулптурата", category: "noun", gender: "die", sentence_de: "Die Skulptur steht im Park.", sentence_mk: "Скулптурата стои во паркот.", image: "🗿" },

  // ФИЛОЗОФИЈА (PHILOSOPHY)
  { word: "die Philosophie", translation: "филозофијата", category: "noun", gender: "die", sentence_de: "Philosophie ist die Liebe zur Weisheit.", sentence_mk: "Филозофијата е љубов кон мудроста.", image: "🧠" },
  { word: "der Philosoph", translation: "филозофот", category: "noun", gender: "der", sentence_de: "Der Philosoph denkt über das Leben nach.", sentence_mk: "Филозофот размислува за животот.", image: "👨‍🎓" },
  { word: "die Philosophin", translation: "филозофката", category: "noun", gender: "die", sentence_de: "Die Philosophin schreibt ein Buch.", sentence_mk: "Филозофката пишува книга.", image: "👩‍🎓" },
  { word: "die Weisheit", translation: "мудроста", category: "noun", gender: "die", sentence_de: "Weisheit kommt mit dem Alter.", sentence_mk: "Мудроста доаѓа со возраста.", image: "🦉" },
  { word: "die Erkenntnis", translation: "спознанието", category: "noun", gender: "die", sentence_de: "Die Erkenntnis ist wichtig.", sentence_mk: "Спознанието е важно.", image: "💡" },
  { word: "die Wahrheit", translation: "вистината", category: "noun", gender: "die", sentence_de: "Die Wahrheit ist nicht immer angenehm.", sentence_mk: "Вистината не е секогаш пријатна.", image: "⚖️" },
  { word: "die Lüge", translation: "лагата", category: "noun", gender: "die", sentence_de: "Die Lüge fliegt auf.", sentence_mk: "Лагата излегува на виделина.", image: "🤥" },
  { word: "das Bewusstsein", translation: "свеста", category: "noun", gender: "das", sentence_de: "Das Bewusstsein ist ein Rätsel.", sentence_mk: "Свеста е загатка.", image: "🧠" },
  { word: "das Unterbewusstsein", translation: "подсвеста", category: "noun", gender: "das", sentence_de: "Das Unterbewusstsein steuert vieles.", sentence_mk: "Подсвеста контролира многу нешта.", image: "🌊" },
  { word: "die Seele", translation: "душата", category: "noun", gender: "die", sentence_de: "Die Seele ist unsterblich.", sentence_mk: "Душата е бесмртна.", image: "👻" },
  { word: "der Geist", translation: "духот/умот", category: "noun", gender: "der", sentence_de: "Der Geist ist schnell.", sentence_mk: "Умот е брз.", image: "💭" },
  { word: "der Körper", translation: "телото", category: "noun", gender: "der", sentence_de: "Der Körper braucht Bewegung.", sentence_mk: "Телото има потреба од движење.", image: "🏃" },
  { word: "das Denken", translation: "мислењето/размислувањето", category: "noun", gender: "das", sentence_de: "Das Denken macht den Menschen aus.", sentence_mk: "Размислувањето го дефинира човекот.", image: "💭" },
  { word: "der Gedanke", translation: "мислата", category: "noun", gender: "der", sentence_de: "Der Gedanke ist gut.", sentence_mk: "Мислата е добра.", image: "💡" },
  { word: "die Idee", translation: "идејата", category: "noun", gender: "die", sentence_de: "Die Idee ist genial.", sentence_mk: "Идејата е генијална.", image: "💡" },
  { word: "die Theorie", translation: "теоријата", category: "noun", gender: "die", sentence_de: "Die Theorie ist kompliziert.", sentence_mk: "Теоријата е комплицирана.", image: "📐" },
  { word: "die Praxis", translation: "праксата", category: "noun", gender: "die", sentence_de: "Die Praxis zeigt, ob es funktioniert.", sentence_mk: "Праксата покажува дали функционира.", image: "🔧" },
  { word: "die Ethik", translation: "етиката", category: "noun", gender: "die", sentence_de: "Ethik fragt nach dem guten Handeln.", sentence_mk: "Етиката прашува за доброто дејствување.", image: "⚖️" },
  { word: "die Moral", translation: "моралот", category: "noun", gender: "die", sentence_de: "Die Moral ist in der Gesellschaft wichtig.", sentence_mk: "Моралот е важен во општеството.", image: "⚖️" },
  { word: "das Gewissen", translation: "совеста", category: "noun", gender: "das", sentence_de: "Mein Gewissen ist rein.", sentence_mk: "Мојата совест е чиста.", image: "😇" },
  { word: "die Freiheit", translation: "слободата", category: "noun", gender: "die", sentence_de: "Freiheit ist ein hohes Gut.", sentence_mk: "Слободата е високо добро.", image: "🕊️" },
  { word: "die Gleichheit", translation: "еднаквоста", category: "noun", gender: "die", sentence_de: "Alle Menschen sind gleich.", sentence_mk: "Сите луѓе се еднакви.", image: "⚖️" },
  { word: "die Gerechtigkeit", translation: "правдата", category: "noun", gender: "die", sentence_de: "Wir kämpfen für Gerechtigkeit.", sentence_mk: "Се бориме за правда.", image: "⚖️" },
  { word: "das Böse", translation: "злото", category: "noun", gender: "das", sentence_de: "Das Böse existiert in der Welt.", sentence_mk: "Злото постои во светот.", image: "👿" },
  { word: "das Gute", translation: "доброто", category: "noun", gender: "das", sentence_de: "Das Gute siegt am Ende.", sentence_mk: "Доброто победува на крајот.", image: "😇" },
  { word: "der Sinn", translation: "смислата", category: "noun", gender: "der", sentence_de: "Was ist der Sinn des Lebens?", sentence_mk: "Која е смислата на животот?", image: "❓" },
  { word: "das Dasein", translation: "постоењето", category: "noun", gender: "das", sentence_de: "Das menschliche Dasein ist vergänglich.", sentence_mk: "Човечкото постоење е минливо.", image: "⏳" },
  { word: "die Existenz", translation: "егзистенцијата", category: "noun", gender: "die", sentence_de: "Die Existenz Gottes wird diskutiert.", sentence_mk: "Егзистенцијата на Бог се дискутира.", image: "❓" },
  { word: "der Glaube", translation: "верувањето", category: "noun", gender: "der", sentence_de: "Der Glaube kann Berge versetzen.", sentence_mk: "Верувањето може да поместува планини.", image: "🙏" },
  { word: "die Religion", translation: "религијата", category: "noun", gender: "die", sentence_de: "Viele Menschen haben eine Religion.", sentence_mk: "Многу луѓе имаат религија.", image: "⛪" },

  // ГЛАГОЛИ - НАПРЕДНО НИВО (ADVANCED VERBS)
  { word: "beeinflussen", translation: "влијае", category: "verb", sentence_de: "Die Medien beeinflussen die Meinung.", sentence_mk: "Медиумите влијаат на мислењето.", image: "📺" },
  { word: "entscheiden", translation: "одлучува", category: "verb", sentence_de: "Ich entscheide selbst.", sentence_mk: "Сам одлучувам.", image: "⚖️" },
  { word: "beschließen", translation: "одлучува (официјално)", category: "verb", sentence_de: "Das Parlament beschließt ein Gesetz.", sentence_mk: "Парламентот донесува закон.", image: "📜" },
  { word: "vermeiden", translation: "избегнува", category: "verb", sentence_de: "Ich vermeide Konflikte.", sentence_mk: "Избегнувам конфликти.", image: "🚫" },
  { word: "ertragen", translation: "поднесува", category: "verb", sentence_de: "Ich ertrage den Lärm nicht.", sentence_mk: "Не го поднесувам шумот.", image: "😖" },
  { word: "genießen", translation: "ужива", category: "verb", sentence_de: "Ich genieße das Leben.", sentence_mk: "Уживам во животот.", image: "😎" },
  { word: "leiden", translation: "страда", category: "verb", sentence_de: "Er leidet unter Schmerzen.", sentence_mk: "Тој страда од болки.", image: "😖" },
  { word: "bestehen", translation: "инсистира/постои", category: "verb", sentence_de: "Ich bestehe auf meinem Recht.", sentence_mk: "Инсистирам на моето право.", image: "⚖️" },
  { word: "bestehen aus", translation: "се состои од", category: "verb", sentence_de: "Das Buch besteht aus 10 Kapiteln.", sentence_mk: "Книгата се состои од 10 поглавја.", image: "📖" },
  { word: "auffallen", translation: "привлекува внимание", category: "verb", sentence_de: "Sie fällt durch ihr Kleid auf.", sentence_mk: "Таа привлекува внимание со својот фустан.", image: "👗" },
  { word: "aussehen", translation: "изгледа", category: "verb", sentence_de: "Du siehst gut aus.", sentence_mk: "Изгледаш добро.", image: "😊" },
  { word: "sich verhalten", translation: "се однесува", category: "verb", sentence_de: "Verhalte dich ruhig!", sentence_mk: "Однесувај се мирно!", image: "😌" },
  { word: "sich entwickeln", translation: "се развива", category: "verb", sentence_de: "Das Kind entwickelt sich gut.", sentence_mk: "Детето се развива добро.", image: "🌱" },
  { word: "sich gewöhnen an", translation: "се навикнува на", category: "verb", sentence_de: "Ich gewöhne mich an das Klima.", sentence_mk: "Се навикнувам на климата.", image: "🌡️" },
  { word: "sich entschuldigen", translation: "се извинува", category: "verb", sentence_de: "Ich entschuldige mich für den Fehler.", sentence_mk: "Се извинувам за грешката.", image: "🙏" },
  { word: "sich bedanken", translation: "се заблагодарува", category: "verb", sentence_de: "Ich bedanke mich für deine Hilfe.", sentence_mk: "Ти се заблагодарувам за помошта.", image: "🙏" },
  { word: "sich interessieren für", translation: "се интересира за", category: "verb", sentence_de: "Ich interessiere mich für Kunst.", sentence_mk: "Се интересирам за уметност.", image: "🎨" },
  { word: "sich kümmern um", translation: "се грижи за", category: "verb", sentence_de: "Ich kümmere mich um meine Oma.", sentence_mk: "Се грижам за баба ми.", image: "👵" },
  { word: "sich treffen mit", translation: "се среќава со", category: "verb", sentence_de: "Ich treffe mich mit Freunden.", sentence_mk: "Се среќавам со пријатели.", image: "👥" },
  { word: "sich unterhalten", translation: "разговара", category: "verb", sentence_de: "Wir unterhalten uns über Politik.", sentence_mk: "Разговараме за политика.", image: "🗣️" },
  { word: "sich beschweren", translation: "се жали", category: "verb", sentence_de: "Er beschwert sich über das Essen.", sentence_mk: "Тој се жали за храната.", image: "😤" },
  { word: "sich entspannen", translation: "се опушта", category: "verb", sentence_de: "Am Wochenende entspanne ich mich.", sentence_mk: "За викенд се опуштам.", image: "😌" },
  { word: "sich konzentrieren", translation: "се концентрира", category: "verb", sentence_de: "Ich muss mich konzentrieren.", sentence_mk: "Морам да се концентрирам.", image: "🧘" },
  { word: "sich erinnern an", translation: "се сеќава на", category: "verb", sentence_de: "Ich erinnere mich an dich.", sentence_mk: "Се сеќавам на тебе.", image: "🧠" },
  { word: "sich vorstellen", translation: "замислува/се претставува", category: "verb", sentence_de: "Ich kann mir das vorstellen.", sentence_mk: "Можам да си го замислам тоа.", image: "💭" },
  { word: "stattfinden", translation: "се одржува", category: "verb", sentence_de: "Das Konzert findet morgen statt.", sentence_mk: "Концертот се одржува утре.", image: "🎵" },
  { word: "teilnehmen", translation: "учествува", category: "verb", sentence_de: "Ich nehme am Kurs teil.", sentence_mk: "Учествувам на курсот.", image: "📚" },
  { word: "veranstalten", translation: "организира", category: "verb", sentence_de: "Die Schule veranstaltet ein Fest.", sentence_mk: "Училиштето организира прослава.", image: "🎉" },
  { word: "verpassen", translation: "пропушта", category: "verb", sentence_de: "Ich habe den Bus verpasst.", sentence_mk: "Го пропуштив автобусот.", image: "😔" },
  { word: "erreichen", translation: "постигнува/достигнува", category: "verb", sentence_de: "Ich habe mein Ziel erreicht.", sentence_mk: "Ја постигнав мојата цел.", image: "🎯" },
  { word: "erwarten", translation: "очекува", category: "verb", sentence_de: "Ich erwarte einen Anruf.", sentence_mk: "Очекувам повик.", image: "📞" },
  { word: "erfahren", translation: "дознава/искусува", category: "verb", sentence_de: "Ich habe Neuigkeiten erfahren.", sentence_mk: "Дознав новости.", image: "📰" },
  { word: "entdecken", translation: "открива", category: "verb", sentence_de: "Kolumbus entdeckte Amerika.", sentence_mk: "Колумбо ја откри Америка.", image: "🌍" },
  { word: "erfinden", translation: "измислува", category: "verb", sentence_de: "Edison erfand die Glühbirne.", sentence_mk: "Едисон ја измисли сијалицата.", image: "💡" },
  { word: "entwickeln", translation: "развива", category: "verb", sentence_de: "Die Firma entwickelt neue Produkte.", sentence_mk: "Фирмата развива нови производи.", image: "🔧" },
  { word: "erforschen", translation: "истражува", category: "verb", sentence_de: "Wissenschaftler erforschen das Universum.", sentence_mk: "Научниците го истражуваат универзумот.", image: "🔬" },
  { word: "untersuchen", translation: "испитува", category: "verb", sentence_de: "Der Arzt untersucht den Patienten.", sentence_mk: "Докторот го испитува пациентот.", image: "🩺" },
  { word: "prüfen", translation: "проверува", category: "verb", sentence_de: "Der Lehrer prüft die Hausaufgaben.", sentence_mk: "Учителот ги проверува домашните задачи.", image: "📝" },
  { word: "kontrollieren", translation: "контролира", category: "verb", sentence_de: "Die Polizei kontrolliert den Verkehr.", sentence_mk: "Полицијата го контролира сообраќајот.", image: "👮" },
  { word: "überprüfen", translation: "преиспитува", category: "verb", sentence_de: "Ich überprüfe die Daten.", sentence_mk: "Ги преиспитувам податоците.", image: "🔍" },
  { word: "bestätigen", translation: "потврдува", category: "verb", sentence_de: "Ich bestätige den Termin.", sentence_mk: "Го потврдувам терминот.", image: "✅" },
  { word: "widersprechen", translation: "противеречи", category: "verb", sentence_de: "Ich widerspreche dir.", sentence_mk: "Ти противречам.", image: "❌" },
  { word: "diskutieren", translation: "дискутира", category: "verb", sentence_de: "Wir diskutieren über Politik.", sentence_mk: "Дискутираме за политика.", image: "🗣️" },
  { word: "argumentieren", translation: "аргументира", category: "verb", sentence_de: "Er argumentiert gut.", sentence_mk: "Тој добро аргументира.", image: "🗣️" },
  { word: "überzeugen", translation: "убедува", category: "verb", sentence_de: "Ich überzeuge ihn.", sentence_mk: "Го убедувам.", image: "🤝" },
  { word: "zweifeln", translation: "се сомнева", category: "verb", sentence_de: "Ich zweifle an seiner Geschichte.", sentence_mk: "Се сомневам во неговата приказна.", image: "🤔" },
  { word: "vertrauen", translation: "верува (доверба)", category: "verb", sentence_de: "Ich vertraue dir.", sentence_mk: "Ти верувам.", image: "🤝" },
  { word: "misstrauen", translation: "не верува (недоверба)", category: "verb", sentence_de: "Ich misstraue Fremden.", sentence_mk: "Не им верувам на странци.", image: "👀" },
  { word: "bewundern", translation: "се восхитува", category: "verb", sentence_de: "Ich bewundere deine Arbeit.", sentence_mk: "Му се восхитувам на твојата работа.", image: "😍" },
  { word: "respektieren", translation: "почитува", category: "verb", sentence_de: "Ich respektiere deine Meinung.", sentence_mk: "Го почитувам твоето мислење.", image: "🤝" },
  { word: "akzeptieren", translation: "прифаќа", category: "verb", sentence_de: "Ich akzeptiere die Regeln.", sentence_mk: "Ги прифаќам правилата.", image: "✅" },
  { word: "ablehnen", translation: "одбива", category: "verb", sentence_de: "Ich lehne das Angebot ab.", sentence_mk: "Ја одбивам понудата.", image: "❌" },
  { word: "verweigern", translation: "одбива (тврдоглаво)", category: "verb", sentence_de: "Er verweigert die Aussage.", sentence_mk: "Тој одбива да даде изјава.", image: "🙅" },
  { word: "erlauben", translation: "дозволува", category: "verb", sentence_de: "Meine Eltern erlauben es.", sentence_mk: "Моите родители го дозволуваат тоа.", image: "✅" },
  { word: "verbieten", translation: "забранува", category: "verb", sentence_de: "Das Gesetz verbietet das.", sentence_mk: "Законот го забранува тоа.", image: "🚫" },
  { word: "erfüllen", translation: "исполнува", category: "verb", sentence_de: "Ich erfülle meine Pflicht.", sentence_mk: "Ја исполнувам мојата должност.", image: "✅" },
  { word: "enttäuschen", translation: "разочарува", category: "verb", sentence_de: "Du hast mich enttäuscht.", sentence_mk: "Ме разочара.", image: "😞" },
  { word: "überraschen", translation: "изненадува", category: "verb", sentence_de: "Das überrascht mich.", sentence_mk: "Тоа ме изненадува.", image: "😲" },
  { word: "erschrecken", translation: "плаши", category: "verb", sentence_de: "Der Lärm erschreckt mich.", sentence_mk: "Шумот ме плаши.", image: "😱" },
  { word: "verletzen", translation: "повредува", category: "verb", sentence_de: "Er hat sich verletzt.", sentence_mk: "Тој се повреди.", image: "🩹" },
  { word: "heilen", translation: "лекува/заздравува", category: "verb", sentence_de: "Die Wunde heilt langsam.", sentence_mk: "Раната заздравува полека.", image: "💊" },
  { word: "retten", translation: "спасува", category: "verb", sentence_de: "Der Feuerwehrmann rettet das Kind.", sentence_mk: "Пожарникарот го спасува детето.", image: "🆘" },
  { word: "schaden", translation: "штети", category: "verb", sentence_de: "Rauchen schadet der Gesundheit.", sentence_mk: "Пушењето му штети на здравјето.", image: "🚬" },
  { word: "nützen", translation: "користи (бити од корист)", category: "verb", sentence_de: "Das nützt mir nichts.", sentence_mk: "Тоа не ми користи ништо.", image: "🤷" },
  { word: "verhindern", translation: "спречува", category: "verb", sentence_de: "Wir verhindern den Unfall.", sentence_mk: "Го спречуваме несреќата.", image: "🚫" },
  { word: "ermöglichen", translation: "овозможува", category: "verb", sentence_de: "Das Stipendium ermöglicht das Studium.", sentence_mk: "Стипендијата го овозможува студирањето.", image: "🎓" },
  { word: "verursachen", translation: "предизвикува", category: "verb", sentence_de: "Der Stau verursacht Ärger.", sentence_mk: "Гужвата предизвикува лутина.", image: "😠" },
  { word: "bewirken", translation: "предизвикува (ефект)", category: "verb", sentence_de: "Die Medizin bewirkt eine Besserung.", sentence_mk: "Лекот предизвикува подобрување.", image: "💊" }
];