import { Idiom } from './types';

export const IDIOMS_DATA: Idiom[] = [
  // ОСНОВНИ ИДИОМИ (BASIC IDIOMS) - 30
  { de: "Da liegt der Hund begraben", mk: "Тука лежи зајакот", literal: "Таму лежи кучето закопано" },
  { de: "Tomaten auf den Augen haben", mk: "Да се биде слеп за очигледното", literal: "Да имаш домати на очите" },
  { de: "Um den heißen Brei herumreden", mk: "Кружи како мачка околу врела каша", literal: "Зборува околу жешката каша" },
  { de: "Alles in Butter", mk: "Сè е подмачкано / Сè е во ред", literal: "Сè е во путер" },
  { de: "Ein Affentheater machen", mk: "Прави непотребна драма", literal: "Прави мајмунски театар" },
  { de: "Krokodilstränen weinen", mk: "Лие крокодилски солзи", literal: "Плаче крокодилски солзи" },
  { de: "Jemandem einen Bären aufbinden", mk: "Му продава рогови за свеќи", literal: "Му врзува мечка на некој" },
  { de: "Zwei Fliegen mit einer Klappe schlagen", mk: "Две муви со еден удар", literal: "Удри две муви со една тупаница" },
  { de: "Einen Vogel haben", mk: "Не му се сите на број", literal: "Има птица" },
  { de: "Hunde, die bellen, beißen nicht", mk: "Куче што лае, не каса", literal: "Куче што лае, не гризе" },
  { de: "Lügen haben kurze Beine", mk: "На лагата ѝ се кратки нозете", literal: "Лагите имаат кратки нозе" },
  { de: "Die Daumen drücken", mk: "Држи среќа", literal: "Стискај ги палците" },
  { de: "Den Faden verlieren", mk: "Го изгуби континуитетот / Конецот", literal: "Го изгуби конецот" },
  { de: "Ein Herz aus Gold haben", mk: "Има златно срце", literal: "Има срце од злато" },
  { de: "Hals- und Beinbruch!", mk: "Со среќа! (Скрши нога)", literal: "Скршен врат и нога!" },
  { de: "Da steppt der Bär", mk: "Таму е најдобрата забава", literal: "Таму танцува мечката" },
  { de: "Auf großem Fuß leben", mk: "Живее на висока нога", literal: "Живее на големо стапало" },
  { de: "Ins Fettnäpfchen treten", mk: "Направи гаф / Тресе зелени", literal: "Згазна во садот со маст" },
  { de: "Den Nagel auf den Kopf treffen", mk: "Ја погоди поентата / Во центар", literal: "Го погоди клинецот во глава" },
  { de: "Wer zuerst kommt, mahlt zuerst", mk: "Кој прв дојде, прв услужен", literal: "Кој прв доаѓа, прв меле" },
  { de: "Schwein haben", mk: "Има голема среќа", literal: "Има свиња" },
  { de: "Die Flinte ins Korn werfen", mk: "Да се откажеш / Да кренеш раце", literal: "Да ја фрлиш пушката во житото" },
  { de: "Auf Wolke sieben schweben", mk: "Е на седмо небо", literal: "Лебди на седмиот облак" },
  { de: "Eulen nach Athen tragen", mk: "Залудна работа (Носи дрва во шума)", literal: "Носи бувови во Атина" },
  { de: "Blau machen", mk: "Забушава / Бега од работа", literal: "Прави сино" },
  { de: "Unter vier Augen", mk: "Во четири очи", literal: "Под четири очи" },
  { de: "Ein Brett vor dem Kopf haben", mk: "Не сфаќа ништо / Како со ѕид да збориш", literal: "Има штица пред главата" },
  { de: "Den Teufel an die Wand malen", mk: "Гледа песимистички / Го бара ѓаволот", literal: "Го црта ѓаволот на ѕидот" },
  { de: "Das A und O", mk: "Најважното / Алфа и омега", literal: "А и О" },
  { de: "Asche auf mein Haupt", mk: "Моја грешка / Се посипувам со пепел", literal: "Пепел на мојата глава" },

  // ИДИОМИ СО ЖИВОТНИ (ANIMAL IDIOMS) - 25
  { de: "Die Katze im Sack kaufen", mk: "Купува мачка во вреќа", literal: "Купува мачка во вреќа" },
  { de: "Die Katze aus dem Sack lassen", mk: "Ја открива тајната", literal: "Ја пушта мачката од вреќа" },
  { de: "Mit den Wölfen heulen", mk: "Се прилагодува на средината", literal: "Вие со волците" },
  { de: "Ein Wolf im Schafspelz", mk: "Волк во јагнешка кожа", literal: "Волк во овча кожа" },
  { de: "Die Pferde scheu machen", mk: "Предизвикува немир", literal: "Ги плаши коњите" },
  { de: "Mit Pferdefußen", mk: "Со маана / со флека", literal: "Со коњски нозе" },
  { de: "Das Pferd von hinten aufzäumen", mk: "Почнува од погрешна страна", literal: "Го зауздува коњот одзади" },
  { de: "Die Kirche im Dorf lassen", mk: "Не претерува", literal: "Ја остава црквата во селото" },
  { de: "Den Ochsen hinter den Pflug spannen", mk: "Прави нешто наопаку", literal: "Го става волат зад плугот" },
  { de: "Die Ziege zum Gärtner machen", mk: "Става лисица да чува кокошки", literal: "Го прави козата градинар" },
  { de: "Ein alter Hase", mk: "Стар ветеран / Искусен", literal: "Стар зајак" },
  { de: "Da brat mir einer 'nen Storch", mk: "Нема да веруваш!", literal: "Некој да ми испече штрк" },
  { de: "Die Schmetterlinge im Bauch", mk: "Пеперутки во стомакот", literal: "Пеперутки во стомакот" },
  { de: "Eine Laus auf der Leber haben", mk: "Има проблем / му тежи", literal: "Има вошка на џигерот" },
  { de: "Mäuse im Kopf haben", mk: "Има чудни идеи", literal: "Има глувци во главата" },
  { de: "Die Ratten verlassen das sinkende Schiff", mk: "Стаорците го напуштаат бродот", literal: "Глувците го напуштаат тонечкиот брод" },
  { de: "Mit dem Bock auf die Sünde gehen", mk: "Прави нешто ризично", literal: "Со јарецот на грев" },
  { de: "Vom wilden Esel gestochen", mk: "Како ударен со мокра чуна", literal: "Фрлен од диво магаре" },
  { de: "Eine Gans stechen", mk: "Прави нешто глупаво", literal: "Боде гуска" },
  { de: "Die Ente im Schilf", mk: "Нешто сомнително", literal: "Патка во трските" },
  { de: "Den Bock zum Gärtner machen", mk: "Става некого на погрешно место", literal: "Го прави јарецот градинар" },
  { de: "Wie ein Elefant im Porzellanladen", mk: "Како слон во стакларница", literal: "Како слон во продавница за порцелан" },
  { de: "Auf dem hohen Ross sitzen", mk: "Се држи нависоко", literal: "Седи на висок коњ" },
  { de: "Die Füchse grüßen einander", mk: "Се разбираат без зборови", literal: "Лисиците се поздравуваат" },
  { de: "Eine Kröte schlucken", mk: "Голта горкава пилула", literal: "Голта крастава жаба" },

  // ИДИОМИ СО ХРАНА (FOOD IDIOMS) - 20
  { de: "Sein Süppchen am eigenen Herd kochen", mk: "Си ги вари своите работи", literal: "Си ја вари супата на свој шпорет" },
  { de: "Die Suppe auslöffeln", mk: "Трпи последици", literal: "Ја јаде супата" },
  { de: "Jemandem die Suppe versalzen", mk: "Му расипува некому план", literal: "Му ја пресолува супата" },
  { de: "Ein harter Brocken", mk: "Тврда кора / тешка задача", literal: "Тврдо парче" },
  { de: "Das ist nicht mein Bier", mk: "Не е мој проблем", literal: "Тоа не е мое пиво" },
  { de: "Klare Ansage wie Klare Brühe", mk: "Како отворена книга", literal: "Јасно како бистра супа" },
  { de: "Mit jemandem ein Hühnchen zu rupfen haben", mk: "Има да си плаќа/ да си разјасни", literal: "Има да скубе пиле со некого" },
  { de: "Das Ei des Kolumbus", mk: "Многу едноставно решение", literal: "Јајцето на Колумбо" },
  { de: "Wie ein Ei dem anderen gleichen", mk: "Си личат како две капки вода", literal: "Си личат како едно на друго јајце" },
  { de: "Die Eier unter die Henne legen", mk: "Ги враќа работите каде што треба", literal: "Ги става јајцата под кокошката" },
  { de: "Da haben wir den Salat", mk: "Ете ти сега!", literal: "Еве ја салатата" },
  { de: "Der dicke Fisch kommt später", mk: "Поважното доаѓа подоцна", literal: "Дебелата риба доаѓа подоцна" },
  { de: "Klein but sweet, sagt der Bauer da ist die Kartoffel", mk: "Малку ама вредно", literal: "Мало ама слатко, вели селанецот еве го компирот" },
  { de: "Die Kartoffel im Keller haben", mk: "Има резерви", literal: "Има компири во подрум" },
  { de: "Das schmeckt nach mehr", mk: "Бара уште", literal: "Има вкус на уште" },
  { de: "Zuckerbrot und Peitsche", mk: "Морков и стап", literal: "Шеќерен леб и камшик" },
  { de: "Sich die Butter vom Brot nehmen lassen", mk: "Дозволува да го искористуваат", literal: "Дозволува да му го земаат путерот од лебот" },
  { de: "Sein Fett weghaben", mk: "Си ја доби заслужената казна", literal: "Си го доби своето сало" },
  { de: "In der Tinte sitzen", mk: "Во небрано", literal: "Седи во мастило" },
  { de: "Einen im Tee haben", mk: "Пијан", literal: "Има во чајот" },

  // ИДИОМИ СО ТЕЛО (BODY IDIOMS) - 25
  { de: "Sich die Augen ausweinen", mk: "Се исплакува", literal: "Си ги исплакува очите" },
  { de: "Große Augen machen", mk: "Се чуди / гледа зачудено", literal: "Прави големи очи" },
  { de: "Ein Auge zudrücken", mk: "Затвора очи (попушта)", literal: "Затвора едно око" },
  { de: "Die Nase voll haben", mk: "Му е доста", literal: "Има полн нос" },
  { de: "Die Nase überall reinstecken", mk: "Го пика носот насекаде", literal: "Го пика носот насекаде" },
  { de: "Jemandem auf der Nase herumtanzen", mk: "Му скока по глава", literal: "Му танцува на носот" },
  { de: "Die Ohren spitzen", mk: "Наостри уши", literal: "Ги заострува ушите" },
  { de: "Sich etwas hinter die Ohren schreiben", mk: "Добро да запамти", literal: "Си запишува зад ушите" },
  { de: "Tauben Ohren predigen", mk: "Зборува на глуви уши", literal: "Проповеда на глуви уши" },
  { de: "Die Zähne zusammenbeißen", mk: "Стиснува заби", literal: "Стиснува заби" },
  { de: "Jemandem die Zähne zeigen", mk: "Му ги покажува забите", literal: "Му ги покажува забите" },
  { de: "Sich den Mund verbrennen", mk: "Си го изгори јазикот", literal: "Си ја изгорува устата" },
  { de: "Nicht auf den Mund gefallen sein", mk: "Не му паѓа камен во уста", literal: "Не е паднат на уста" },
  { de: "Den Mund halten", mk: "Молчи / држи јазак за заби", literal: "Ја држи устата" },
  { de: "Von der Hand in den Mund leben", mk: "Живее од рака до уста", literal: "Од рака во уста живее" },
  { de: "Die Hände in den Schoß legen", mk: "Крши раце", literal: "Ги става рацете во скутот" },
  { de: "Zwei linke Hände haben", mk: "Нема дарба за рачна работа", literal: "Има две леви раце" },
  { de: "Das Herz auf der Zunge tragen", mk: "Го кажува она што го мисли", literal: "Го носи срцето на јазик" },
  { de: "Ein Stein fällt vom Herzen", mk: "Ми падна камен од срце", literal: "Камен паѓа од срце" },
  { de: "Sein Herz ausschütten", mk: "Го отвора срцето", literal: "Го истура своето срце" },
  { de: "Die Beine in die Hand nehmen", mk: "Го зема во нозе", literal: "Ги зема нозете во раце" },
  { de: "Auf eigenen Füßen stehen", mk: "Стои на свои нозе", literal: "Стои на свои стапала" },
  { de: "Mit beiden Beinen im Leben stehen", mk: "Со двете нозе на земја", literal: "Со двете нозе во животот" },
  { de: "Kalte Füße bekommen", mk: "Се исплаши / се откажува", literal: "Му стануваат ладни нозете" },
  { de: "Einen Fuß in die Tür bekommen", mk: "Ја вметнува ногата", literal: "Става нога на вратата" },

  // ИДИОМИ ЗА ЛУЃЕ И ОДНЕСУВАЊЕ (PEOPLE AND BEHAVIOR) - 25
  { de: "Der hat einen Dachschaden", mk: "Не му е добар покривот / полудел", literal: "Има оштетен покрив" },
  { de: "Nicht alle Tassen im Schrank haben", mk: "Нема сите шолји во плакар", literal: "Нема сите чаши во плакарот" },
  { de: "Eine Schraube locker haben", mk: "Му фали шраф", literal: "Има олабавена завртка" },
  { de: "Ein weicher Zahn", mk: "Мек човек / Лесно се влијае", literal: "Мек заб" },
  { de: "Ein harter Hund sein", mk: "Тврд човек", literal: "Тврдо куче" },
  { de: "Ein treuer Hund", mk: "Верен како куче", literal: "Верно куче" },
  { de: "Ein armes Schwein", mk: "Кутра душичка", literal: "Сиромашна свиња" },
  { de: "Ein Glückspilz", mk: "Среќник", literal: "Среќна печурка" },
  { de: "Ein Pechvogel", mk: "Баксуз", literal: "Птица на несреќа" },
  { de: "Ein Sonnenschein", mk: "Сонце (весела личност)", literal: "Сонце" },
  { de: "Ein wandelndes Lexikon", mk: "Одичка енциклопедија", literal: "Шетачки лексикон" },
  { de: "Ein kluger Kopf", mk: "Паметна глава", literal: "Паметна глава" },
  { de: "Ein heller Kopf", mk: "Бистар ум", literal: "Светла глава" },
  { de: "Ein unbeschriebenes Blatt", mk: "Неиспишан лист", literal: "Неиспишан лист" },
  { de: "Ein bekanntes Gesicht", mk: "Познато лице", literal: "Познато лице" },
  { de: "Ein Fremder im eigenen Haus", mk: "Странец во сопствена куќа", literal: "Странец во својот дом" },
  { de: "Ein alter Freund ist wie ein alter Wein", mk: "Стариот пријател е како старо вино", literal: "Стар пријател е како старо вино" },
  { de: "Ein Schwamm in der Wüste", mk: "Реткост / необичност", literal: "Сунѓер во пустина" },
  { de: "Ein Fisch im Wasser", mk: "Риба во вода (се чувствува природно)", literal: "Риба во вода" },
  { de: "Ein Fremder im Paradies", mk: "Не припаѓа", literal: "Странец во рајот" },
  { de: "Ein Engel in der Hölle", mk: "Добар на лошо место", literal: "Ангел во пеколот" },
  { de: "Ein Teufel in Menschengestalt", mk: "Ѓавол во човечки облик", literal: "Ѓавол во човечка форма" },
  { de: "Eine Seele von Mensch", mk: "Блага душа", literal: "Душа од човек" },
  { de: "Ein falscher Fuffziger", mk: "Лажен/неискрен човек", literal: "Лажна педесетка" },
  { de: "Ein Spielverderber", mk: "Расипувач на забава", literal: "Расипувач на игра" },

  // ИДИОМИ ЗА ВРЕМЕ И СРЕЌА (TIME AND LUCK) - 15
  { de: "Die Zeit totschlagen", mk: "Убива време", literal: "Убива време" },
  { de: "In der Zeit stehen", mk: "Стои во време", literal: "Стои во времето" },
  { de: "Die Zeit heilt alle Wunden", mk: "Времето лечи сè", literal: "Времето ги лекува сите рани" },
  { de: "Kommende Zeit, kommende Rat", mk: "Ќе видиме", literal: "Времето што доаѓа, советот што доаѓа" },
  { de: "Die goldene Zeit", mk: "Златно време", literal: "Златно време" },
  { de: "Von heute auf morgen", mk: "Преку ноќ", literal: "Од денес на утре" },
  { de: "In letzter Minute", mk: "Во последен момент", literal: "Во последна минута" },
  { de: "Fünf Minuten vor zwölf", mk: "Во последен час", literal: "Пет минути пред дванаесет" },
  { de: "Alle Zeit der Welt haben", mk: "Има цело време на светот", literal: "Има сето време на светот" },
  { de: "Sich die Zeit vertreiben", mk: "Го поминува времето", literal: "Си го поминува времето" },
  { de: "Das Glück ist ein Vogerl", mk: "Среќата е како птица", literal: "Среќата е птица" },
  { de: "Das Glück kommt selten allein", mk: "Среќата ретко доаѓа сама", literal: "Среќата ретко доаѓа сама" },
  { de: "Pech im Spiel, Glück in der Liebe", mk: "На карти губиш, во љубов добиваш", literal: "Несреќа во игра, среќа во љубов" },
  { de: "Vom Glück verlassen", mk: "Напуштен од среќата", literal: "Напуштањето од среќата" },
  { de: "Dem Glück eine Gasse", mk: "Да се отвори патека за среќата", literal: "На среќата една улица" },

  // ИДИОМИ ЗА ЉУБОВ (LOVE IDIOMS) - 15
  { de: "Liebe auf den ersten Blick", mk: "Љубов на прв поглед", literal: "Љубов на прв поглед" },
  { de: "Die große Liebe", mk: "Големата љубов", literal: "Големата љубов" },
  { de: "Eine Liebesheirat", mk: "Брак од љубов", literal: "Љубовен брак" },
  { de: "Alte Liebe rostet nicht", mk: "Старата љубов не рѓосува", literal: "Старата љубов не рѓосува" },
  { de: "Jemandem das Herz brechen", mk: "Му го крши срцето", literal: "Му го крши срцето" },
  { de: "Sein Herz verschenken", mk: "Го дава срцето", literal: "Го подарува своето срце" },
  { de: "Mit dem Herzen denken", mk: "Мисли со срце", literal: "Мисли со срце" },
  { de: "Das Herz hüpft vor Freude", mk: "Срцето скока од радост", literal: "Срцето скока од радост" },
  { de: "Ein Herz und eine Seele sein", mk: "Душа и срце", literal: "Да бидат едно срце и една душа" },
  { de: "Jemandem schöne Augen machen", mk: "Му се додворува", literal: "Прави убави очи" },
  { de: "In den siebten Himmel kommen", mk: "На седмо небо", literal: "Доаѓа на седмото небо" },
  { de: "Schmetterlinge im Bauch haben", mk: "Пеперутки во стомакот", literal: "Има пеперутки во стомакот" },
  { de: "Verknallt sein", mk: "Заљубен", literal: "Истрелан" },
  { de: "Sich verlieben wie ein Teenager", mk: "Заљубува како тинејџер", literal: "Се заљубува како тинејџер" },
  { de: "Liebe macht blind", mk: "Љубовта е слепа", literal: "Љубовта прави слеп" },

  // КОМПЛЕТИРАЊЕ ДО 100+ (COMPLETING TO 100+) - 15
  { de: "Ein Wörtchen mitzureden haben", mk: "Има збор", literal: "Има да каже зборче" },
  { de: "Das ist ein Buch mit sieben Siegeln", mk: "Тоа е кинески азбука", literal: "Тоа е книга со седум печати" },
  { de: "Ins Schwarze treffen", mk: "Го погоди центарот", literal: "Го погоди црното" },
  { de: "Haare auf den Zähnen haben", mk: "Има остар јазик", literal: "Има влакна на забите" },
  { de: "Mit dem Feuer spielen", mk: "Си игра со оган", literal: "Си игра со оган" },
  { de: "Öl ins Feuer gießen", mk: "Долева масло на оган", literal: "Истура масло на оган" },
  { de: "Die Wellen glätten", mk: "Ги смирува страстите", literal: "Ги измазнува брановите" },
  { de: "Auf der Stelle treten", mk: "Стагнира", literal: "Трапка на место" },
  { de: "Schwarz auf weiß haben", mk: "Црно на бело", literal: "Црно на бело" },
  { de: "Himmel und Hölle in Bewegung setzen", mk: "Крши и троши", literal: "Го става небото и пеколот во движење" },
  { de: "Zwischen Himmel und Erde", mk: "Помеѓу небо и земја", literal: "Помеѓу небо и земја" },
  { de: "Mit dem Kopf durch die Wand wollen", mk: "Сака со сила да направи", literal: "Сака со глава низ ѕид" },
  { de: "Einen kühlen Kopf bewahren", mk: "Задржува смиреност", literal: "Задржува ладна глава" },
  { de: "Das kann ja heiter werden", mk: "Ова ќе биде интересно", literal: "Ова може да биде весело" },
  { de: "Das ist die Höhe!", mk: "Ова е веќе премногу!", literal: "Ова е висината!" },
  { de: "Da staunt der Laie, und der Fachmann wundert sich", mk: "Сите се чудат", literal: "Лаикот се чуди, а експертот се восхитува" }
];