export interface WordleWord {
  word: string;
  translation: string;
  description: string;
}

export interface WordleTheme {
  id: string;
  name: string;
  emoji: string;
  color: string;
  description: string;
  words: WordleWord[];
}

export const WORDLE_THEMES: WordleTheme[] = [
  {
    id: 'alltag',
    name: 'Секојдневие',
    emoji: '🏠',
    color: 'from-green-500 to-emerald-600',
    description: 'Најчести зборови во секојдневниот живот',
    words: [
      { word: 'apfel', translation: 'јаболко', description: 'Плод од јаболкницата' },
      { word: 'wasser', translation: 'вода', description: 'Течна супстанција за пиење' },
      { word: 'brot', translation: 'леб', description: 'Основна храна од брашно' },
      { word: 'milch', translation: 'млеко', description: 'Пијалик од крава или друг цицач' },
      { word: 'tisch', translation: 'маса', description: 'Мебел за седење и работа' },
      { word: 'stuhl', translation: 'стол', description: 'Мебел за седење' },
      { word: 'tür', translation: 'врата', description: 'Отвор за влегување во просторија' },
      { word: 'fenster', translation: 'прозор', description: 'Отвор во ѕид за светлина' },
      { word: 'licht', translation: 'светло', description: 'Спротивност од темнина' },
      { word: 'heute', translation: 'денес', description: 'Деновниот ден' },
      { word: 'morgen', translation: 'утре', description: 'Следниот ден' },
      { word: 'tag', translation: 'ден', description: '24 часа' },
      { word: 'nacht', translation: 'ноќ', description: 'Време кога е темно' },
      { word: 'jahr', translation: 'година', description: '12 месеци' },
      { word: 'kind', translation: 'дете', description: 'Младо човечко суштество' },
      { word: 'frau', translation: 'жена', description: 'Женско лице' },
      { word: 'mann', translation: 'маж', description: 'Машко лице' },
      { word: 'haus', translation: 'куќа', description: 'Објекат за живеење' },
      { word: 'zeit', translation: 'време', description: 'Концепт на минување' },
      { word: 'leben', translation: 'живот', description: 'Постоење на организми' },
    ]
  },
  {
    id: 'essen',
    name: 'Храна',
    emoji: '🍕',
    color: 'from-orange-500 to-red-600',
    description: 'Зборови поврзани со храна и пијалици',
    words: [
      { word: 'käse', translation: 'сирење', description: 'Млечен производ' },
      { word: 'fisch', translation: 'риба', description: 'Животинка во вода' },
      { word: 'fleisch', translation: 'месо', description: 'Мускулно ткиво од животни' },
      { word: 'eier', translation: 'јајца', description: 'Производ од кокошка' },
      { word: 'obst', translation: 'овошје', description: 'Плодови од дрвја' },
      { word: 'gemüse', translation: 'зеленчук', description: 'Растителна храна' },
      { word: 'salat', translation: 'салата', description: 'Свежо зеленчук' },
      { word: 'suppe', translation: 'супа', description: 'Течна храна' },
      { word: 'reis', translation: 'ориз', description: 'Житарка' },
      { word: 'zucker', translation: 'шеќер', description: 'Сладок кристал' },
      { word: 'salz', translation: 'сол', description: 'Бел кристал за зачинување' },
      { word: 'kaffee', translation: 'кафе', description: 'Пијалик од кафеав боб' },
      { word: 'tee', translation: 'чај', description: 'Пијалик од билки' },
      { word: 'bier', translation: 'пиво', description: 'Алкохолен пијалик' },
      { word: 'wein', translation: 'вино', description: 'Алкохолен пијалик од грозје' },
      { word: 'saft', translation: 'сок', description: 'Течност од овошје' },
      { word: 'kuchen', translation: 'колаче', description: 'Слатко печиво' },
      { word: 'nudel', translation: 'тестенина', description: 'Италијанска храна' },
      { word: 'pizza', translation: 'пица', description: 'Италијанско јадење' },
      { word: 'gulas', translation: 'гулаш', description: 'Месо со зачини' },
    ]
  },
  {
    id: 'arbeit',
    name: 'Работа',
    emoji: '💼',
    color: 'from-blue-500 to-indigo-600',
    description: 'Зборови поврзани со работа и бизнис',
    words: [
      { word: 'arbeit', translation: 'работа', description: 'Активност за заработка' },
      { word: 'büro', translation: 'канцеларија', description: 'Просторија за работа' },
      { word: 'chef', translation: 'шеф', description: 'Надредениот' },
      { word: 'kunde', translation: 'купувач', description: 'Лице што купува' },
      { word: 'preis', translation: 'цена', description: 'Вредност на производ' },
      { word: 'geld', translation: 'пари', description: 'Средство за плаќање' },
      { word: 'bank', translation: 'банка', description: 'Финансиска институција' },
      { word: 'marke', translation: 'марка', description: 'Бренд или ознака' },
      { word: 'firma', translation: 'фирма', description: 'Компанија' },
      { word: 'trade', translation: 'трговија', description: 'Размена на стоки' },
      { word: 'kasse', translation: 'каса', description: 'Место за плаќање' },
      { word: 'shop', translation: 'продавница', description: 'Место за купување' },
      { word: 'deal', translation: 'договор', description: 'Договор или зделка' },
      { word: 'taxi', translation: 'такси', description: 'Превозно средство' },
      { word: 'post', translation: 'пошта', description: 'Служба за пратки' },
      { word: 'hotel', translation: 'хотел', description: 'Објекат за преноќевање' },
      { word: 'resto', translation: 'ресторан', description: 'Место за јадење' },
      { word: 'bar', translation: 'бар', description: 'Место за пиење' },
      { word: 'club', translation: 'клуб', description: 'Место за забава' },
      { word: 'media', translation: 'медиуми', description: 'Средства за информирање' },
    ]
  },
  {
    id: 'reise',
    name: 'Патување',
    emoji: '✈️',
    color: 'from-sky-500 to-cyan-600',
    description: 'Зборови поврзани со патување и транспорт',
    words: [
      { word: 'zug', translation: 'воз', description: 'Железнички превоз' },
      { word: 'auto', translation: 'автомобил', description: 'Моторно возило' },
      { word: 'rad', translation: 'велосипед', description: 'Двотркално возило' },
      { word: 'schiff', translation: 'брод', description: 'Превоз по вода' },
      { word: 'flug', translation: 'лет', description: 'Превоз по воздух' },
      { word: 'bahn', translation: 'железница', description: 'Систем за возови' },
      { word: 'strasse', translation: 'пат', description: 'Коловоз за возила' },
      { word: 'platz', translation: 'плоштад', description: 'Отворено место' },
      { word: 'hafen', translation: 'пристаниште', description: 'Место за бродови' },
      { word: 'park', translation: 'парк', description: 'Зелена површина' },
      { word: 'hotel', translation: 'хотел', description: 'Сместување' },
      { word: 'zimmer', translation: 'соба', description: 'Просторија во хотел' },
      { word: 'koffer', translation: 'куфер', description: 'Прибор за багаж' },
      { word: 'ticket', translation: 'билет', description: 'Дозвола за пат' },
      { word: 'pass', translation: 'пасош', description: 'Документ за патување' },
      { word: 'visa', translation: 'виза', description: 'Дозвола за влез' },
      { word: 'route', translation: 'рута', description: 'Правец на патување' },
      { word: 'tour', translation: 'тура', description: 'Организирано патување' },
      { word: 'berg', translation: 'планина', description: 'Висока географска форма' },
      { word: 'strand', translation: 'плажа', description: 'Брег на море' },
    ]
  },
  {
    id: 'familie',
    name: 'Семејство',
    emoji: '👨‍👩‍👧',
    color: 'from-pink-500 to-rose-600',
    description: 'Зборови поврзани со семејство и односи',
    words: [
      { word: 'mutter', translation: 'мајка', description: 'Женски родител' },
      { word: 'vater', translation: 'татко', description: 'Машки родител' },
      { word: 'eltern', translation: 'родители', description: 'Мајка и татко' },
      { word: 'bruder', translation: 'брат', description: 'Машко братче' },
      { word: 'schwester', translation: 'сестра', description: 'Женско братче' },
      { word: 'onkel', translation: 'чичко', description: 'Брат на родител' },
      { word: 'tante', translation: 'тетка', description: 'Сестра на родител' },
      { word: 'cousin', translation: 'братучед', description: 'Дете на чичко/тетка' },
      { word: 'freund', translation: 'пријател', description: 'Близко лице' },
      { word: 'liebe', translation: 'љубов', description: 'Чувство на приврзаност' },
      { word: 'herz', translation: 'срце', description: 'Орган за крвта' },
      { word: 'seele', translation: 'душа', description: 'Духовна суштина' },
      { word: 'name', translation: 'име', description: 'Лична ознака' },
      { word: 'jung', translation: 'млад', description: 'Спротивност на стар' },
      { word: 'alt', translation: 'стар', description: 'Спротивност на млад' },
      { word: 'groß', translation: 'голем', description: 'Спротивност на мал' },
      { word: 'klein', translation: 'мал', description: 'Спротивност на голем' },
      { word: 'reich', translation: 'богат', description: 'Со многу пари' },
      { word: 'arm', translation: 'сиромашен', description: 'Без многу пари' },
      { word: 'fremd', translation: 'туѓ', description: 'Не познат' },
    ]
  },
  {
    id: 'natur',
    name: 'Природа',
    emoji: '🌳',
    color: 'from-emerald-500 to-teal-600',
    description: 'Зборови поврзани со природа и животни',
    words: [
      { word: 'hund', translation: 'куче', description: 'Домашно животно' },
      { word: 'katze', translation: 'мачка', description: 'Домашно животно' },
      { word: 'vogel', translation: 'птица', description: 'Животно со крилја' },
      { word: 'pferd', translation: 'коњ', description: 'Ездитно животно' },
      { word: 'kuh', translation: 'крава', description: 'Млечно животно' },
      { word: 'schaf', translation: 'овца', description: 'Животно со вuna' },
      { word: 'schwein', translation: 'свинја', description: 'Домашно животно' },
      { word: 'ente', translation: 'патка', description: 'Водена птица' },
      { word: 'fisch', translation: 'риба', description: 'Водено животно' },
      { word: 'bär', translation: 'мечка', description: 'Дивеч' },
      { word: 'wolf', translation: 'волк', description: 'Дивеч' },
      { word: 'fuchs', translation: 'лисица', description: 'Дивеч' },
      { word: 'maus', translation: 'глушец', description: 'Мало животно' },
      { word: 'ratte', translation: 'стаорец', description: 'Мало животно' },
      { word: 'biene', translation: 'пчела', description: 'Инсект' },
      { word: 'spinne', translation: 'пајак', description: 'Инсект' },
      { word: 'fliege', translation: 'мува', description: 'Инсект' },
      { word: 'ameise', translation: 'мравка', description: 'Инсект' },
      { word: 'blume', translation: 'цвет', description: 'Растение' },
      { word: 'baum', translation: 'дрво', description: 'Растение' },
    ]
  },
  {
    id: 'zeit',
    name: 'Време',
    emoji: '⏰',
    color: 'from-violet-500 to-purple-600',
    description: 'Зборови поврзани со време и датуми',
    words: [
      { word: 'uhr', translation: 'часовник', description: 'Уред за време' },
      { word: 'minute', translation: 'минута', description: '60 секунди' },
      { word: 'sekund', translation: 'секунда', description: 'Најмала единица' },
      { word: 'stund', translation: 'час', description: '60 минути' },
      { word: 'monat', translation: 'месец', description: 'Околу 30 дена' },
      { word: 'woche', translation: 'недела', description: '7 дена' },
      { word: 'datum', translation: 'датум', description: 'Ден во календар' },
      { word: 'ferien', translation: 'одмор', description: 'Слободно време' },
      { word: 'fest', translation: 'празник', description: 'Специјален ден' },
      { word: 'feier', translation: 'празник', description: 'Поврзан со празник' },
      { word: 'früh', translation: 'рано', description: 'Пред обед' },
      { word: 'spät', translation: 'доцна', description: 'По обед' },
      { word: 'immer', translation: 'секогаш', description: 'Без исклучок' },
      { word: 'nie', translation: 'никогаш', description: 'Без времена' },
      { word: 'bald', translation: 'наскоро', description: 'За кратко време' },
      { word: 'noch', translation: 'уште', description: 'Дополнително време' },
      { word: 'schon', translation: 'веќе', description: 'Поминато време' },
      { word: 'danach', translation: 'потоа', description: 'Следно во време' },
      { word: 'vorher', translation: 'претходно', description: 'Пред нешто' },
      { word: 'sofort', translation: 'веднаш', description: 'Без одлагање' },
    ]
  },
  {
    id: 'gefühl',
    name: 'Чувства',
    emoji: '😊',
    color: 'from-amber-500 to-orange-600',
    description: 'Зборови поврзани со емоции и чувства',
    words: [
      { word: 'freud', translation: 'радост', description: 'Позитивно чувство' },
      { word: 'angst', translation: 'страв', description: 'Негативно чувство' },
      { word: 'liebe', translation: 'љубов', description: 'Позитивно чувство' },
      { word: 'neid', translation: 'завист', description: 'Негативно чувство' },
      { word: 'scham', translation: 'срам', description: 'Негативно чувство' },
      { word: 'schuld', translation: 'вина', description: 'Осеќање на одговорност' },
      { word: 'fried', translation: 'мир', description: 'Без конфликт' },
      { word: 'stress', translation: 'стрес', description: 'Притисок' },
      { word: 'muede', translation: 'уморен', description: 'Потреба за одмор' },
      { word: 'satt', translation: 'сит', description: 'Без глад' },
      { word: 'durst', translation: 'жеден', description: 'Потреба за вода' },
      { word: 'krank', translation: 'болен', description: 'Нездрав' },
      { word: 'gesund', translation: 'здрав', description: 'Без болест' },
      { word: 'schön', translation: 'убав', description: 'Позитивен изглед' },
      { word: 'böse', translation: 'лош', description: 'Негативен изглед' },
      { word: 'gut', translation: 'добар', description: 'Позитивна квалитета' },
      { word: 'mutig', translation: 'храбар', description: 'Без страв' },
      { word: 'scheu', translation: 'плашлив', description: 'Стравлив' },
      { word: 'zorn', translation: 'лутина', description: 'Силна негативна емоција' },
      { word: 'eitel', translation: 'суетен', description: 'Фиксиран на себе' },
    ]
  },
  {
    id: 'aktion',
    name: 'Акции',
    emoji: '🏃',
    color: 'from-red-500 to-rose-600',
    description: 'Зборови поврзани со дејства и активности',
    words: [
      { word: 'gehen', translation: 'одам', description: 'Движење со нозе' },
      { word: 'lauf', translation: 'трчам', description: 'Брзо движење' },
      { word: 'komm', translation: 'доаѓам', description: 'Пристигнување' },
      { word: 'fahr', translation: 'возам', description: 'Движење со возило' },
      { word: 'flieg', translation: 'летам', description: 'Движење по воздух' },
      { word: 'schwim', translation: 'пливам', description: 'Движење во вода' },
      { word: 'spring', translation: 'скокам', description: 'Брзо движење нагоре' },
      { word: 'sitz', translation: 'седиш', description: 'Одмор во стоење' },
      { word: 'steh', translation: 'стојам', description: 'Одмор во седење' },
      { word: 'lieg', translation: 'лежиш', description: 'Одмор во хоризонтала' },
      { word: 'essen', translation: 'јадам', description: 'Консумирање храна' },
      { word: 'trink', translation: 'пијам', description: 'Консумирање пијалик' },
      { word: 'schlaf', translation: 'спијам', description: 'Одмор со затворени очи' },
      { word: 'arbeit', translation: 'работам', description: 'Вршење на задачи' },
      { word: 'lern', translation: 'уча', description: 'Стекнување на знаење' },
      { word: 'spiel', translation: 'играм', description: 'Забавна активност' },
      { word: 'sag', translation: 'кажам', description: 'Изговарање на зборови' },
      { word: 'hör', translation: 'слушам', description: 'Примање на звуци' },
      { word: 'seh', translation: 'гледам', description: 'Примање на слики' },
      { word: 'fühl', translation: 'чувствувам', description: 'Добивање на сензации' },
    ]
  },
  {
    id: 'ort',
    name: 'Места',
    emoji: '📍',
    color: 'from-cyan-500 to-blue-600',
    description: 'Зборови поврзани со места и локации',
    words: [
      { word: 'stadt', translation: 'град', description: 'Големо населено место' },
      { word: 'dorf', translation: 'село', description: 'Мало населено место' },
      { word: 'land', translation: 'земја', description: 'Држава или поле' },
      { word: 'meer', translation: 'море', description: 'Голема водена површина' },
      { word: 'see', translation: 'езеро', description: 'Мала водена површина' },
      { word: 'fluss', translation: 'река', description: 'Течечка вода' },
      { word: 'berg', translation: 'планина', description: 'Висока копнена форма' },
      { word: 'wald', translation: 'шума', description: 'Многу дрвја' },
      { word: 'feld', translation: 'поле', description: 'Отворена површина' },
      { word: 'weg', translation: 'пат', description: 'Правец за одење' },
      { word: 'ort', translation: 'место', description: 'Општа локација' },
      { word: 'platz', translation: 'плоштад', description: 'Отворено место во град' },
      { word: 'straße', translation: 'улица', description: 'Пат во населба' },
      { word: 'gasse', translation: 'сокаче', description: 'Улица меѓу згради' },
      { word: 'ecke', translation: 'агол', description: 'Место каде се среќаваат две страни' },
      { word: 'mitte', translation: 'центар', description: 'Највнатрешната точка' },
      { word: 'seite', translation: 'страна', description: 'Еден дел од нешто' },
      { word: 'rand', translation: 'крај', description: 'Надворешна граница' },
      { word: 'rand', translation: 'крај', description: 'Надворешна граница' },
      { word: 'zone', translation: 'зона', description: 'Определена област' },
    ]
  }
];

export const MY_VOCAB = {
  id: 'vocab',
  name: 'Мој Вокабулар',
  emoji: '📚',
  color: 'from-primary to-primary/80',
  description: 'Зборови од твојот вокабулар',
  words: []
};

export type ThemeId = 'alltag' | 'essen' | 'arbeit' | 'reise' | 'familie' | 'natur' | 'zeit' | 'gefühl' | 'aktion' | 'ort' | 'vocab';

export function getThemeById(id: string): WordleTheme | undefined {
  return WORDLE_THEMES.find(t => t.id === id);
}
